/**
 * AUTO-GENERATED by tools/gen.ts from specs/ir.json.
 * Do not edit directly — run `bun run gen` instead.
 */

import type { Currency, CultureName, FiscalDataOperator } from "./handbooks.js";
import type { Payer, CloudPaymentsJsonData, KktCorrectionReceiptData, KktReceipt, KktReceiptType, KktTaxationSystem } from "../models.js";

/**
 * Метод для получения информации по БС для обоих типов сделки (N:1 и 1:N)
 * Публичный метод для получения информации по массиву **EscrowAccumulationId**, который позволяет получить:
 * @see https://developers.cloudpayments.ru/#metod-dlya-polucheniya-informatsii-po-bs-dlya-oboih-tipov-sdelki-n-1-i-1-n
 */
export interface EscrowGetInfoRequest {
	/** Идентификаторы безопасных сделок */
	EscrowAccumulationIds: string[];
}

export const ESCROW_GET_INFO_URL = "/Escrow/GetEscrowInfo" as const;

/**
 * Тестовый метод
 * Для проверки взаимодействия с API можно вызвать тестовый метод.
 * @see https://developers.cloudpayments.ru/#testovyy-metod
 */
export type PaymentsTestRequest = Record<string, never>;

export const PAYMENTS_TEST_URL = "/test" as const;

/**
 * Оплата по криптограмме
 * Метод для оплаты по криптограмме платежных данных результат алгоритма шифрования. Для формирования криптограммы воспользуйтесь скриптом [Checkout](#skript-checkout).
 * @see https://developers.cloudpayments.ru/#oplata-po-kriptogramme
 */
export interface PaymentsChargeCryptogramRequest {
	/** Cумма платежа в валюте, разделитель точка. Количество не нулевых знаков после точки – 2 */
	Amount: number;
	/** Валюта: RUB/USD/EUR/GBP ([см. справочник](#spisok-valyut)). Если параметр не передан, то по умолчанию принимает значение RUB */
	Currency?: Currency;
	/** IP-адрес плательщика */
	IpAddress: string;
	/** [Криптограмма платежных данных](#skript-checkout) */
	CardCryptogramPacket: string;
	/** Имя держателя карты латиницей */
	Name?: string;
	/** Адрес сайта, с которого совершается вызов скрипта checkout */
	PaymentUrl?: string;
	/** Номер счета или заказа */
	InvoiceId?: string;
	/** Описание оплаты в свободной форме */
	Description?: string;
	/** Язык уведомлений. Возможные значения: "ru-RU", "en-US". ([см. справочник](#lokalizatsiya)) */
	CultureName?: CultureName;
	/** Обязательный идентификатор пользователя для создания подписки и получения токена */
	AccountId?: string;
	/** E-mail плательщика, на который будет отправлена квитанция об оплате */
	Email?: string;
	/** Доп. поле, куда передается информация о плательщике. Используйте следующие параметры: `FirstName`, `LastName`, `MiddleName`, `Birth`, `Street`, `Address`, `City`, `Country`, `Phone`, `Postcode` */
	Payer?: Payer;
	/** Любые другие данные, которые будут связаны с транзакцией, в том числе инструкции для [создания подписки](#rekurrentnye-platezhi-podpiska) или формирования [онлайн-чека](#format-peredachi-dannyh-dlya-onlayn-cheka) должны обёртываться в объект `cloudpayments`. Мы зарезервировали названия следующих параметров и отображаем их содержимое в реестре операций, выгружаемом в Личном Кабинете: `name`, `firstName`, `middleName`, `lastName`, `nick`, `phone`, `address`, `comment`, `birthDate`. */
	JsonData?: CloudPaymentsJsonData;
	/** Признак сохранения карточного токена для проведения оплаты по сохранённой карте (см. [Оплата по токену (рекарринг)](#oplata-po-tokenu-rekarring)). Возможные значения: `true` - после успешной оплаты будет возвращён карточный токен, `false` - токен не будет возвращаться (по-умолчанию) Параметр SaveCard обрабатывается только при включении настройки "Сохранение токена карты" в Личном Кабинете. При включении настройки "Сохранять принудительно", параметр SaveCard будет игнорироваться. */
	SaveCard?: boolean;
}

export const PAYMENTS_CHARGE_CRYPTOGRAM_URL = "/payments/cards/charge" as const;

/**
 * Оплата по криптограмме
 * Метод для оплаты по криптограмме платежных данных результат алгоритма шифрования. Для формирования криптограммы воспользуйтесь скриптом [Checkout](#skript-checkout).
 * @see https://developers.cloudpayments.ru/#oplata-po-kriptogramme
 */
export interface PaymentsAuthCryptogramRequest {
	/** Cумма платежа в валюте, разделитель точка. Количество не нулевых знаков после точки – 2 */
	Amount: number;
	/** Валюта: RUB/USD/EUR/GBP ([см. справочник](#spisok-valyut)). Если параметр не передан, то по умолчанию принимает значение RUB */
	Currency?: Currency;
	/** IP-адрес плательщика */
	IpAddress: string;
	/** [Криптограмма платежных данных](#skript-checkout) */
	CardCryptogramPacket: string;
	/** Имя держателя карты латиницей */
	Name?: string;
	/** Адрес сайта, с которого совершается вызов скрипта checkout */
	PaymentUrl?: string;
	/** Номер счета или заказа */
	InvoiceId?: string;
	/** Описание оплаты в свободной форме */
	Description?: string;
	/** Язык уведомлений. Возможные значения: "ru-RU", "en-US". ([см. справочник](#lokalizatsiya)) */
	CultureName?: CultureName;
	/** Обязательный идентификатор пользователя для создания подписки и получения токена */
	AccountId?: string;
	/** E-mail плательщика, на который будет отправлена квитанция об оплате */
	Email?: string;
	/** Доп. поле, куда передается информация о плательщике. Используйте следующие параметры: `FirstName`, `LastName`, `MiddleName`, `Birth`, `Street`, `Address`, `City`, `Country`, `Phone`, `Postcode` */
	Payer?: Payer;
	/** Любые другие данные, которые будут связаны с транзакцией, в том числе инструкции для [создания подписки](#rekurrentnye-platezhi-podpiska) или формирования [онлайн-чека](#format-peredachi-dannyh-dlya-onlayn-cheka) должны обёртываться в объект `cloudpayments`. Мы зарезервировали названия следующих параметров и отображаем их содержимое в реестре операций, выгружаемом в Личном Кабинете: `name`, `firstName`, `middleName`, `lastName`, `nick`, `phone`, `address`, `comment`, `birthDate`. */
	JsonData?: CloudPaymentsJsonData;
	/** Признак сохранения карточного токена для проведения оплаты по сохранённой карте (см. [Оплата по токену (рекарринг)](#oplata-po-tokenu-rekarring)). Возможные значения: `true` - после успешной оплаты будет возвращён карточный токен, `false` - токен не будет возвращаться (по-умолчанию) Параметр SaveCard обрабатывается только при включении настройки "Сохранение токена карты" в Личном Кабинете. При включении настройки "Сохранять принудительно", параметр SaveCard будет игнорироваться. */
	SaveCard?: boolean;
}

export const PAYMENTS_AUTH_CRYPTOGRAM_URL = "/payments/cards/auth" as const;

/**
 * Пример формы:
 * @see https://developers.cloudpayments.ru/#primer-formy
 */
export interface PaymentsPost3dsRequest {
	/** Значение параметра MD */
	TransactionId: number;
	/** Значение одноименного параметра */
	PaRes: string;
}

export const PAYMENTS_POST3DS_URL = "/payments/cards/post3ds" as const;

/**
 * Оплата по токену (рекарринг)
 * Метод для оплаты по токену, полученному при [оплате по криптограмме](#oplata-po-kriptogramme), либо через [Pay](#pay)-уведомление.
 * @see https://developers.cloudpayments.ru/#oplata-po-tokenu-rekarring
 */
export interface PaymentsChargeTokenRequest {
	/** Cумма платежа в валюте, разделитель точка. Количество не нулевых знаков после точки – 2 */
	Amount: number;
	/** Валюта: RUB/USD/EUR/GBP (см. [справочник](#spisok-valyut)). Если параметр не передан, то по умолчанию принимает значение RUB */
	Currency?: Currency;
	/** Идентификатор пользователя */
	AccountId: string;
	/** Признак инициатора списания денежных средств. Возможные значения: 0 - транзакция инициирована ТСП на основе ранее сохраненных учетных данных; 1 - транзакция инициирована держателем карты (клиентом) на основе ранее сохраненных учетных данных. **ВАЖНО!** В случае, если транзакция инициирована ТСП, необходимо дополнительно в запросе указать параметр PaymentScheduled с корректным значением. */
	TrInitiatorCode: number;
	/** Признак оплаты по расписанию на основе ранее сохраненных учетных данных. Возможные значения: 0 - без расписания; 1 - по расписанию. **ВАЖНО!** В случае, если при запросе данный параметр не указан, по умолчанию будет использоваться значение 0. */
	PaymentScheduled?: number;
	/** Токен */
	Token: string;
	/** Номер счета или заказа */
	InvoiceId?: string;
	/** Назначение платежа в свободной форме */
	Description?: string;
	/** IP-адрес плательщика */
	IpAddress?: string;
	/** E-mail плательщика, на который будет отправлена квитанция об оплате */
	Email?: string;
	/** Доп. поле, куда передается информация о плательщике. Используйте следующие параметры: `FirstName`, `LastName`, `MiddleName`, `Birth`, `Street`, `Address`, `City`, `Country`, `Phone`, `Postcode` */
	Payer?: Payer;
	/** Любые другие данные, которые будут связаны с транзакцией, в том числе инструкции для [создания подписки](#rekurrentnye-platezhi-podpiska) или формирования [онлайн-чека](#format-peredachi-dannyh-dlya-onlayn-cheka) должны обёртываться в объект `cloudpayments`. Мы зарезервировали названия следующих параметров и отображаем их содержимое в реестре операций, выгружаемом в Личном Кабинете: `name`, `firstName`, `middleName`, `lastName`, `nick`, `phone`, `address`, `comment`, `birthDate`. */
	JsonData?: CloudPaymentsJsonData;
}

export const PAYMENTS_CHARGE_TOKEN_URL = "/payments/tokens/charge" as const;

/**
 * Оплата по токену (рекарринг)
 * Метод для оплаты по токену, полученному при [оплате по криптограмме](#oplata-po-kriptogramme), либо через [Pay](#pay)-уведомление.
 * @see https://developers.cloudpayments.ru/#oplata-po-tokenu-rekarring
 */
export interface PaymentsAuthTokenRequest {
	/** Cумма платежа в валюте, разделитель точка. Количество не нулевых знаков после точки – 2 */
	Amount: number;
	/** Валюта: RUB/USD/EUR/GBP (см. [справочник](#spisok-valyut)). Если параметр не передан, то по умолчанию принимает значение RUB */
	Currency?: Currency;
	/** Идентификатор пользователя */
	AccountId: string;
	/** Признак инициатора списания денежных средств. Возможные значения: 0 - транзакция инициирована ТСП на основе ранее сохраненных учетных данных; 1 - транзакция инициирована держателем карты (клиентом) на основе ранее сохраненных учетных данных. **ВАЖНО!** В случае, если транзакция инициирована ТСП, необходимо дополнительно в запросе указать параметр PaymentScheduled с корректным значением. */
	TrInitiatorCode: number;
	/** Признак оплаты по расписанию на основе ранее сохраненных учетных данных. Возможные значения: 0 - без расписания; 1 - по расписанию. **ВАЖНО!** В случае, если при запросе данный параметр не указан, по умолчанию будет использоваться значение 0. */
	PaymentScheduled?: number;
	/** Токен */
	Token: string;
	/** Номер счета или заказа */
	InvoiceId?: string;
	/** Назначение платежа в свободной форме */
	Description?: string;
	/** IP-адрес плательщика */
	IpAddress?: string;
	/** E-mail плательщика, на который будет отправлена квитанция об оплате */
	Email?: string;
	/** Доп. поле, куда передается информация о плательщике. Используйте следующие параметры: `FirstName`, `LastName`, `MiddleName`, `Birth`, `Street`, `Address`, `City`, `Country`, `Phone`, `Postcode` */
	Payer?: Payer;
	/** Любые другие данные, которые будут связаны с транзакцией, в том числе инструкции для [создания подписки](#rekurrentnye-platezhi-podpiska) или формирования [онлайн-чека](#format-peredachi-dannyh-dlya-onlayn-cheka) должны обёртываться в объект `cloudpayments`. Мы зарезервировали названия следующих параметров и отображаем их содержимое в реестре операций, выгружаемом в Личном Кабинете: `name`, `firstName`, `middleName`, `lastName`, `nick`, `phone`, `address`, `comment`, `birthDate`. */
	JsonData?: CloudPaymentsJsonData;
}

export const PAYMENTS_AUTH_TOKEN_URL = "/payments/tokens/auth" as const;

/**
 * Подтверждение оплаты
 * Для платежей, проведенных по [двухстадийной схеме](#shemy-provedeniya-platezha), необходимо подтверждение оплаты, которое можно выполнить через личный кабинет, либо через вызов метода API.
 * @see https://developers.cloudpayments.ru/#podtverzhdenie-oplaty
 */
export interface PaymentsConfirmRequest {
	/** Номер транзакции в системе */
	TransactionId: number;
	/** Сумма подтверждения в валюте транзакции, разделитель точка. Количество не нулевых знаков после точки – 2. */
	Amount: number;
	/** Любые другие данные, которые будут связаны с транзакцией, в том числе инструкции для формирования [онлайн-чека](#format-peredachi-dannyh-dlya-onlayn-cheka) */
	JsonData?: CloudPaymentsJsonData;
}

export const PAYMENTS_CONFIRM_URL = "/payments/confirm" as const;

/**
 * Отмена оплаты
 * Отмену оплаты можно выполнить через личный кабинет либо через вызов метода API.
 * @see https://developers.cloudpayments.ru/#otmena-oplaty
 */
export interface PaymentsVoidRequest {
	/** Номер транзакции в системе */
	TransactionId: number;
}

export const PAYMENTS_VOID_URL = "/payments/void" as const;

/**
 * Возврат денег
 * Возврат денег можно выполнить через личный кабинет или через вызов метода API.
 * @see https://developers.cloudpayments.ru/#vozvrat-deneg
 */
export interface PaymentsRefundRequest {
	/** Номер транзакции оплаты */
	TransactionId: number;
	/** Сумма возврата в валюте транзакции, разделитель точка. Количество не нулевых знаков после точки – 2. */
	Amount: number;
	/** Любые другие данные, которые будут связаны с транзакцией, в том числе инструкции для формирования [онлайн-чека](#format-peredachi-dannyh-dlya-onlayn-cheka) */
	JsonData?: CloudPaymentsJsonData;
}

export const PAYMENTS_REFUND_URL = "/payments/refund" as const;

/**
 * Выплата по криптограмме
 * Выплату по криптограмме можно осуществить через вызов метода API.
 * @see https://developers.cloudpayments.ru/#vyplata-po-kriptogramme
 */
export interface PaymentsPayoutCryptogramRequest {
	/** Криптограмма платежных данных */
	CardCryptogramPacket: string;
	/** Cумма платежа в валюте, разделитель точка. Количество не нулевых знаков после точки – 2 */
	Amount: number;
	/** Валюта: RUB */
	Currency: Currency;
	/** Имя держателя карты латиницей */
	Name?: string;
	/** Идентификатор пользователя */
	AccountId?: string;
	/** E-mail плательщика, на который будет отправлена квитанция об оплате */
	Email?: string;
	/** Любые другие данные, которые будут связаны с транзакцией. Мы зарезервировали названия следующих параметров и отображаем их содержимое в реестре операций, выгружаемом в Личном Кабинете: `name`, `firstName`, `middleName`, `lastName`, `nick`, `phone`, `address`, `comment`, `birthDate`. */
	JsonData?: CloudPaymentsJsonData;
	/** Номер заказа в вашей системе */
	InvoiceId?: string;
	/** Описание оплаты в свободной форме */
	Description?: string;
	/** Доп. поле, куда передается информация о плательщике */
	Payer?: Payer;
	/** Доп. поле, куда передается информация о получателе */
	Receiver?: Payer;
}

export const PAYMENTS_PAYOUT_CRYPTOGRAM_URL = "/payments/cards/topup" as const;

/**
 * Выплата по токену
 * Выплату по токену можно осуществить через вызов метода API.
 * @see https://developers.cloudpayments.ru/#vyplata-po-tokenu
 */
export interface PaymentsPayoutTokenRequest {
	/** Токен карты, выданный системой после первого платежа */
	Token: string;
	/** Cумма платежа в валюте, разделитель точка. Количество не нулевых знаков после точки – 2 */
	Amount: number;
	/** Идентификатор пользователя */
	AccountId: string;
	/** Валюта: RUB */
	Currency: Currency;
	/** Номер заказа в вашей системе */
	InvoiceId?: string;
	/** Доп. поле, куда передается информация о плательщике */
	Payer?: Payer;
	/** Доп. поле, куда передается информация о получателе */
	Receiver?: Payer;
}

export const PAYMENTS_PAYOUT_TOKEN_URL = "/payments/token/topup" as const;

/**
 * Выплата по СБП
 * Выплату по СБП можно осуществить через вызов метода API.
 * @see https://developers.cloudpayments.ru/#vyplata-po-sbp
 */
export interface PaymentsPayoutSbpRequest {
	/** Идентификатор банка получателя НПСК для СБП Если в запросе поле `Receiver.Phone` заполнено, то `MemberId` обязательное Допустимые значения для `MemberId` можно найти по [ссылке](https://qr.nspk.ru/proxyapp/c2bmembers.json). Значение из поля `schema` в поле `MemberId` надо передать только цифровое значение из поля `schema` Например, для `schema:bank100000000111` передать `MemberId:100000000111` */
	MemberId?: string;
	/** Cумма платежа в валюте, разделитель точка. Количество не нулевых знаков после точки – 2 */
	Amount: number;
	/** Валюта: RUB */
	Currency: Currency;
	/** Идентификатор пользователя */
	AccountId?: string;
	/** E-mail плательщика, на который будет отправлена квитанция об оплате */
	Email?: string;
	/** Язык уведомлений. Возможные значения: "ru-RU", "en-US". ([см. справочник](#lokalizatsiya)) */
	CultureName?: CultureName;
	/** Номер заказа в вашей системе */
	InvoiceId?: string;
	/** Описание оплаты в свободной форме */
	Description?: string;
	/** Доп. поле, куда передается информация о плательщике. Используйте следующие параметры: `FirstName`, `LastName`, `MiddleName`, `Birth`, `Street`, `Address`, `City`, `Country`, `Phone`, `Postcode` */
	Payer?: Payer;
	/** Доп. поле, куда передается информация о получателе */
	Receiver: Payer & { Phone: string };
}

export const PAYMENTS_PAYOUT_SBP_URL = "/payments/alt/topup" as const;

/**
 * Просмотр транзакции
 * Метод получения детализации по транзакции.
 * @see https://developers.cloudpayments.ru/#prosmotr-tranzaktsii
 */
export interface PaymentsGetRequest {
	/** Номер транзакции */
	TransactionId: number;
}

export const PAYMENTS_GET_URL = "/payments/get" as const;

/**
 * Проверка статуса платежа
 * Метод поиска платежа и проверки статуса (см. [справочник](#statusy-operatsiy)).
 * @see https://developers.cloudpayments.ru/#proverka-statusa-platezha
 */
export interface PaymentsFindLegacyRequest {
	/** Номер заказа */
	InvoiceId: string;
}

export const PAYMENTS_FIND_LEGACY_URL = "/payments/find" as const;

/**
 * Проверка статуса платежа
 * Метод поиска платежа и проверки статуса (см. [справочник](#statusy-operatsiy)).
 * @see https://developers.cloudpayments.ru/#proverka-statusa-platezha
 */
export interface PaymentsFindRequest {
	/** Номер заказа */
	InvoiceId: string;
}

export const PAYMENTS_FIND_URL = "/v2/payments/find" as const;

/**
 * Выгрузка списка транзакций
 * Метод выгрузки списка транзакций за день.
 * @see https://developers.cloudpayments.ru/#vygruzka-spiska-tranzaktsiy
 */
export interface PaymentsListByDayRequest {
	/** Дата создания операций */
	Date: string;
	/** Код временной зоны, по умолчанию — UTC */
	TimeZone?: string;
}

export const PAYMENTS_LIST_BY_DAY_URL = "/payments/list" as const;

/**
 * Выгрузка списка транзакций за произвольный период
 * Метод выгрузки списка транзакций за произвольный период.
 * @see https://developers.cloudpayments.ru/#vygruzka-spiska-tranzaktsiy-za-proizvolnyy-period
 */
export interface PaymentsListByPeriodRequest {
	/** Начальная дата создания операций */
	CreatedDateGte: string;
	/** Конечная дата создания операций */
	CreatedDateLte: string;
	/** порядковый номер страницы, должно быть больше или равно 1 */
	PageNumber: number;
	/** Код временной зоны, по умолчанию — UTC */
	TimeZone?: string;
	/** Статус операция. Может иметь значения [ "Authorized", "Completed", "Cancelled", "Declined" ]. По умолчанию выбраны все */
	Statuses?: string;
}

export const PAYMENTS_LIST_BY_PERIOD_URL = "/v2/payments/list" as const;

/**
 * Выгрузка списка претензий за произвольный период
 * Метод выгрузки списка претензий за произвольный период, но не более чем за 1 год. Для выгрузки требуется отправить http-запрос с типом авторизации “Basic Auth”. Логин - public key (pk) терминала.
 * @see https://developers.cloudpayments.ru/#vygruzka-spiska-pretenziy-za-proizvolnyy-period
 */
export interface PaymentsListClaimsByPeriodRequest {
	/** Начальная дата создания претензии */
	CreatedDateGte: string;
	/** Конечная дата создания претензии */
	CreatedDateLte: string;
	/** Порядковый номер страницы, должно быть больше или равно 1 */
	PageNumber: number;
}

export const PAYMENTS_LIST_CLAIMS_BY_PERIOD_URL = "/chargebacks/list" as const;

/**
 * Выгрузка токенов
 * Метод выгрузки списка всех платежных токенов CloudPayments.
 * @see https://developers.cloudpayments.ru/#vygruzka-tokenov
 */
export interface PaymentsListTokensRequest {
	/** Порядковый номер страницы, должно быть больше или равно 1 */
	PageNumber: number;
}

export const PAYMENTS_LIST_TOKENS_URL = "/payments/tokens/list" as const;

/**
 * Создание подписки на рекуррентные платежи
 * Метод создания подписки на рекуррентные платежи.
 * @see https://developers.cloudpayments.ru/#sozdanie-podpiski-na-rekurrentnye-platezhi
 */
export interface SubscriptionsCreateRequest {
	/** Токен карты, выданный системой после первого платежа */
	Token: string;
	/** Идентификатор пользователя */
	AccountId: string;
	/** Назначение платежа в свободной форме */
	Description: string;
	/** E-mail плательщика */
	Email?: string;
	/** Cумма платежа в валюте, разделитель точка. Количество не нулевых знаков после точки – 2 */
	Amount: number;
	/** Валюта: RUB/USD/EUR/GBP (см. [справочник](#spisok-valyut)) */
	Currency: Currency;
	/** Если значение true — платежи будут выполняться по двухстадийной схеме */
	RequireConfirmation: boolean;
	/** Дата и время первого платежа по плану во временной зоне UTC. Значение должно быть в будущем */
	StartDate: string;
	/** Интервал. Возможные значения: Day, Week, Month */
	Interval: string;
	/** Период. В комбинации с интервалом, 1 Month значит раз в месяц, а 2 Week — раз в две недели. Должен быть больше 0 */
	Period: number;
	/** Максимальное количество платежей в подписке. Если указан, должен быть больше 0 */
	MaxPeriods?: number;
	/** Для изменения состава [онлайн-чека](#format-peredachi-dannyh-dlya-onlayn-cheka) */
	CustomerReceipt?: KktReceipt;
}

export const SUBSCRIPTIONS_CREATE_URL = "/subscriptions/create" as const;

/**
 * Запрос информации о подписке
 * Метод получения информации о статусе подписки.
 * @see https://developers.cloudpayments.ru/#zapros-informatsii-o-podpiske
 */
export interface SubscriptionsGetRequest {
	/** Идентификатор подписки */
	Id: string;
}

export const SUBSCRIPTIONS_GET_URL = "/subscriptions/get" as const;

/**
 * Поиск подписок
 * Метод получения списка подписок для определенного аккаунта.
 * @see https://developers.cloudpayments.ru/#poisk-podpisok
 */
export interface SubscriptionsFindByAccountRequest {
	/** Идентификатор пользователя */
	accountId: string;
}

export const SUBSCRIPTIONS_FIND_BY_ACCOUNT_URL = "/subscriptions/find" as const;

/**
 * Изменение подписки на рекуррентные платежи
 * Метод изменения ранее созданной подписки.
 * @see https://developers.cloudpayments.ru/#izmenenie-podpiski-na-rekurrentnye-platezhi
 */
export interface SubscriptionsUpdateRequest {
	/** Идентификатор подписки */
	Id: string;
	/** Для изменения назначения платежа */
	Description?: string;
	/** Для изменения суммы платежа в валюте, разделитель точка. Количество не нулевых знаков после точки – 2. */
	Amount?: number;
	/** Для изменения валюты: RUB/USD/EUR/GBP ([см. справочник](#spisok-valyut)) */
	Currency?: Currency;
	/** Для изменения схемы проведения платежей */
	RequireConfirmation?: boolean;
	/** Для изменения даты и времени первого или следующего платежа во временной зоне UTC */
	StartDate?: string;
	/** Для изменения интервала. Возможные значения: Day, Week, Month */
	Interval?: string;
	/** Для изменения периода. В комбинации с интервалом, 1 Month значит раз в месяц, а 2 Week — раз в две недели */
	Period?: number;
	/** Для изменения максимального количества платежей в подписке */
	MaxPeriods?: number;
	/** Для изменения состава [онлайн-чека](#format-peredachi-dannyh-dlya-onlayn-cheka) */
	CustomerReceipt?: KktReceipt;
	/** Язык уведомлений. Возможные значения: "ru-RU", "en-US". ([см. справочник](#lokalizatsiya)) */
	CultureName?: CultureName;
}

export const SUBSCRIPTIONS_UPDATE_URL = "/subscriptions/update" as const;

/**
 * Отмена подписки на рекуррентные платежи
 * Метод отмены подписки на рекуррентные платежи.
 * @see https://developers.cloudpayments.ru/#otmena-podpiski-na-rekurrentnye-platezhi
 */
export interface SubscriptionsCancelRequest {
	/** Идентификатор подписки */
	Id: string;
}

export const SUBSCRIPTIONS_CANCEL_URL = "/subscriptions/cancel" as const;

/**
 * Создание счета для отправки по почте
 * Метод формирования ссылки на оплату и последующей отправки уведомления на e-mail адрес плательщика.
 * @see https://developers.cloudpayments.ru/#sozdanie-scheta-dlya-otpravki-po-pochte
 */
export interface OrdersCreateRequest {
	/** Cумма платежа в валюте, разделитель точка. Количество не нулевых знаков после точки – 2 */
	Amount: number;
	/** Валюта RUB/USD/EUR/GBP ([см. справочник](#spisok-valyut)). Если параметр не передан, то по умолчанию принимает значение RUB */
	Currency?: Currency;
	/** Назначение платежа в свободной форме */
	Description: string;
	/** E-mail плательщика */
	Email?: string;
	/** Есть значение true — платеж будет выполнен по двухстадийной схеме */
	RequireConfirmation?: boolean;
	/** Если значение true — плательщик получит письмо со ссылкой на оплату */
	SendEmail?: boolean;
	/** Номер заказа в вашей системе */
	InvoiceId?: string;
	/** Идентификатор пользователя в вашей системе */
	AccountId?: string;
	/** Ссылка на оферту, которая будет показываться на странице заказа */
	OfferUri?: string;
	/** Номер телефона плательщика в произвольном формате */
	Phone?: string;
	/** Если значение true — плательщик получит СМС со ссылкой на оплату */
	SendSms?: boolean;
	/** Если значение true — плательщик получит сообщение в Viber со ссылкой на оплату */
	SendViber?: boolean;
	/** Язык уведомлений. Возможные значения: "ru-RU", "en-US". ([см. справочник](#lokalizatsiya)) */
	CultureName?: CultureName;
	/** Для создания платежа с подпиской. Возможные значения: CreateWeekly, CreateMonthly */
	SubscriptionBehavior?: string;
	/** Адрес страницы для редиректа при успешной оплате */
	SuccessRedirectUrl?: string;
	/** Адрес страницы для редиректа при неуспешной оплате */
	FailRedirectUrl?: string;
	/** Любые другие данные, которые будут связаны с транзакцией, в том числе инструкции для формирования [онлайн-чека](#format-peredachi-dannyh-dlya-onlayn-cheka) должны обёртываться в объект `cloudpayments` */
	JsonData?: CloudPaymentsJsonData;
}

export const ORDERS_CREATE_URL = "/orders/create" as const;

/**
 * Отмена созданного счета
 * Метод отмены созданного счета:
 * @see https://developers.cloudpayments.ru/#otmena-sozdannogo-scheta
 */
export interface OrdersCancelRequest {
	/** Идентификатор счета */
	Id: string;
}

export const ORDERS_CANCEL_URL = "/orders/cancel" as const;

/**
 * Просмотр настроек уведомлений
 * Метод просмотра настроек уведомлений с указанием типа уведомления.
 * @see https://developers.cloudpayments.ru/#prosmotr-nastroek-uvedomleniy
 */
export interface SettingsGetNotificationRequest {
	/** Тип уведомления: Check/Pay/Fail и т.д. (см. [справочник](#tipy-operatsiy)) */
	Type: string;
}

export const SETTINGS_GET_NOTIFICATION_URL = "/site/notifications/{Type}/get" as const;

/**
 * Изменение настроек уведомлений
 * Метод изменения настроек уведомлений.
 * @see https://developers.cloudpayments.ru/#izmenenie-nastroek-uvedomleniy
 */
export interface SettingsUpdateNotificationRequest {
	/** Тип уведомления: Pay/Fail и т.д., кроме Check-уведомления (см. [справочник](#tipy-operatsiy)) */
	Type: string;
	/** Если значение true — то уведомление включено. Значение по умолчанию — false */
	IsEnabled?: boolean;
	/** Адрес для отправки уведомлений (для HTTPS-схемы необходим валидный SSL-сертификат) */
	Address?: string;
	/** HTTP-метод для отправки уведомлений. Возможные значения: GET, POST. Значение по умолчанию — GET */
	HttpMethod?: string;
	/** Кодировка уведомлений. Возможные значения: UTF8, Windows1251. Значение по умолчанию — UTF8 */
	Encoding?: string;
	/** Формат уведомлений. Возможные значения: CloudPayments, QIWI, RT. Значение по умолчанию — CloudPayments */
	Format?: string;
}

export const SETTINGS_UPDATE_NOTIFICATION_URL = "/site/notifications/{Type}/update" as const;

/**
 * Получение ссылки для оплаты
 * @see https://developers.cloudpayments.ru/#poluchenie-ssylki-dlya-oplaty
 */
export interface TPayCreateLinkRequest {
	/** Идентификатор сайта, который находится в ЛК */
	publicId: string;
	/** Cумма платежа в валюте, разделитель точка. Количество не нулевых знаков после точки – 2 */
	Amount: number;
	/** Валюта: RUB (см. [справочник](#spisok-valyut)) */
	Currency: Currency;
	/** Схема проведения платежа (см. [Виды операций](#vidy-operatsiy)). Возможные значения: `0` - одностадийная оплата `1` - двухстадийная оплата */
	Scheme: 0 | 1;
	/** Название браузера клиента на основании userAgent браузера. Пример значения: `Chrome`, `Firefox`, `MIUI Browser`, `Opera` */
	Browser: string;
	/** Операционная система устройства плательщика. Пример значения: `Android`, `iOS`, `Windows` */
	Os: string;
	/** Признак открытия браузера в режиме webview. Возможные значения: `true` - для оплат через webview `false` - для оплат без webview */
	Webview: boolean;
	/** Признак устройства плательщика. Возможные значения: `MobileApp` - вызов оплаты из мобильного приложения `DesktopWeb` - вызов оплаты из браузера с десктопа `Mobile` - вызов из браузера с мобильного устройства */
	Device: "MobileApp" | "DesktopWeb" | "Mobile";
	/** Url для перенаправления клиента после успешной оплаты. После проведения платежа, клиент будет перенаправлен на указанный адрес из мобильного приложения Банка. */
	SuccessRedirectUrl: string;
	/** Url для перенаправления клиента после неуспешной оплаты. После проведения платежа, клиент будет перенаправлен на указанный адрес из мобильного приложения Банка. */
	FailRedirectUrl: string;
	/** IP-адрес плательщика */
	IpAddress?: string;
	/** Идентификатор пользователя */
	AccountId?: string;
	/** E-mail плательщика */
	Email?: string;
	/** Номер счёта или заказа */
	InvoiceId?: string;
	/** Назначение платежа в свободной форме */
	Description?: string;
	/** Любые другие данные, которые будут связаны с транзакцией, в том числе [инструкции](#rekurrentnye-platezhi-podpiska) для создания подписки или формирования [онлайн-чека](#format-peredachi-dannyh-dlya-onlayn-cheka) должны обёртываться в объект `cloudpayments`. Мы зарезервировали названия следующих параметров и отображаем их содержимое в реестре операций, выгружаемом в Личном Кабинете: `name`, `firstName`, `middleName`, `lastName`, `nick`, `phone`, `address`, `comment`, `birthDate` */
	JsonData?: CloudPaymentsJsonData;
	/** Время в течение которого будет доступна оплата по QR-коду / ссылке на оплату. Если параметр не передан, оплату можно будет совершить в течение 24 часов. **Важно:** - Значение 0 считается **некорректным** и может привести к ошибке обработки запроса. - Если временное ограничение не требуется, параметр следует **не передавать** или явно указать как `null`. */
	TtlMinutes?: number | null;
	/** Признак сохранения карточного токена для проведения оплаты по сохранённой карте (см. [Оплата по токену (рекарринг)](#oplata-po-tokenu-rekarring)). Возможные значения: `true` - после успешной оплаты будет возвращён карточный токен, `false` - токен не будет возвращаться (по-умолчанию) Параметр SaveCard обрабатывается только при включении настройки "Сохранение токена карты" в Личном Кабинете. При включении настройки "Сохранять принудительно", параметр SaveCard будет игнорироваться. */
	SaveCard?: boolean;
}

export const T_PAY_CREATE_LINK_URL = "/payments/qr/tinkoffpay/link" as const;

/**
 * Получение QR-кода для оплаты
 * @see https://developers.cloudpayments.ru/#poluchenie-qr-koda-dlya-oplaty
 */
export interface TPayCreateQrImageRequest {
	/** Идентификатор сайта, который находится в ЛК */
	publicId: string;
	/** Cумма платежа в валюте, разделитель точка. Количество не нулевых знаков после точки – 2 */
	Amount: number;
	/** Валюта: RUB (см. [справочник](#spisok-valyut)) */
	Currency: Currency;
	/** Схема проведения платежа (см. [Виды операций](#vidy-operatsiy)). Возможные значения: `0` - одностадийная оплата `1` - двухстадийная оплата */
	Scheme: 0 | 1;
	/** Название браузера клиента на основании userAgent браузера. Пример значения: `Chrome`, `Firefox`, `MIUI Browser`, `Opera` */
	Browser: string;
	/** Операционная система устройства плательщика. Пример значения: `Android`, `iOS`, `Windows` */
	Os: string;
	/** Признак открытия браузера в режиме webview. Возможные значения: `true` - для оплат через webview `false` - для оплат без webview */
	Webview: boolean;
	/** Признак устройства плательщика. Возможные значения: `MobileApp` - вызов оплаты из мобильного приложения `DesktopWeb` - вызов оплаты из браузера с десктопа `Mobile` - вызов из браузера с мобильного устройства */
	Device: "MobileApp" | "DesktopWeb" | "Mobile";
	/** Url для перенаправления клиента после успешной оплаты. После проведения платежа, клиент будет перенаправлен на указанный адрес из мобильного приложения Банка. */
	SuccessRedirectUrl: string;
	/** Url для перенаправления клиента после неуспешной оплаты. После проведения платежа, клиент будет перенаправлен на указанный адрес из мобильного приложения Банка. */
	FailRedirectUrl: string;
	/** IP-адрес плательщика */
	IpAddress?: string;
	/** Идентификатор пользователя */
	AccountId?: string;
	/** E-mail плательщика */
	Email?: string;
	/** Номер счёта или заказа */
	InvoiceId?: string;
	/** Назначение платежа в свободной форме */
	Description?: string;
	/** Любые другие данные, которые будут связаны с транзакцией, в том числе [инструкции](#rekurrentnye-platezhi-podpiska) для создания подписки или формирования [онлайн-чека](#format-peredachi-dannyh-dlya-onlayn-cheka) должны обёртываться в объект `cloudpayments`. Мы зарезервировали названия следующих параметров и отображаем их содержимое в реестре операций, выгружаемом в Личном Кабинете: `name`, `firstName`, `middleName`, `lastName`, `nick`, `phone`, `address`, `comment`, `birthDate` */
	JsonData?: CloudPaymentsJsonData;
	/** Время в течение которого будет доступна оплата по QR-коду / ссылке на оплату. Если параметр не передан, оплату можно будет совершить в течение 24 часов. **Важно:** - Значение 0 считается **некорректным** и может привести к ошибке обработки запроса. - Если временное ограничение не требуется, параметр следует **не передавать** или явно указать как `null`. */
	TtlMinutes?: number | null;
	/** Признак сохранения карточного токена для проведения оплаты по сохранённой карте (см. [Оплата по токену (рекарринг)](#oplata-po-tokenu-rekarring)). Возможные значения: `true` - после успешной оплаты будет возвращён карточный токен, `false` - токен не будет возвращаться (по-умолчанию) Параметр SaveCard обрабатывается только при включении настройки "Сохранение токена карты" в Личном Кабинете. При включении настройки "Сохранять принудительно", параметр SaveCard будет игнорироваться. */
	SaveCard?: boolean;
}

export const T_PAY_CREATE_QR_IMAGE_URL = "/payments/qr/tinkoffpay/image" as const;

/**
 * Получение ссылки для оплаты
 * @see https://developers.cloudpayments.ru/#sbp-poluchenie-ssylki-dlya-oplaty
 */
export interface SbpCreateLinkRequest {
	/** Идентификатор сайта, который находится в ЛК */
	PublicId: string;
	/** Cумма платежа в рублях, разделитель точка. Количество не нулевых знаков после точки – 2 */
	Amount: number;
	/** Валюта: RUB (см. [справочник](#spisok-valyut)) */
	Currency: Currency;
	/** Назначение платежа в свободной форме */
	Description?: string;
	/** Идентификатор пользователя, используется для создания подписки и получения токена */
	AccountId?: string;
	/** E-mail плательщика, на который будет отправлена квитанция об оплате */
	Email?: string;
	/** Любые другие данные, которые будут связаны с транзакцией, в том числе [инструкции](#rekurrentnye-platezhi-podpiska) для создания подписки или формирования [онлайн-чека](#format-peredachi-dannyh-dlya-onlayn-cheka) должны обёртываться в объект `cloudpayments`. Мы зарезервировали названия следующих параметров и отображаем их содержимое в реестре операций, выгружаемом в Личном Кабинете: `name`, `firstName`, `middleName`, `lastName`, `nick`, `phone`, `address`, `comment`, `birthDate` */
	JsonData?: CloudPaymentsJsonData;
	/** Идентификатор/номер счета. Приходит в Check-уведомлении и может использоваться для сверки номера заказа */
	InvoiceId?: string;
	/** Схема проведения платежа (см. [Виды операций](#vidy-operatsiy)). Возможные значения: `charge` - одностадийная оплата */
	Scheme: "charge";
	/** Url для перенаправления клиента после успешной оплаты. После проведения платежа, клиент будет перенаправлен на указанный адрес из мобильного приложения Банка. Значение должно содержать не более 1024 символов, быть в кодировке ASCII и соответствовать формату спецификации RFC-3986. */
	SuccessRedirectUrl?: string;
	/** IP-адрес плательщика */
	IpAddress?: string;
	/** Операционная система устройства плательщика. Пример значения: `Android`, `iOS`, `Windows` */
	Os?: string;
	/** Признак открытия браузера в режиме webview. Возможные значения: `true` - для оплат через webview `false` - для оплат без webview */
	Webview?: boolean;
	/** Признак устройства плательщика. Возможные значения: `MobileApp` - вызов оплаты из мобильного приложения `DesktopWeb` - вызов оплаты из браузера с десктопа `Mobile` - вызов из браузера с мобильного устройства */
	Device?: "MobileApp" | "DesktopWeb" | "Mobile";
	/** Название браузера клиента на основании userAgent браузера. Пример значения: `Chrome`, `Firefox`, `MIUI Browser`, `Opera` */
	Browser?: string;
	/** Время, в течение которого будет доступна оплата по QR-коду / ссылке на оплату. Минимальное допустимое значение - "1". Максимальное допустимое значение - "129 600" (90 дней). Если параметр не передан, оплату можно будет совершить в течение 72 часов. */
	TtlMinutes?: number | null;
	/** Флаг необходимости сохранить карту для привязки счета в Национальной Системе Платежных Карт для последующих списаний */
	SaveCard?: boolean;
	/** Флаг тестового режима оплаты */
	IsTest?: boolean;
}

export const SBP_CREATE_LINK_URL = "/payments/qr/sbp/link" as const;

/**
 * Получение QR-кода для оплаты
 * @see https://developers.cloudpayments.ru/#sbp-poluchenie-qr-koda-dlya-oplaty
 */
export interface SbpCreateQrImageRequest {
	/** Идентификатор сайта, который находится в ЛК */
	PublicId: string;
	/** Cумма платежа в рублях, разделитель точка. Количество не нулевых знаков после точки – 2 */
	Amount: number;
	/** Валюта: RUB (см. [справочник](#spisok-valyut)) */
	Currency: Currency;
	/** Назначение платежа в свободной форме */
	Description?: string;
	/** Идентификатор пользователя, используется для создания подписки и получения токена */
	AccountId?: string;
	/** E-mail плательщика, на который будет отправлена квитанция об оплате */
	Email?: string;
	/** Любые другие данные, которые будут связаны с транзакцией, в том числе [инструкции](#rekurrentnye-platezhi-podpiska) для создания подписки или формирования [онлайн-чека](#format-peredachi-dannyh-dlya-onlayn-cheka) должны обёртываться в объект `cloudpayments`. Мы зарезервировали названия следующих параметров и отображаем их содержимое в реестре операций, выгружаемом в Личном Кабинете: `name`, `firstName`, `middleName`, `lastName`, `nick`, `phone`, `address`, `comment`, `birthDate` */
	JsonData?: CloudPaymentsJsonData;
	/** Идентификатор/номер счета. Приходит в Check-уведомлении и может использоваться для сверки номера заказа */
	InvoiceId?: string;
	/** Схема проведения платежа (см. [Виды операций](#vidy-operatsiy)). Возможные значения: `charge` - одностадийная оплата */
	Scheme: "charge";
	/** Url для перенаправления клиента после успешной оплаты. После проведения платежа, клиент будет перенаправлен на указанный адрес из мобильного приложения Банка. Значение должно содержать не более 1024 символов, быть в кодировке ASCII и соответствовать формату спецификации RFC-3986. */
	SuccessRedirectUrl?: string;
	/** IP-адрес плательщика */
	IpAddress?: string;
	/** Операционная система устройства плательщика. Пример значения: `Android`, `iOS`, `Windows` */
	Os?: string;
	/** Признак открытия браузера в режиме webview. Возможные значения: `true` - для оплат через webview `false` - для оплат без webview */
	Webview?: boolean;
	/** Признак устройства плательщика. Возможные значения: `MobileApp` - вызов оплаты из мобильного приложения `DesktopWeb` - вызов оплаты из браузера с десктопа `Mobile` - вызов из браузера с мобильного устройства */
	Device?: "MobileApp" | "DesktopWeb" | "Mobile";
	/** Название браузера клиента на основании userAgent браузера. Пример значения: `Chrome`, `Firefox`, `MIUI Browser`, `Opera` */
	Browser?: string;
	/** Время, в течение которого будет доступна оплата по QR-коду / ссылке на оплату. Минимальное допустимое значение - "1". Максимальное допустимое значение - "129 600" (90 дней). Если параметр не передан, оплату можно будет совершить в течение 72 часов. */
	TtlMinutes?: number | null;
	/** Флаг необходимости сохранить карту для привязки счета в Национальной Системе Платежных Карт для последующих списаний */
	SaveCard?: boolean;
	/** Флаг тестового режима оплаты */
	IsTest?: boolean;
}

export const SBP_CREATE_QR_IMAGE_URL = "/payments/qr/sbp/image" as const;

/**
 * Список участников СБП
 * @see https://developers.cloudpayments.ru/#spisok-uchastnikov-sbp
 */
export interface SbpListBanksRequest {
	AccountId?: string;
	IsRenewSubscription?: boolean;
	JsonData?: string;
	Platform?: string;
	PublicTerminalId: string;
	SaveCard?: boolean;
	Token?: string;
}

export const SBP_LIST_BANKS_URL = "/sbp/v2/banks/info" as const;

/**
 * Получение ссылки для оплаты
 * @see https://developers.cloudpayments.ru/#sberpay-poluchenie-ssylki-dlya-oplaty
 */
export interface SberPayCreateLinkRequest {
	/** Идентификатор сайта, который находится в ЛК */
	PublicId: string;
	/** Cумма платежа в рублях, разделитель точка. Количество не нулевых знаков после точки – 2 */
	Amount: number;
	/** Валюта: RUB (см. [справочник](#spisok-valyut)) */
	Currency: Currency;
	/** Назначение платежа в свободной форме */
	Description?: string;
	/** Идентификатор пользователя, используется для создания подписки и получения токена */
	AccountId?: string;
	/** E-mail плательщика, на который будет отправлена квитанция об оплате */
	Email?: string;
	/** Любые другие данные, которые будут связаны с транзакцией, в том числе [инструкции](#rekurrentnye-platezhi-podpiska) для создания подписки или формирования [онлайн-чека](#format-peredachi-dannyh-dlya-onlayn-cheka) должны обёртываться в объект `cloudpayments`. Мы зарезервировали названия следующих параметров и отображаем их содержимое в реестре операций, выгружаемом в Личном Кабинете: `name`, `firstName`, `middleName`, `lastName`, `nick`, `phone`, `address`, `comment`, `birthDate` */
	JsonData?: CloudPaymentsJsonData;
	/** Идентификатор/номер счета. Приходит в Check-уведомлении и может использоваться для сверки номера заказа */
	InvoiceId?: string;
	/** Схема проведения платежа (см. [Виды операций](#vidy-operatsiy)). Возможные значения: `charge` - одностадийная оплата; `auth` - двухстадийная оплата */
	Scheme: "charge" | "auth";
	/** Url для перенаправления клиента после успешной оплаты. После проведения платежа, клиент будет перенаправлен на указанный адрес из мобильного приложения Банка. */
	SuccessRedirectUrl?: string;
	/** IP-адрес плательщика */
	IpAddress?: string;
	/** Операционная система устройства плательщика. Пример значения: `Android`, `iOS`, `Windows` */
	Os: string;
	/** Признак открытия браузера в режиме webview. Возможные значения: `true` - для оплат через webview `false` - для оплат без webview */
	Webview: boolean;
	/** Признак устройства плательщика. Возможные значения: `MobileApp` - вызов оплаты из мобильного приложения `DesktopWeb` - вызов оплаты из браузера с десктопа `Mobile` - вызов из браузера с мобильного устройства */
	Device: "MobileApp" | "DesktopWeb" | "Mobile";
	/** Название браузера клиента на основании userAgent браузера. Пример значения: `Chrome`, `Firefox`, `MIUI Browser`, `Opera` */
	Browser: string;
}

export const SBER_PAY_CREATE_LINK_URL = "/payments/qr/sberpay/link" as const;

/**
 * Получение QR-кода для оплаты
 * @see https://developers.cloudpayments.ru/#sberpay-poluchenie-qr-koda-dlya-oplaty
 */
export interface SberPayCreateQrImageRequest {
	/** Идентификатор сайта, который находится в ЛК */
	PublicId: string;
	/** Cумма платежа в рублях, разделитель точка. Количество не нулевых знаков после точки – 2 */
	Amount: number;
	/** Валюта: RUB (см. [справочник](#spisok-valyut)) */
	Currency: Currency;
	/** Назначение платежа в свободной форме */
	Description?: string;
	/** Идентификатор пользователя, используется для создания подписки и получения токена */
	AccountId?: string;
	/** E-mail плательщика, на который будет отправлена квитанция об оплате */
	Email?: string;
	/** Любые другие данные, которые будут связаны с транзакцией, в том числе [инструкции](#rekurrentnye-platezhi-podpiska) для создания подписки или формирования [онлайн-чека](#format-peredachi-dannyh-dlya-onlayn-cheka) должны обёртываться в объект `cloudpayments`. Мы зарезервировали названия следующих параметров и отображаем их содержимое в реестре операций, выгружаемом в Личном Кабинете: `name`, `firstName`, `middleName`, `lastName`, `nick`, `phone`, `address`, `comment`, `birthDate` */
	JsonData?: CloudPaymentsJsonData;
	/** Идентификатор/номер счета. Приходит в Check-уведомлении и может использоваться для сверки номера заказа */
	InvoiceId?: string;
	/** Схема проведения платежа (см. [Виды операций](#vidy-operatsiy)). Возможные значения: `charge` - одностадийная оплата; `auth` - двухстадийная оплата */
	Scheme: "charge" | "auth";
	/** Url для перенаправления клиента после успешной оплаты. После проведения платежа, клиент будет перенаправлен на указанный адрес из мобильного приложения Банка. */
	SuccessRedirectUrl?: string;
	/** IP-адрес плательщика */
	IpAddress?: string;
	/** Операционная система устройства плательщика. Пример значения: `Android`, `iOS`, `Windows` */
	Os: string;
	/** Признак открытия браузера в режиме webview. Возможные значения: `true` - для оплат через webview `false` - для оплат без webview */
	Webview: boolean;
	/** Признак устройства плательщика. Возможные значения: `MobileApp` - вызов оплаты из мобильного приложения `DesktopWeb` - вызов оплаты из браузера с десктопа `Mobile` - вызов из браузера с мобильного устройства */
	Device: "MobileApp" | "DesktopWeb" | "Mobile";
	/** Название браузера клиента на основании userAgent браузера. Пример значения: `Chrome`, `Firefox`, `MIUI Browser`, `Opera` */
	Browser: string;
}

export const SBER_PAY_CREATE_QR_IMAGE_URL = "/payments/qr/sberpay/image" as const;

/**
 * Фискализация кассы
 * Метод перевода интернет-кассы в фискальный режим работы (первичная регистрация).
 * @see https://developers.cloudkassir.ru/#fiskalizatsiya-kassy
 */
export interface KktFiscalizeRequest {
	/** ИНН организации или индивидуального предпринимателя — пользователя кассы */
	Inn: string;
	/** Заводской номер кассы */
	DeviceNumber: string;
	/** Номер фискального накопителя */
	FiscalNumber: string;
	/** Регистрационный номер кассы */
	RegNumber: string;
	/** Адрес сайта (сайтов) — место расчетов */
	Url: string;
	/** Оператор фискальный данных, см. [справочник](#operatory-fiskalnyh-dannyh) */
	Ofd: FiscalDataOperator;
	/** Одно или несколько значений системы налогообложения, см. [справочник](#taxationsystem) */
	TaxationSystem: KktTaxationSystem[];
	/** Email магазина */
	MerchantEmail: string;
	/** Телефон магазина */
	MerchantPhone: string;
	/** Для бланков строгой отчётности (БСО) */
	IsBso?: boolean;
}

export const KKT_FISCALIZE_URL = "/kkt/fiscalize" as const;

/**
 * Формирование кассового чека
 * Метод формирования кассового чека.
 * @see https://developers.cloudkassir.ru/#formirovanie-kassovogo-cheka
 */
export interface KktSubmitReceiptRequest {
	/** ИНН вашей организации или ИП, на который зарегистрирована касса */
	Inn: string;
	/** Признак расчета, см. [ниже](#type) */
	Type: KktReceiptType;
	/** Состав чека см. [ниже](#customerreceipt) */
	CustomerReceipt: KktReceipt;
	/** Номер заказа в вашей системе */
	InvoiceId?: string;
	/** Идентификатор пользователя в вашей системе */
	AccountId?: string;
}

export const KKT_SUBMIT_RECEIPT_URL = "/kkt/receipt" as const;

/**
 * Запрос статуса чека
 * Метод получения статуса чека.
 * @see https://developers.cloudkassir.ru/#zapros-statusa-cheka
 */
export interface KktGetReceiptStatusRequest {
	/** Идентификатор чека */
	Id: string;
}

export const KKT_GET_RECEIPT_STATUS_URL = "/kkt/receipt/status/get" as const;

/**
 * Получение данных чека
 * Метод получения детализации чека.
 * @see https://developers.cloudkassir.ru/#poluchenie-dannyh-cheka
 */
export interface KktGetReceiptRequest {
	/** Идентификатор чека */
	Id: string;
}

export const KKT_GET_RECEIPT_URL = "/kkt/receipt/get" as const;

/**
 * Проверка кода маркировки
 * Для использования метода API, проверяющего маркировку товара в Системе цифровой маркировки товаров Честный знак, нужно задать настройки “Разрешительный режим“ через ЛК мерчанта в разделе “Чеки и кассы“.
 * @see https://developers.cloudkassir.ru/#proverka-koda-markirovki
 */
export interface KktValidateMarkCodeRequest {
	/** ИНН организации или индивидуального предпринимателя — пользователя кассы */
	Inn: string;
	/** Код маркировки */
	MarkCode: string;
}

export const KKT_VALIDATE_MARK_CODE_URL = "/kkt/validate-mark-code" as const;

/**
 * Массовая проверка кодов маркировки
 * Метод для проверки массива кодов маркировки.
 * @see https://developers.cloudkassir.ru/#massovaya-proverka-kodov-markirovki
 */
export interface KktValidateMarkCodesRequest {
	/** ИНН организации или индивидуального предпринимателя — пользователя кассы */
	Inn: string;
	/** Коды маркировки */
	MarkCodes: string[];
}

export const KKT_VALIDATE_MARK_CODES_URL = "/kkt/validate-mark-codes" as const;

/**
 * Формирование чека коррекции
 * Метод формирования чека коррекции.
 * @see https://developers.cloudkassir.ru/#formirovanie-cheka-korrektsii
 */
export interface KktSubmitCorrectionReceiptRequest {
	/** Состав чека см. [ниже](#correctionreceiptdata) */
	CorrectionReceiptData: KktCorrectionReceiptData;
}

export const KKT_SUBMIT_CORRECTION_RECEIPT_URL = "/kkt/correction-receipt" as const;

/**
 * Запрос статуса чека коррекции
 * Метод получения статуса чека.
 * @see https://developers.cloudkassir.ru/#zapros-statusa-cheka-korrektsii
 */
export interface KktGetCorrectionReceiptStatusRequest {
	/** Идентификатор чека */
	Id: string;
}

export const KKT_GET_CORRECTION_RECEIPT_STATUS_URL = "/kkt/correction-receipt/status/get" as const;

/**
 * Получение данных чека коррекции
 * Метод получения детализации чека.
 * @see https://developers.cloudkassir.ru/#poluchenie-dannyh-cheka-korrektsii
 */
export interface KktGetCorrectionReceiptRequest {
	/** Идентификатор чека */
	Id: string;
}

export const KKT_GET_CORRECTION_RECEIPT_URL = "/kkt/correction-receipt/get" as const;

/**
 * Изменение состояния кассы
 * Метод ручного управления состоянием кассы. Касса может быть принудительно выключена (отправлена на техобслуживание) и включена (введена в эксплуатацию).
 * @see https://developers.cloudkassir.ru/#izmenenie-sostoyaniya-kassy
 */
export interface KktUpdateCashRegisterStateRequest {
	/** ИНН организации или индивидуального предпринимателя — пользователя кассы */
	Inn: string;
	/** Заводской номер кассы */
	DeviceNumber: string;
	/** Номер фискального накопителя */
	FiscalNumber: string;
	/** Флаг, указывающий, нужно ли помещать кассу на техобслуживание */
	OnMaintenance: boolean;
}

export const KKT_UPDATE_CASH_REGISTER_STATE_URL = "/kkt/state" as const;

/**
 * Получение данных кассы
 * Метод получения данных кассы.
 * @see https://developers.cloudkassir.ru/#poluchenie-dannyh-kassy
 */
export interface KktGetCashRegisterStateRequest {
	/** Заводской номер кассы */
	DeviceNumber: string;
	/** Номер фискального накопителя */
	FiscalNumber: string;
}

export const KKT_GET_CASH_REGISTER_STATE_URL = "/kkt/state/get" as const;

/**
 * Предупреждения по кассам
 * Метод получения предупреждений по всем кассам мерчанта.
 * @see https://developers.cloudkassir.ru/#preduprezhdeniya-po-kassam
 */
export type KktListCashRegisterWarningsRequest = Record<string, never>;

export const KKT_LIST_CASH_REGISTER_WARNINGS_URL = "/kkt/merchant-devices-warnings" as const;

/** Реестр всех API-эндпоинтов, сгенерирован из IR. */
export const ENDPOINTS = {
	escrow: {
		getInfo: { url: "/Escrow/GetEscrowInfo", method: "POST" as const },
	},
	payments: {
		test: { url: "/test", method: "POST" as const },
		chargeCryptogram: { url: "/payments/cards/charge", method: "POST" as const },
		authCryptogram: { url: "/payments/cards/auth", method: "POST" as const },
		post3ds: { url: "/payments/cards/post3ds", method: "POST" as const },
		chargeToken: { url: "/payments/tokens/charge", method: "POST" as const },
		authToken: { url: "/payments/tokens/auth", method: "POST" as const },
		confirm: { url: "/payments/confirm", method: "POST" as const },
		void: { url: "/payments/void", method: "POST" as const },
		refund: { url: "/payments/refund", method: "POST" as const },
		payoutCryptogram: { url: "/payments/cards/topup", method: "POST" as const },
		payoutToken: { url: "/payments/token/topup", method: "POST" as const },
		payoutSbp: { url: "/payments/alt/topup", method: "POST" as const },
		get: { url: "/payments/get", method: "POST" as const },
		findLegacy: { url: "/payments/find", method: "POST" as const },
		find: { url: "/v2/payments/find", method: "POST" as const },
		listByDay: { url: "/payments/list", method: "POST" as const },
		listByPeriod: { url: "/v2/payments/list", method: "POST" as const },
		listClaimsByPeriod: { url: "/chargebacks/list", method: "POST" as const },
		listTokens: { url: "/payments/tokens/list", method: "POST" as const },
	},
	subscriptions: {
		create: { url: "/subscriptions/create", method: "POST" as const },
		get: { url: "/subscriptions/get", method: "POST" as const },
		findByAccount: { url: "/subscriptions/find", method: "POST" as const },
		update: { url: "/subscriptions/update", method: "POST" as const },
		cancel: { url: "/subscriptions/cancel", method: "POST" as const },
	},
	orders: {
		create: { url: "/orders/create", method: "POST" as const },
		cancel: { url: "/orders/cancel", method: "POST" as const },
	},
	settings: {
		getNotification: { url: "/site/notifications/{Type}/get", method: "POST" as const },
		updateNotification: { url: "/site/notifications/{Type}/update", method: "POST" as const },
	},
	tPay: {
		createLink: { url: "/payments/qr/tinkoffpay/link", method: "POST" as const },
		createQrImage: { url: "/payments/qr/tinkoffpay/image", method: "POST" as const },
	},
	sbp: {
		createLink: { url: "/payments/qr/sbp/link", method: "POST" as const },
		createQrImage: { url: "/payments/qr/sbp/image", method: "POST" as const },
		listBanks: { url: "/sbp/v2/banks/info", method: "POST" as const },
	},
	sberPay: {
		createLink: { url: "/payments/qr/sberpay/link", method: "POST" as const },
		createQrImage: { url: "/payments/qr/sberpay/image", method: "POST" as const },
	},
	kkt: {
		fiscalize: { url: "/kkt/fiscalize", method: "POST" as const },
		submitReceipt: { url: "/kkt/receipt", method: "POST" as const },
		getReceiptStatus: { url: "/kkt/receipt/status/get", method: "POST" as const },
		getReceipt: { url: "/kkt/receipt/get", method: "POST" as const },
		validateMarkCode: { url: "/kkt/validate-mark-code", method: "POST" as const },
		validateMarkCodes: { url: "/kkt/validate-mark-codes", method: "POST" as const },
		submitCorrectionReceipt: { url: "/kkt/correction-receipt", method: "POST" as const },
		getCorrectionReceiptStatus: { url: "/kkt/correction-receipt/status/get", method: "POST" as const },
		getCorrectionReceipt: { url: "/kkt/correction-receipt/get", method: "POST" as const },
		updateCashRegisterState: { url: "/kkt/state", method: "POST" as const },
		getCashRegisterState: { url: "/kkt/state/get", method: "POST" as const },
		listCashRegisterWarnings: { url: "/kkt/merchant-devices-warnings", method: "POST" as const },
	},
} as const;
