/**
 * AUTO-GENERATED by tools/gen.ts from specs/ir.json.
 * Do not edit directly — run `bun run gen` instead.
 */

import type { Currency, CultureName } from "./handbooks.js";
import type { Payer, Receipt, CloudPaymentsMeta } from "./shared.js";

/**
 * Тестовый метод
 * Для проверки взаимодействия с API можно вызвать тестовый метод.
 * @see https://developers.cloudpayments.ru/#testovyy-metod
 */
export type PaymentsTestRequest = Record<string, never>;

export const PAYMENTS_TEST_URL = "https://api.cloudpayments.ru/test" as const;

/**
 * Оплата по криптограмме
 * Метод для оплаты по криптограмме платежных данных результат алгоритма шифрования. Для формирования криптограммы воспользуйтесь скриптом [Checkout](#skript-checkout).
 * @see https://developers.cloudpayments.ru/#oplata-po-kriptogramme
 */
export interface PaymentsChargeCryptogramRequest {
	/** Cумма платежа в валюте, разделитель точка. Количество не нулевых знаков после точки – 2 */
	Amount: number;
	/** Валюта: RUB/USD/EUR/GBP ([см. справочник](#spisok-valyut)). Если параметр не передан, то по умолчанию принимает значение RUB */
	Currency?: Currency;
	/** IP-адрес плательщика */
	IpAddress: string;
	/** [Криптограмма платежных данных](#skript-checkout) */
	CardCryptogramPacket: string;
	/** Имя держателя карты латиницей */
	Name?: string;
	/** Адрес сайта, с которого совершается вызов скрипта checkout */
	PaymentUrl?: string;
	/** Номер счета или заказа */
	InvoiceId?: string;
	/** Описание оплаты в свободной форме */
	Description?: string;
	/** Язык уведомлений. Возможные значения: "ru-RU", "en-US". ([см. справочник](#lokalizatsiya)) */
	CultureName?: CultureName;
	/** Обязательный идентификатор пользователя для создания подписки и получения токена */
	AccountId?: string;
	/** E-mail плательщика, на который будет отправлена квитанция об оплате */
	Email?: string;
	/** Доп. поле, куда передается информация о плательщике. Используйте следующие параметры: `FirstName`, `LastName`, `MiddleName`, `Birth`, `Street`, `Address`, `City`, `Country`, `Phone`, `Postcode` */
	Payer?: Payer;
	/** Любые другие данные, которые будут связаны с транзакцией, в том числе инструкции для [создания подписки](#rekurrentnye-platezhi-podpiska) или формирования [онлайн-чека](#format-peredachi-dannyh-dlya-onlayn-cheka) должны обёртываться в объект `cloudpayments`. Мы зарезервировали названия следующих параметров и отображаем их содержимое в реестре операций, выгружаемом в Личном Кабинете: `name`, `firstName`, `middleName`, `lastName`, `nick`, `phone`, `address`, `comment`, `birthDate`. */
	JsonData?: Record<string, unknown>;
	/** Признак сохранения карточного токена для проведения оплаты по сохранённой карте (см. [Оплата по токену (рекарринг)](#oplata-po-tokenu-rekarring)). Возможные значения: `true` - после успешной оплаты будет возвращён карточный токен, `false` - токен не будет возвращаться (по-умолчанию) Параметр SaveCard обрабатывается только при включении настройки "Сохранение токена карты" в Личном Кабинете. При включении настройки "Сохранять принудительно", параметр SaveCard будет игнорироваться. */
	SaveCard?: boolean;
}

export const PAYMENTS_CHARGE_CRYPTOGRAM_URL = "https://api.cloudpayments.ru/payments/cards/charge" as const;

/**
 * Оплата по криптограмме
 * Метод для оплаты по криптограмме платежных данных результат алгоритма шифрования. Для формирования криптограммы воспользуйтесь скриптом [Checkout](#skript-checkout).
 * @see https://developers.cloudpayments.ru/#oplata-po-kriptogramme
 */
export interface PaymentsAuthCryptogramRequest {
	/** Cумма платежа в валюте, разделитель точка. Количество не нулевых знаков после точки – 2 */
	Amount: number;
	/** Валюта: RUB/USD/EUR/GBP ([см. справочник](#spisok-valyut)). Если параметр не передан, то по умолчанию принимает значение RUB */
	Currency?: Currency;
	/** IP-адрес плательщика */
	IpAddress: string;
	/** [Криптограмма платежных данных](#skript-checkout) */
	CardCryptogramPacket: string;
	/** Имя держателя карты латиницей */
	Name?: string;
	/** Адрес сайта, с которого совершается вызов скрипта checkout */
	PaymentUrl?: string;
	/** Номер счета или заказа */
	InvoiceId?: string;
	/** Описание оплаты в свободной форме */
	Description?: string;
	/** Язык уведомлений. Возможные значения: "ru-RU", "en-US". ([см. справочник](#lokalizatsiya)) */
	CultureName?: CultureName;
	/** Обязательный идентификатор пользователя для создания подписки и получения токена */
	AccountId?: string;
	/** E-mail плательщика, на который будет отправлена квитанция об оплате */
	Email?: string;
	/** Доп. поле, куда передается информация о плательщике. Используйте следующие параметры: `FirstName`, `LastName`, `MiddleName`, `Birth`, `Street`, `Address`, `City`, `Country`, `Phone`, `Postcode` */
	Payer?: Payer;
	/** Любые другие данные, которые будут связаны с транзакцией, в том числе инструкции для [создания подписки](#rekurrentnye-platezhi-podpiska) или формирования [онлайн-чека](#format-peredachi-dannyh-dlya-onlayn-cheka) должны обёртываться в объект `cloudpayments`. Мы зарезервировали названия следующих параметров и отображаем их содержимое в реестре операций, выгружаемом в Личном Кабинете: `name`, `firstName`, `middleName`, `lastName`, `nick`, `phone`, `address`, `comment`, `birthDate`. */
	JsonData?: Record<string, unknown>;
	/** Признак сохранения карточного токена для проведения оплаты по сохранённой карте (см. [Оплата по токену (рекарринг)](#oplata-po-tokenu-rekarring)). Возможные значения: `true` - после успешной оплаты будет возвращён карточный токен, `false` - токен не будет возвращаться (по-умолчанию) Параметр SaveCard обрабатывается только при включении настройки "Сохранение токена карты" в Личном Кабинете. При включении настройки "Сохранять принудительно", параметр SaveCard будет игнорироваться. */
	SaveCard?: boolean;
}

export const PAYMENTS_AUTH_CRYPTOGRAM_URL = "https://api.cloudpayments.ru/payments/cards/auth" as const;

/**
 * Пример формы:
 * @see https://developers.cloudpayments.ru/#primer-formy
 */
export interface PaymentsPost3dsRequest {
	/** Значение параметра MD */
	TransactionId: number;
	/** Значение одноименного параметра */
	PaRes: string;
}

export const PAYMENTS_POST3DS_URL = "https://api.cloudpayments.ru/payments/cards/post3ds" as const;

/**
 * Оплата по токену (рекарринг)
 * Метод для оплаты по токену, полученному при [оплате по криптограмме](#oplata-po-kriptogramme), либо через [Pay](#pay)-уведомление.
 * @see https://developers.cloudpayments.ru/#oplata-po-tokenu-rekarring
 */
export interface PaymentsChargeTokenRequest {
	/** Cумма платежа в валюте, разделитель точка. Количество не нулевых знаков после точки – 2 */
	Amount: number;
	/** Валюта: RUB/USD/EUR/GBP (см. [справочник](#spisok-valyut)). Если параметр не передан, то по умолчанию принимает значение RUB */
	Currency?: Currency;
	/** Идентификатор пользователя */
	AccountId: string;
	/** Признак инициатора списания денежных средств. Возможные значения: 0 - транзакция инициирована ТСП на основе ранее сохраненных учетных данных; 1 - транзакция инициирована держателем карты (клиентом) на основе ранее сохраненных учетных данных. **ВАЖНО!** В случае, если транзакция инициирована ТСП, необходимо дополнительно в запросе указать параметр PaymentScheduled с корректным значением. */
	TrInitiatorCode: number;
	/** Признак оплаты по расписанию на основе ранее сохраненных учетных данных. Возможные значения: 0 - без расписания; 1 - по расписанию. **ВАЖНО!** В случае, если при запросе данный параметр не указан, по умолчанию будет использоваться значение 0. */
	PaymentScheduled?: number;
	/** Токен */
	Token: string;
	/** Номер счета или заказа */
	InvoiceId?: string;
	/** Назначение платежа в свободной форме */
	Description?: string;
	/** IP-адрес плательщика */
	IpAddress?: string;
	/** E-mail плательщика, на который будет отправлена квитанция об оплате */
	Email?: string;
	/** Доп. поле, куда передается информация о плательщике. Используйте следующие параметры: `FirstName`, `LastName`, `MiddleName`, `Birth`, `Street`, `Address`, `City`, `Country`, `Phone`, `Postcode` */
	Payer?: Payer;
	/** Любые другие данные, которые будут связаны с транзакцией, в том числе инструкции для [создания подписки](#rekurrentnye-platezhi-podpiska) или формирования [онлайн-чека](#format-peredachi-dannyh-dlya-onlayn-cheka) должны обёртываться в объект `cloudpayments`. Мы зарезервировали названия следующих параметров и отображаем их содержимое в реестре операций, выгружаемом в Личном Кабинете: `name`, `firstName`, `middleName`, `lastName`, `nick`, `phone`, `address`, `comment`, `birthDate`. */
	JsonData?: Record<string, unknown>;
}

export const PAYMENTS_CHARGE_TOKEN_URL = "https://api.cloudpayments.ru/payments/tokens/charge" as const;

/**
 * Оплата по токену (рекарринг)
 * Метод для оплаты по токену, полученному при [оплате по криптограмме](#oplata-po-kriptogramme), либо через [Pay](#pay)-уведомление.
 * @see https://developers.cloudpayments.ru/#oplata-po-tokenu-rekarring
 */
export interface PaymentsAuthTokenRequest {
	/** Cумма платежа в валюте, разделитель точка. Количество не нулевых знаков после точки – 2 */
	Amount: number;
	/** Валюта: RUB/USD/EUR/GBP (см. [справочник](#spisok-valyut)). Если параметр не передан, то по умолчанию принимает значение RUB */
	Currency?: Currency;
	/** Идентификатор пользователя */
	AccountId: string;
	/** Признак инициатора списания денежных средств. Возможные значения: 0 - транзакция инициирована ТСП на основе ранее сохраненных учетных данных; 1 - транзакция инициирована держателем карты (клиентом) на основе ранее сохраненных учетных данных. **ВАЖНО!** В случае, если транзакция инициирована ТСП, необходимо дополнительно в запросе указать параметр PaymentScheduled с корректным значением. */
	TrInitiatorCode: number;
	/** Признак оплаты по расписанию на основе ранее сохраненных учетных данных. Возможные значения: 0 - без расписания; 1 - по расписанию. **ВАЖНО!** В случае, если при запросе данный параметр не указан, по умолчанию будет использоваться значение 0. */
	PaymentScheduled?: number;
	/** Токен */
	Token: string;
	/** Номер счета или заказа */
	InvoiceId?: string;
	/** Назначение платежа в свободной форме */
	Description?: string;
	/** IP-адрес плательщика */
	IpAddress?: string;
	/** E-mail плательщика, на который будет отправлена квитанция об оплате */
	Email?: string;
	/** Доп. поле, куда передается информация о плательщике. Используйте следующие параметры: `FirstName`, `LastName`, `MiddleName`, `Birth`, `Street`, `Address`, `City`, `Country`, `Phone`, `Postcode` */
	Payer?: Payer;
	/** Любые другие данные, которые будут связаны с транзакцией, в том числе инструкции для [создания подписки](#rekurrentnye-platezhi-podpiska) или формирования [онлайн-чека](#format-peredachi-dannyh-dlya-onlayn-cheka) должны обёртываться в объект `cloudpayments`. Мы зарезервировали названия следующих параметров и отображаем их содержимое в реестре операций, выгружаемом в Личном Кабинете: `name`, `firstName`, `middleName`, `lastName`, `nick`, `phone`, `address`, `comment`, `birthDate`. */
	JsonData?: Record<string, unknown>;
}

export const PAYMENTS_AUTH_TOKEN_URL = "https://api.cloudpayments.ru/payments/tokens/auth" as const;

/**
 * Подтверждение оплаты
 * Для платежей, проведенных по [двухстадийной схеме](#shemy-provedeniya-platezha), необходимо подтверждение оплаты, которое можно выполнить через личный кабинет, либо через вызов метода API.
 * @see https://developers.cloudpayments.ru/#podtverzhdenie-oplaty
 */
export interface PaymentsConfirmRequest {
	/** Номер транзакции в системе */
	TransactionId: number;
	/** Сумма подтверждения в валюте транзакции, разделитель точка. Количество не нулевых знаков после точки – 2. */
	Amount: number;
	/** Любые другие данные, которые будут связаны с транзакцией, в том числе инструкции для формирования [онлайн-чека](#format-peredachi-dannyh-dlya-onlayn-cheka) */
	JsonData?: Record<string, unknown>;
}

export const PAYMENTS_CONFIRM_URL = "https://api.cloudpayments.ru/payments/confirm" as const;

/**
 * Отмена оплаты
 * Отмену оплаты можно выполнить через личный кабинет либо через вызов метода API.
 * @see https://developers.cloudpayments.ru/#otmena-oplaty
 */
export interface PaymentsVoidRequest {
	/** Номер транзакции в системе */
	TransactionId: number;
}

export const PAYMENTS_VOID_URL = "https://api.cloudpayments.ru/payments/void" as const;

/**
 * Возврат денег
 * Возврат денег можно выполнить через личный кабинет или через вызов метода API.
 * @see https://developers.cloudpayments.ru/#vozvrat-deneg
 */
export interface PaymentsRefundRequest {
	/** Номер транзакции оплаты */
	TransactionId: number;
	/** Сумма возврата в валюте транзакции, разделитель точка. Количество не нулевых знаков после точки – 2. */
	Amount: number;
	/** Любые другие данные, которые будут связаны с транзакцией, в том числе инструкции для формирования [онлайн-чека](#format-peredachi-dannyh-dlya-onlayn-cheka) */
	JsonData?: Record<string, unknown>;
}

export const PAYMENTS_REFUND_URL = "https://api.cloudpayments.ru/payments/refund" as const;

/**
 * Выплата по криптограмме
 * Выплату по криптограмме можно осуществить через вызов метода API.
 * @see https://developers.cloudpayments.ru/#vyplata-po-kriptogramme
 */
export interface PaymentsPayoutCryptogramRequest {
	/** Криптограмма платежных данных */
	CardCryptogramPacket: string;
	/** Cумма платежа в валюте, разделитель точка. Количество не нулевых знаков после точки – 2 */
	Amount: number;
	/** Валюта: RUB */
	Currency: Currency;
	/** Имя держателя карты латиницей */
	Name?: string;
	/** Идентификатор пользователя */
	AccountId?: string;
	/** E-mail плательщика, на который будет отправлена квитанция об оплате */
	Email?: string;
	/** Любые другие данные, которые будут связаны с транзакцией. Мы зарезервировали названия следующих параметров и отображаем их содержимое в реестре операций, выгружаемом в Личном Кабинете: `name`, `firstName`, `middleName`, `lastName`, `nick`, `phone`, `address`, `comment`, `birthDate`. */
	JsonData?: Record<string, unknown>;
	/** Номер заказа в вашей системе */
	InvoiceId?: string;
	/** Описание оплаты в свободной форме */
	Description?: string;
	/** Доп. поле, куда передается информация о плательщике */
	Payer?: Payer;
	/** Доп. поле, куда передается информация о получателе */
	Receiver?: Record<string, unknown>;
}

export const PAYMENTS_PAYOUT_CRYPTOGRAM_URL = "https://api.cloudpayments.ru/payments/cards/topup" as const;

/**
 * Выплата по токену
 * Выплату по токену можно осуществить через вызов метода API.
 * @see https://developers.cloudpayments.ru/#vyplata-po-tokenu
 */
export interface PaymentsPayoutTokenRequest {
	/** Токен карты, выданный системой после первого платежа */
	Token: string;
	/** Cумма платежа в валюте, разделитель точка. Количество не нулевых знаков после точки – 2 */
	Amount: number;
	/** Идентификатор пользователя */
	AccountId: string;
	/** Валюта: RUB */
	Currency: Currency;
	/** Номер заказа в вашей системе */
	InvoiceId?: string;
	/** Доп. поле, куда передается информация о плательщике */
	Payer?: Payer;
	/** Доп. поле, куда передается информация о получателе */
	Receiver?: Record<string, unknown>;
}

export const PAYMENTS_PAYOUT_TOKEN_URL = "https://api.cloudpayments.ru/payments/token/topup" as const;

/**
 * Выплата по СБП
 * Выплату по СБП можно осуществить через вызов метода API.
 * @see https://developers.cloudpayments.ru/#vyplata-po-sbp
 */
export interface PaymentsPayoutSbpRequest {
	/** Идентификатор банка получателя НПСК для СБП Если в запросе поле `Receiver.Phone` заполнено, то `MemberId` обязательное Допустимые значения для `MemberId` можно найти по [ссылке](https://qr.nspk.ru/proxyapp/c2bmembers.json). Значение из поля `schema` в поле `MemberId` надо передать только цифровое значение из поля `schema` Например, для `schema:bank100000000111` передать `MemberId:100000000111` */
	MemberId?: string;
	/** Cумма платежа в валюте, разделитель точка. Количество не нулевых знаков после точки – 2 */
	Amount: number;
	/** Валюта: RUB */
	Currency: Currency;
	/** Идентификатор пользователя */
	AccountId?: string;
	/** E-mail плательщика, на который будет отправлена квитанция об оплате */
	Email?: string;
	/** Язык уведомлений. Возможные значения: "ru-RU", "en-US". ([см. справочник](#lokalizatsiya)) */
	CultureName?: CultureName;
	/** Номер заказа в вашей системе */
	InvoiceId?: string;
	/** Описание оплаты в свободной форме */
	Description?: string;
	/** Доп. поле, куда передается информация о плательщике. Используйте следующие параметры: `FirstName`, `LastName`, `MiddleName`, `Birth`, `Street`, `Address`, `City`, `Country`, `Phone`, `Postcode` */
	Payer?: Payer;
	/** Доп. поле, куда передается информация о получателе */
	Receiver: Record<string, unknown>;
	/** Для выплаты по СБП необходимо указать номер получателя средств */
	"Receiver.Phone": string;
}

export const PAYMENTS_PAYOUT_SBP_URL = "https://api.cloudpayments.ru/payments/alt/topup" as const;

/**
 * Просмотр транзакции
 * Метод получения детализации по транзакции.
 * @see https://developers.cloudpayments.ru/#prosmotr-tranzaktsii
 */
export interface PaymentsGetRequest {
	/** Номер транзакции */
	TransactionId: number;
}

export const PAYMENTS_GET_URL = "https://api.cloudpayments.ru/payments/get" as const;

/**
 * Выгрузка списка транзакций
 * Метод выгрузки списка транзакций за день.
 * @see https://developers.cloudpayments.ru/#vygruzka-spiska-tranzaktsiy
 */
export interface PaymentsListByDayRequest {
	/** Дата создания операций */
	Date: string;
	/** Код временной зоны, по умолчанию — UTC */
	TimeZone?: string;
}

export const PAYMENTS_LIST_BY_DAY_URL = "https://api.cloudpayments.ru/payments/list" as const;

/**
 * Выгрузка списка транзакций за произвольный период
 * Метод выгрузки списка транзакций за произвольный период.
 * @see https://developers.cloudpayments.ru/#vygruzka-spiska-tranzaktsiy-za-proizvolnyy-period
 */
export interface PaymentsListByPeriodRequest {
	/** Начальная дата создания операций */
	CreatedDateGte: string;
	/** Конечная дата создания операций */
	CreatedDateLte: string;
	/** порядковый номер страницы, должно быть больше или равно 1 */
	PageNumber: number;
	/** Код временной зоны, по умолчанию — UTC */
	TimeZone?: string;
	/** Статус операция. Может иметь значения [ "Authorized", "Completed", "Cancelled", "Declined" ]. По умолчанию выбраны все */
	Statuses?: string;
}

export const PAYMENTS_LIST_BY_PERIOD_URL = "https://api.cloudpayments.ru/v2/payments/list" as const;

/**
 * Выгрузка списка претензий за произвольный период
 * Метод выгрузки списка претензий за произвольный период, но не более чем за 1 год. Для выгрузки требуется отправить http-запрос с типом авторизации “Basic Auth”. Логин - public key (pk) терминала.
 * @see https://developers.cloudpayments.ru/#vygruzka-spiska-pretenziy-za-proizvolnyy-period
 */
export interface PaymentsListClaimsByPeriodRequest {
	/** Начальная дата создания претензии */
	CreatedDateGte: string;
	/** Конечная дата создания претензии */
	CreatedDateLte: string;
	/** Порядковый номер страницы, должно быть больше или равно 1 */
	PageNumber: number;
}

export const PAYMENTS_LIST_CLAIMS_BY_PERIOD_URL = "https://api.cloudpayments.ru/chargebacks/list" as const;

/**
 * Выгрузка токенов
 * Метод выгрузки списка всех платежных токенов CloudPayments.
 * @see https://developers.cloudpayments.ru/#vygruzka-tokenov
 */
export interface PaymentsListTokensRequest {
	/** Порядковый номер страницы, должно быть больше или равно 1 */
	PageNumber: number;
}

export const PAYMENTS_LIST_TOKENS_URL = "https://api.cloudpayments.ru/payments/tokens/list" as const;

/**
 * Создание подписки на рекуррентные платежи
 * Метод создания подписки на рекуррентные платежи.
 * @see https://developers.cloudpayments.ru/#sozdanie-podpiski-na-rekurrentnye-platezhi
 */
export interface SubscriptionsCreateRequest {
	/** Токен карты, выданный системой после первого платежа */
	Token: string;
	/** Идентификатор пользователя */
	AccountId: string;
	/** Назначение платежа в свободной форме */
	Description: string;
	/** E-mail плательщика */
	Email?: string;
	/** Cумма платежа в валюте, разделитель точка. Количество не нулевых знаков после точки – 2 */
	Amount: number;
	/** Валюта: RUB/USD/EUR/GBP (см. [справочник](#spisok-valyut)) */
	Currency: Currency;
	/** Если значение true — платежи будут выполняться по двухстадийной схеме */
	RequireConfirmation: boolean;
	/** Дата и время первого платежа по плану во временной зоне UTC. Значение должно быть в будущем */
	StartDate: string;
	/** Интервал. Возможные значения: Day, Week, Month */
	Interval: string;
	/** Период. В комбинации с интервалом, 1 Month значит раз в месяц, а 2 Week — раз в две недели. Должен быть больше 0 */
	Period: number;
	/** Максимальное количество платежей в подписке. Если указан, должен быть больше 0 */
	MaxPeriods?: number;
	/** Для изменения состава [онлайн-чека](#format-peredachi-dannyh-dlya-onlayn-cheka) */
	CustomerReceipt?: Record<string, unknown>;
}

export const SUBSCRIPTIONS_CREATE_URL = "https://api.cloudpayments.ru/subscriptions/create" as const;

/**
 * Запрос информации о подписке
 * Метод получения информации о статусе подписки.
 * @see https://developers.cloudpayments.ru/#zapros-informatsii-o-podpiske
 */
export interface SubscriptionsGetRequest {
	/** Идентификатор подписки */
	Id: string;
}

export const SUBSCRIPTIONS_GET_URL = "https://api.cloudpayments.ru/subscriptions/get" as const;

/**
 * Поиск подписок
 * Метод получения списка подписок для определенного аккаунта.
 * @see https://developers.cloudpayments.ru/#poisk-podpisok
 */
export interface SubscriptionsFindByAccountRequest {
	/** Идентификатор пользователя */
	accountId: string;
}

export const SUBSCRIPTIONS_FIND_BY_ACCOUNT_URL = "https://api.cloudpayments.ru/subscriptions/find" as const;

/**
 * Изменение подписки на рекуррентные платежи
 * Метод изменения ранее созданной подписки.
 * @see https://developers.cloudpayments.ru/#izmenenie-podpiski-na-rekurrentnye-platezhi
 */
export interface SubscriptionsUpdateRequest {
	/** Идентификатор подписки */
	Id: string;
	/** Для изменения назначения платежа */
	Description?: string;
	/** Для изменения суммы платежа в валюте, разделитель точка. Количество не нулевых знаков после точки – 2. */
	Amount?: number;
	/** Для изменения валюты: RUB/USD/EUR/GBP ([см. справочник](#spisok-valyut)) */
	Currency?: Currency;
	/** Для изменения схемы проведения платежей */
	RequireConfirmation?: boolean;
	/** Для изменения даты и времени первого или следующего платежа во временной зоне UTC */
	StartDate?: string;
	/** Для изменения интервала. Возможные значения: Day, Week, Month */
	Interval?: string;
	/** Для изменения периода. В комбинации с интервалом, 1 Month значит раз в месяц, а 2 Week — раз в две недели */
	Period?: number;
	/** Для изменения максимального количества платежей в подписке */
	MaxPeriods?: number;
	/** Для изменения состава [онлайн-чека](#format-peredachi-dannyh-dlya-onlayn-cheka) */
	CustomerReceipt?: Record<string, unknown>;
	/** Язык уведомлений. Возможные значения: "ru-RU", "en-US". ([см. справочник](#lokalizatsiya)) */
	CultureName?: CultureName;
}

export const SUBSCRIPTIONS_UPDATE_URL = "https://api.cloudpayments.ru/subscriptions/update" as const;

/**
 * Отмена подписки на рекуррентные платежи
 * Метод отмены подписки на рекуррентные платежи.
 * @see https://developers.cloudpayments.ru/#otmena-podpiski-na-rekurrentnye-platezhi
 */
export interface SubscriptionsCancelRequest {
	/** Идентификатор подписки */
	Id: string;
}

export const SUBSCRIPTIONS_CANCEL_URL = "https://api.cloudpayments.ru/subscriptions/cancel" as const;

/**
 * Создание счета для отправки по почте
 * Метод формирования ссылки на оплату и последующей отправки уведомления на e-mail адрес плательщика.
 * @see https://developers.cloudpayments.ru/#sozdanie-scheta-dlya-otpravki-po-pochte
 */
export interface OrdersCreateRequest {
	/** Cумма платежа в валюте, разделитель точка. Количество не нулевых знаков после точки – 2 */
	Amount: number;
	/** Валюта RUB/USD/EUR/GBP ([см. справочник](#spisok-valyut)). Если параметр не передан, то по умолчанию принимает значение RUB */
	Currency?: Currency;
	/** Назначение платежа в свободной форме */
	Description: string;
	/** E-mail плательщика */
	Email?: string;
	/** Есть значение true — платеж будет выполнен по двухстадийной схеме */
	RequireConfirmation?: boolean;
	/** Если значение true — плательщик получит письмо со ссылкой на оплату */
	SendEmail?: boolean;
	/** Номер заказа в вашей системе */
	InvoiceId?: string;
	/** Идентификатор пользователя в вашей системе */
	AccountId?: string;
	/** Ссылка на оферту, которая будет показываться на странице заказа */
	OfferUri?: string;
	/** Номер телефона плательщика в произвольном формате */
	Phone?: string;
	/** Если значение true — плательщик получит СМС со ссылкой на оплату */
	SendSms?: boolean;
	/** Если значение true — плательщик получит сообщение в Viber со ссылкой на оплату */
	SendViber?: boolean;
	/** Язык уведомлений. Возможные значения: "ru-RU", "en-US". ([см. справочник](#lokalizatsiya)) */
	CultureName?: CultureName;
	/** Для создания платежа с подпиской. Возможные значения: CreateWeekly, CreateMonthly */
	SubscriptionBehavior?: string;
	/** Адрес страницы для редиректа при успешной оплате */
	SuccessRedirectUrl?: string;
	/** Адрес страницы для редиректа при неуспешной оплате */
	FailRedirectUrl?: string;
	/** Любые другие данные, которые будут связаны с транзакцией, в том числе инструкции для формирования [онлайн-чека](#format-peredachi-dannyh-dlya-onlayn-cheka) должны обёртываться в объект `cloudpayments` */
	JsonData?: Record<string, unknown>;
}

export const ORDERS_CREATE_URL = "https://api.cloudpayments.ru/orders/create" as const;

/**
 * Отмена созданного счета
 * Метод отмены созданного счета:
 * @see https://developers.cloudpayments.ru/#otmena-sozdannogo-scheta
 */
export interface OrdersCancelRequest {
	/** Идентификатор счета */
	Id: string;
}

export const ORDERS_CANCEL_URL = "https://api.cloudpayments.ru/orders/cancel" as const;

/**
 * Просмотр настроек уведомлений
 * Метод просмотра настроек уведомлений с указанием типа уведомления.
 * @see https://developers.cloudpayments.ru/#prosmotr-nastroek-uvedomleniy
 */
export interface SettingsGetNotificationRequest {
	/** Тип уведомления: Check/Pay/Fail и т.д. (см. [справочник](#tipy-operatsiy)) */
	Type: string;
}

export const SETTINGS_GET_NOTIFICATION_URL = "https://api.cloudpayments.ru/site/notifications/{Type}/get" as const;

/**
 * Изменение настроек уведомлений
 * Метод изменения настроек уведомлений.
 * @see https://developers.cloudpayments.ru/#izmenenie-nastroek-uvedomleniy
 */
export interface SettingsUpdateNotificationRequest {
	/** Тип уведомления: Pay/Fail и т.д., кроме Check-уведомления (см. [справочник](#tipy-operatsiy)) */
	Type: string;
	/** Если значение true — то уведомление включено. Значение по умолчанию — false */
	IsEnabled?: boolean;
	/** Адрес для отправки уведомлений (для HTTPS-схемы необходим валидный SSL-сертификат) */
	Address?: string;
	/** HTTP-метод для отправки уведомлений. Возможные значения: GET, POST. Значение по умолчанию — GET */
	HttpMethod?: string;
	/** Кодировка уведомлений. Возможные значения: UTF8, Windows1251. Значение по умолчанию — UTF8 */
	Encoding?: string;
	/** Формат уведомлений. Возможные значения: CloudPayments, QIWI, RT. Значение по умолчанию — CloudPayments */
	Format?: string;
}

export const SETTINGS_UPDATE_NOTIFICATION_URL = "https://api.cloudpayments.ru/site/notifications/{Type}/update" as const;

/** Реестр всех API-эндпоинтов, сгенерирован из IR. */
export const ENDPOINTS = {
	payments: {
		test: { url: "https://api.cloudpayments.ru/test", method: "POST" as const },
		chargeCryptogram: { url: "https://api.cloudpayments.ru/payments/cards/charge", method: "POST" as const },
		authCryptogram: { url: "https://api.cloudpayments.ru/payments/cards/auth", method: "POST" as const },
		post3ds: { url: "https://api.cloudpayments.ru/payments/cards/post3ds", method: "POST" as const },
		chargeToken: { url: "https://api.cloudpayments.ru/payments/tokens/charge", method: "POST" as const },
		authToken: { url: "https://api.cloudpayments.ru/payments/tokens/auth", method: "POST" as const },
		confirm: { url: "https://api.cloudpayments.ru/payments/confirm", method: "POST" as const },
		void: { url: "https://api.cloudpayments.ru/payments/void", method: "POST" as const },
		refund: { url: "https://api.cloudpayments.ru/payments/refund", method: "POST" as const },
		payoutCryptogram: { url: "https://api.cloudpayments.ru/payments/cards/topup", method: "POST" as const },
		payoutToken: { url: "https://api.cloudpayments.ru/payments/token/topup", method: "POST" as const },
		payoutSbp: { url: "https://api.cloudpayments.ru/payments/alt/topup", method: "POST" as const },
		get: { url: "https://api.cloudpayments.ru/payments/get", method: "POST" as const },
		listByDay: { url: "https://api.cloudpayments.ru/payments/list", method: "POST" as const },
		listByPeriod: { url: "https://api.cloudpayments.ru/v2/payments/list", method: "POST" as const },
		listClaimsByPeriod: { url: "https://api.cloudpayments.ru/chargebacks/list", method: "POST" as const },
		listTokens: { url: "https://api.cloudpayments.ru/payments/tokens/list", method: "POST" as const },
	},
	subscriptions: {
		create: { url: "https://api.cloudpayments.ru/subscriptions/create", method: "POST" as const },
		get: { url: "https://api.cloudpayments.ru/subscriptions/get", method: "POST" as const },
		findByAccount: { url: "https://api.cloudpayments.ru/subscriptions/find", method: "POST" as const },
		update: { url: "https://api.cloudpayments.ru/subscriptions/update", method: "POST" as const },
		cancel: { url: "https://api.cloudpayments.ru/subscriptions/cancel", method: "POST" as const },
	},
	orders: {
		create: { url: "https://api.cloudpayments.ru/orders/create", method: "POST" as const },
		cancel: { url: "https://api.cloudpayments.ru/orders/cancel", method: "POST" as const },
	},
	settings: {
		getNotification: { url: "https://api.cloudpayments.ru/site/notifications/{Type}/get", method: "POST" as const },
		updateNotification: { url: "https://api.cloudpayments.ru/site/notifications/{Type}/update", method: "POST" as const },
	},
} as const;
