/**
 * AUTO-GENERATED by tools/gen.ts from specs/ir.json.
 * Do not edit directly — run `bun run gen` instead.
 */

/**
 * Статусы операций
 * @see https://developers.cloudpayments.ru/#statusy-operatsiy
 */
export type TransactionStatus = "AwaitingAuthentication" | "Authorized" | "Completed" | "Cancelled" | "Declined";
/** Все значения TransactionStatus. */
export const TRANSACTION_STATUS_VALUES: readonly TransactionStatus[] = ["AwaitingAuthentication", "Authorized", "Completed", "Cancelled", "Declined"] as const;
/** Человекочитаемые названия TransactionStatus. */
export const transactionStatusLabels: Record<TransactionStatus, string> = {
	["AwaitingAuthentication"]: "Ожидает аутентификации",
	["Authorized"]: "Авторизована",
	["Completed"]: "Завершена",
	["Cancelled"]: "Отменена",
	["Declined"]: "Отклонена",
};
/** Полная информация по TransactionStatus (label + метаданные). */
export const transactionStatusInfo: Record<TransactionStatus, { label: string; "применение": string; "возможные действия": string; }> = {
	["AwaitingAuthentication"]: { label: "Ожидает аутентификации", "применение": "После перехода плательщика на сайт эмитента в ожидании результатов 3-D Secure", "возможные действия": "Нет" },
	["Authorized"]: { label: "Авторизована", "применение": "После получения авторизации", "возможные действия": "Подтверждение, Отмена" },
	["Completed"]: { label: "Завершена", "применение": "После подтверждения операции", "возможные действия": "Возврат денег" },
	["Cancelled"]: { label: "Отменена", "применение": "В случае отмены операции", "возможные действия": "Нет" },
	["Declined"]: { label: "Отклонена", "применение": "В случае невозможности провести операцию (нет денег на счете карты и т.п.)", "возможные действия": "Нет" },
};

/**
 * Статусы подписок (рекуррент)
 * @see https://developers.cloudpayments.ru/#statusy-podpisok-rekurrent
 */
export type SubscriptionStatus = "Active" | "PastDue" | "Cancelled" | "Rejected" | "Expired";
/** Все значения SubscriptionStatus. */
export const SUBSCRIPTION_STATUS_VALUES: readonly SubscriptionStatus[] = ["Active", "PastDue", "Cancelled", "Rejected", "Expired"] as const;
/** Человекочитаемые названия SubscriptionStatus. */
export const subscriptionStatusLabels: Record<SubscriptionStatus, string> = {
	["Active"]: "Подписка активна",
	["PastDue"]: "Просрочена",
	["Cancelled"]: "Отменена",
	["Rejected"]: "Отклонена",
	["Expired"]: "Завершена",
};
/** Полная информация по SubscriptionStatus (label + метаданные). */
export const subscriptionStatusInfo: Record<SubscriptionStatus, { label: string; "применение": string; "возможные действия": string; }> = {
	["Active"]: { label: "Подписка активна", "применение": "После создания и очередной успешной оплаты", "возможные действия": "Отмена" },
	["PastDue"]: { label: "Просрочена", "применение": "После одной или двух подряд неуспешных попыток оплаты", "возможные действия": "Отмена" },
	["Cancelled"]: { label: "Отменена", "применение": "В случае отмены по запросу", "возможные действия": "Нет" },
	["Rejected"]: { label: "Отклонена", "применение": "В случае трех неудачных попыток оплаты, идущих подряд", "возможные действия": "Нет" },
	["Expired"]: { label: "Завершена", "применение": "В случае завершения максимального количества периодов (если были указаны)", "возможные действия": "Нет" },
};

/**
 * Список валют
 * @see https://developers.cloudpayments.ru/#spisok-valyut
 */
export type Currency = "RUB" | "EUR" | "USD" | "GBP" | "UAH" | "BYR" | "BYN" | "KZT" | "AZN" | "CHF" | "CZK" | "CAD" | "PLN" | "SEK" | "TRY" | "CNY" | "INR" | "BRL" | "ZAR" | "UZS" | "BGN" | "RON" | "AUD" | "HKD" | "GEL" | "KGS" | "AMD" | "AED";
/** Все значения Currency. */
export const CURRENCY_VALUES: readonly Currency[] = ["RUB", "EUR", "USD", "GBP", "UAH", "BYR", "BYN", "KZT", "AZN", "CHF", "CZK", "CAD", "PLN", "SEK", "TRY", "CNY", "INR", "BRL", "ZAR", "UZS", "BGN", "RON", "AUD", "HKD", "GEL", "KGS", "AMD", "AED"] as const;
/** Человекочитаемые названия Currency. */
export const currencyLabels: Record<Currency, string> = {
	["RUB"]: "Российский рубль",
	["EUR"]: "Евро",
	["USD"]: "Доллар США",
	["GBP"]: "Фунт стерлингов",
	["UAH"]: "Украинская гривна",
	["BYR"]: "Белорусский рубль (не используется с 1 июля 2016)",
	["BYN"]: "Белорусский рубль",
	["KZT"]: "Казахский тенге",
	["AZN"]: "Азербайджанский манат",
	["CHF"]: "Швейцарский франк",
	["CZK"]: "Чешская крона",
	["CAD"]: "Канадский доллар",
	["PLN"]: "Польский злотый",
	["SEK"]: "Шведская крона",
	["TRY"]: "Турецкая лира",
	["CNY"]: "Китайский юань",
	["INR"]: "Индийская рупия",
	["BRL"]: "Бразильский реал",
	["ZAR"]: "Южноафриканский рэнд",
	["UZS"]: "Узбекский сум",
	["BGN"]: "Болгарский лев",
	["RON"]: "Румынский лей",
	["AUD"]: "Австралийский доллар",
	["HKD"]: "Гонконгский доллар",
	["GEL"]: "Грузинский лари",
	["KGS"]: "Киргизский сом",
	["AMD"]: "Армянский драм",
	["AED"]: "Дирхам ОАЭ",
};

/**
 * Языки
 * @see https://developers.cloudpayments.ru/#cultures
 */
export type CultureName = "ru-RU" | "en-US" | "kk-KZ";
/** Все значения CultureName. */
export const CULTURE_NAME_VALUES: readonly CultureName[] = ["ru-RU", "en-US", "kk-KZ"] as const;
/** Человекочитаемые названия CultureName. */
export const cultureNameLabels: Record<CultureName, string> = {
	["ru-RU"]: "Русский",
	["en-US"]: "Английский",
	["kk-KZ"]: "Казахский",
};
/** Полная информация по CultureName (label + метаданные). */
export const cultureNameInfo: Record<CultureName, { label: string; "часовой пояс": string; }> = {
	["ru-RU"]: { label: "Русский", "часовой пояс": "MSK" },
	["en-US"]: { label: "Английский", "часовой пояс": "CET" },
	["kk-KZ"]: { label: "Казахский", "часовой пояс": "ALMT" },
};

/**
 * Типы уведомлений
 * @see https://developers.cloudpayments.ru/#tipy-uvedomleniy
 */
export type NotificationType = "Check" | "Pay" | "Fail" | "Confirm" | "Refund" | "Recurrent" | "Cancel";
/** Все значения NotificationType. */
export const NOTIFICATION_TYPE_VALUES: readonly NotificationType[] = ["Check", "Pay", "Fail", "Confirm", "Refund", "Recurrent", "Cancel"] as const;
/** Человекочитаемые названия NotificationType. */
export const notificationTypeLabels: Record<NotificationType, string> = {
	["Check"]: "[Check](#check)",
	["Pay"]: "[Pay](#pay)",
	["Fail"]: "[Fail](#fail)",
	["Confirm"]: "[Confirm](#confirm)",
	["Refund"]: "[Refund](#refund)",
	["Recurrent"]: "[Recurrent](#recurrent)",
	["Cancel"]: "[Cancel](#cancel)",
};

/**
 * Типы операций
 * @see https://developers.cloudpayments.ru/#tipy-operatsiy
 */
export type OperationType = "Payment" | "Refund" | "CardPayout";
/** Все значения OperationType. */
export const OPERATION_TYPE_VALUES: readonly OperationType[] = ["Payment", "Refund", "CardPayout"] as const;
/** Человекочитаемые названия OperationType. */
export const operationTypeLabels: Record<OperationType, string> = {
	["Payment"]: "Оплата",
	["Refund"]: "Возврат",
	["CardPayout"]: "Выплата на карту",
};

/**
 * Коды ошибок
 * @see https://developers.cloudpayments.ru/#kody-oshibok
 */
export type ReasonCode = 5001 | 5003 | 5004 | 5005 | 5006 | 5007 | 5012 | 5013 | 5014 | 5015 | 5017 | 5019 | 5030 | 5031 | 5033 | 5034 | 5036 | 5041 | 5043 | 5051 | 5054 | 5055 | 5057 | 5058 | 5059 | 5061 | 5062 | 5063 | 5065 | 5082 | 5091 | 5092 | 5096 | 5113 | 5204 | 5206 | 5207 | 5300 | 5303 | 5761 | 5762 | 5763 | 6001 | 6002 | 6003 | 6004 | 6005 | 6006 | 6007 | 6008 | 6009 | 6010 | 6011 | 6013 | 6014 | 6015 | 6016 | 6017 | 6021 | 6022 | 6025;
/** Все значения ReasonCode. */
export const REASON_CODE_VALUES: readonly ReasonCode[] = [5001, 5003, 5004, 5005, 5006, 5007, 5012, 5013, 5014, 5015, 5017, 5019, 5030, 5031, 5033, 5034, 5036, 5041, 5043, 5051, 5054, 5055, 5057, 5058, 5059, 5061, 5062, 5063, 5065, 5082, 5091, 5092, 5096, 5113, 5204, 5206, 5207, 5300, 5303, 5761, 5762, 5763, 6001, 6002, 6003, 6004, 6005, 6006, 6007, 6008, 6009, 6010, 6011, 6013, 6014, 6015, 6016, 6017, 6021, 6022, 6025] as const;
/** Человекочитаемые названия ReasonCode. */
export const reasonCodeLabels: Record<ReasonCode, string> = {
	[5001]: "Refer To Card Issuer",
	[5003]: "Invalid Merchant",
	[5004]: "Pick Up Card",
	[5005]: "Do Not Honor",
	[5006]: "Error",
	[5007]: "Pick Up Card Special Conditions",
	[5012]: "Invalid Transaction",
	[5013]: "Amount Error",
	[5014]: "Invalid Card Number",
	[5015]: "No Such Issuer",
	[5017]: "Customer Cancellation",
	[5019]: "Transaction Error",
	[5030]: "Format Error",
	[5031]: "Bank Not Supported By Switch",
	[5033]: "Expired Card Pickup",
	[5034]: "Suspected Fraud",
	[5036]: "Restricted Card",
	[5041]: "Lost Card",
	[5043]: "Stolen Card",
	[5051]: "Insufficient Funds",
	[5054]: "Expired Card",
	[5055]: "Invalid PIN",
	[5057]: "Transaction Not Permitted",
	[5058]: "Transaction Not Permitted To Card",
	[5059]: "Suspected Fraud Decline",
	[5061]: "Exceeds Approval Amount",
	[5062]: "Restricted Card 2",
	[5063]: "Security Violation",
	[5065]: "Exceed Withdrawal Frequency",
	[5082]: "Incorrect CVV",
	[5091]: "Timeout",
	[5092]: "Cannot Reach Network",
	[5096]: "System Error",
	[5113]: "Gateways do not support the currently selected payment card",
	[5204]: "Unable To Process",
	[5206]: "Authentication failed",
	[5207]: "Authentication unavailable",
	[5300]: "Anti Fraud",
	[5303]: "Acquirer Terminal Limits Exceeded",
	[5761]: "No Phone",
	[5762]: "Invalid Phone",
	[5763]: "Different Phones",
	[6001]: "SaveCardRefused",
	[6002]: "InvalidErrorCode",
	[6003]: "AgentIdNotExists",
	[6004]: "CurrencyNotValid",
	[6005]: "InvalidPaymentLink",
	[6006]: "AmountCurrencyNotValid",
	[6007]: "InvalidRedirectUrl",
	[6008]: "InvalidParamsId",
	[6009]: "InvalidTtl",
	[6010]: "SubscriptionNotFound",
	[6011]: "InvalidSubscription",
	[6013]: "InvalidRefund",
	[6014]: "OriginalDetailsIncorrect",
	[6015]: "TransactionNotFound",
	[6016]: "InvalidMemberId",
	[6017]: "IncorrectMCCategory",
	[6021]: "Receiver Account Error",
	[6022]: "Receiver Name Error",
	[6025]: "CrossTerminalTokenRestriction",
};
/** Полная информация по ReasonCode (label + метаданные). */
export const reasonCodeInfo: Record<ReasonCode, { label: string; "причина": string; "сообщение для плательщика": string; }> = {
	[5001]: { label: "Refer To Card Issuer", "причина": "Отказ эмитента проводить онлайн-операцию", "сообщение для плательщика": "Свяжитесь с вашим банком или воспользуйтесь другой картой" },
	[5003]: { label: "Invalid Merchant", "причина": "Отказ эмитента проводить онлайн-операцию", "сообщение для плательщика": "Свяжитесь с вашим банком или воспользуйтесь другой картой" },
	[5004]: { label: "Pick Up Card", "причина": "Карта потеряна", "сообщение для плательщика": "Свяжитесь с вашим банком или воспользуйтесь другой картой" },
	[5005]: { label: "Do Not Honor", "причина": "Отказ эмитента без объяснения причин `- неверно указан код CVV на картах Mastercard;` `- внутренние ограничения банка, выпустившего карту;` `- карта заблокирована или еще не активирована;` `- на карте не включены интернет-платежи или не подключен 3DS.`", "сообщение для плательщика": "Свяжитесь с вашим банком или воспользуйтесь другой картой" },
	[5006]: { label: "Error", "причина": "Отказ сети проводить операцию или неправильный CVV-код", "сообщение для плательщика": "Проверьте правильность введенных данных карты или воспользуйтесь другой картой" },
	[5007]: { label: "Pick Up Card Special Conditions", "причина": "Карта потеряна", "сообщение для плательщика": "Свяжитесь с вашим банком или воспользуйтесь другой картой" },
	[5012]: { label: "Invalid Transaction", "причина": "Карта не предназначена для онлайн-платежей", "сообщение для плательщика": "Воспользуйтесь другой картой или свяжитесь с банком, выпустившим карту" },
	[5013]: { label: "Amount Error", "причина": "Слишком маленькая или слишком большая сумма операции", "сообщение для плательщика": "Проверьте корректность суммы" },
	[5014]: { label: "Invalid Card Number", "причина": "Некорректный номер карты", "сообщение для плательщика": "Проверьте правильность введенных данных карты или воспользуйтесь другой картой" },
	[5015]: { label: "No Such Issuer", "причина": "Эмитент не найден", "сообщение для плательщика": "Проверьте правильность введенных данных карты или воспользуйтесь другой картой" },
	[5017]: { label: "Customer Cancellation", "причина": "Отказ по желанию держателя карты", "сообщение для плательщика": "Воспользуйтесь другой картой" },
	[5019]: { label: "Transaction Error", "причина": "Отказ эмитента без объяснения причин `- неверно указан код CVV на картах Mastercard;` `- внутренние ограничения банка, выпустившего карту;` `- карта заблокирована или еще не активирована;` `- на карте не включены интернет-платежи или не подключен 3DS.`", "сообщение для плательщика": "Свяжитесь с вашим банком или воспользуйтесь другой картой" },
	[5030]: { label: "Format Error", "причина": "Ошибка на стороне эквайера — неверно сформирована транзакция", "сообщение для плательщика": "Повторите попытку позже" },
	[5031]: { label: "Bank Not Supported By Switch", "причина": "Неизвестный эмитент карты", "сообщение для плательщика": "Воспользуйтесь другой картой" },
	[5033]: { label: "Expired Card Pickup", "причина": "Истек срок утери карты", "сообщение для плательщика": "Свяжитесь с вашим банком или воспользуйтесь другой картой" },
	[5034]: { label: "Suspected Fraud", "причина": "Отказ эмитента — подозрение на мошенничество", "сообщение для плательщика": "Свяжитесь с вашим банком или воспользуйтесь другой картой" },
	[5036]: { label: "Restricted Card", "причина": "Карта не предназначена для платежей", "сообщение для плательщика": "Платежи для этой карты запрещены. Попробуйте другую карту" },
	[5041]: { label: "Lost Card", "причина": "Карта потеряна", "сообщение для плательщика": "Свяжитесь с вашим банком или воспользуйтесь другой картой" },
	[5043]: { label: "Stolen Card", "причина": "Карта украдена", "сообщение для плательщика": "Свяжитесь с вашим банком или воспользуйтесь другой картой" },
	[5051]: { label: "Insufficient Funds", "причина": "Недостаточно средств", "сообщение для плательщика": "Недостаточно средств на карте" },
	[5054]: { label: "Expired Card", "причина": "Карта просрочена или неверно указан срок действия", "сообщение для плательщика": "Проверьте правильность введенных данных карты или воспользуйтесь другой картой" },
	[5055]: { label: "Invalid PIN", "причина": "Неверный PIN-код", "сообщение для плательщика": "Воспользуйтесь другой картой" },
	[5057]: { label: "Transaction Not Permitted", "причина": "Ограничение на карте `— внутренние ограничения банка, выпустившего карту;` `— карта заблокирована или еще не активирована;` `— на карте не включены интернет-платежи или не подключен 3DS.`", "сообщение для плательщика": "Свяжитесь с вашим банком или воспользуйтесь другой картой" },
	[5058]: { label: "Transaction Not Permitted To Card", "причина": "Транзакция не разрешена по карте", "сообщение для плательщика": "Свяжитесь с вашим банком или воспользуйтесь другой картой" },
	[5059]: { label: "Suspected Fraud Decline", "причина": "Транзакция была отклонена банком по подозрению в мошенничестве", "сообщение для плательщика": "Свяжитесь с банком или воспользуйтесь другой картой" },
	[5061]: { label: "Exceeds Approval Amount", "причина": "Превышена сумма по карте", "сообщение для плательщика": "Превышение лимита оплаты по карте. Измените настройки лимита или оплатите другой картой" },
	[5062]: { label: "Restricted Card 2", "причина": "Карта не предназначена для платежей", "сообщение для плательщика": "Платежи для этой карты запрещены. Попробуйте другую карту" },
	[5063]: { label: "Security Violation", "причина": "Карта заблокирована из-за нарушений безопасности", "сообщение для плательщика": "Воспользуйтесь другой картой" },
	[5065]: { label: "Exceed Withdrawal Frequency", "причина": "Превышен лимит операций по карте", "сообщение для плательщика": "Свяжитесь с вашим банком или воспользуйтесь другой картой" },
	[5082]: { label: "Incorrect CVV", "причина": "Неверный CVV-код", "сообщение для плательщика": "Неверно указан код CVV" },
	[5091]: { label: "Timeout", "причина": "Эмитент недоступен", "сообщение для плательщика": "Повторите попытку позже или воспользуйтесь другой картой" },
	[5092]: { label: "Cannot Reach Network", "причина": "Эмитент недоступен", "сообщение для плательщика": "Повторите попытку позже или воспользуйтесь другой картой" },
	[5096]: { label: "System Error", "причина": "Ошибка банка-эквайера или сети", "сообщение для плательщика": "Повторите попытку позже" },
	[5113]: { label: "Gateways do not support the currently selected payment card", "причина": "Шлюз не поддерживает эмитента неРФ", "сообщение для плательщика": "Воспользуйтесь другой картой" },
	[5204]: { label: "Unable To Process", "причина": "Операция не может быть обработана по прочим причинам", "сообщение для плательщика": "Свяжитесь с вашим банком или воспользуйтесь другой картой" },
	[5206]: { label: "Authentication failed", "причина": "3-D Secure авторизация не пройдена", "сообщение для плательщика": "Свяжитесь с вашим банком или воспользуйтесь другой картой" },
	[5207]: { label: "Authentication unavailable", "причина": "3-D Secure авторизация недоступна", "сообщение для плательщика": "Свяжитесь с вашим банком или воспользуйтесь другой картой" },
	[5300]: { label: "Anti Fraud", "причина": "Лимиты эквайера на проведение операций", "сообщение для плательщика": "Воспользуйтесь другой картой" },
	[5303]: { label: "Acquirer Terminal Limits Exceeded", "причина": "Превышение лимита на терминале", "сообщение для плательщика": "Свяжитесь с вашим банком или воспользуйтесь другой картой" },
	[5761]: { label: "No Phone", "причина": "Отсутствует номер телефона", "сообщение для плательщика": "Воспользуйтесь другой картой" },
	[5762]: { label: "Invalid Phone", "причина": "Некорректный номер телефона", "сообщение для плательщика": "Воспользуйтесь другой картой" },
	[5763]: { label: "Different Phones", "причина": "Номер телефона в запросе отличается", "сообщение для плательщика": "Воспользуйтесь другой картой" },
	[6001]: { label: "SaveCardRefused", "причина": "Отказ в привязке счета", "сообщение для плательщика": "Невозможно провести оплату" },
	[6002]: { label: "InvalidErrorCode", "причина": "Некорректное значение code", "сообщение для плательщика": "Невозможно провести оплату" },
	[6003]: { label: "AgentIdNotExists", "причина": "Значение agentId отсутствует в ОПКЦ СБП", "сообщение для плательщика": "Невозможно провести оплату" },
	[6004]: { label: "CurrencyNotValid", "причина": "Невозможно провести операцию с валютой `{currency}`", "сообщение для плательщика": "Обратитесь в поддержку сайта" },
	[6005]: { label: "InvalidPaymentLink", "причина": "Неверные данные платежной ссылки", "сообщение для плательщика": "Невозможно провести оплату" },
	[6006]: { label: "AmountCurrencyNotValid", "причина": "amount и currency должны одновременно присутствовать или одновременно отсутствовать при qrcType = 01", "сообщение для плательщика": "Невозможно провести оплату" },
	[6007]: { label: "InvalidRedirectUrl", "причина": "Некорректный формат redirectUrl", "сообщение для плательщика": "Невозможно провести оплату" },
	[6008]: { label: "InvalidParamsId", "причина": "Неверные данные paramsId", "сообщение для плательщика": "Невозможно провести оплату" },
	[6009]: { label: "InvalidTtl", "причина": "Период использования динамической Платежной ссылки СБП в поле qrTtl выходит за допустимый диапазон", "сообщение для плательщика": "Невозможно провести оплату" },
	[6010]: { label: "SubscriptionNotFound", "причина": "Привязка счета не найдена", "сообщение для плательщика": "Невозможно провести оплату" },
	[6011]: { label: "InvalidSubscription", "причина": "Неверные данные привязки счета", "сообщение для плательщика": "Невозможно провести оплату" },
	[6013]: { label: "InvalidRefund", "причина": "Дублирование идентификатора запроса, назначаемого ТСП или Агентом ТСП, - agentRefundRequestId", "сообщение для плательщика": "Невозможно провести оплату" },
	[6014]: { label: "OriginalDetailsIncorrect", "причина": "Параметры запроса отличаются от параметров исходной Операции СБП C2B", "сообщение для плательщика": "Невозможно провести оплату" },
	[6015]: { label: "TransactionNotFound", "причина": "Запрашиваемая транзакция не найдена", "сообщение для плательщика": "Невозможно провести оплату" },
	[6016]: { label: "InvalidMemberId", "причина": "Значение memberId отсутствует в ОПКЦ СБП", "сообщение для плательщика": "Невозможно провести оплату" },
	[6017]: { label: "IncorrectMCCategory", "причина": "Выполнение операций в данной категории ТСП запрещено", "сообщение для плательщика": "Невозможно провести оплату" },
	[6021]: { label: "Receiver Account Error", "причина": "У получателя нет расчетного счета в этом банке", "сообщение для плательщика": "Невозможно провести выплату" },
	[6022]: { label: "Receiver Name Error", "причина": "У получателя нет расчетного счета в этом банке. ФИО некорректное", "сообщение для плательщика": "Невозможно провести выплату" },
	[6025]: { label: "CrossTerminalTokenRestriction", "причина": "Запрет кросстерминальных оплат", "сообщение для плательщика": "Невозможно провести оплату" },
};

/**
 * Операторы фискальных данных
 * @see https://developers.cloudpayments.ru/#operatory-fiskalnyh-dannyh
 */
export type FiscalDataOperator = "PeterService" | "FirstOfd" | "Taxcom" | "PlatformaOfd" | "OfdYa" | "OfdYandex" | "Garantexpress" | "OfdAstralNalog" | "Sbis";
/** Все значения FiscalDataOperator. */
export const FISCAL_DATA_OPERATOR_VALUES: readonly FiscalDataOperator[] = ["PeterService", "FirstOfd", "Taxcom", "PlatformaOfd", "OfdYa", "OfdYandex", "Garantexpress", "OfdAstralNalog", "Sbis"] as const;
/** Человекочитаемые названия FiscalDataOperator. */
export const fiscalDataOperatorLabels: Record<FiscalDataOperator, string> = {
	["PeterService"]: "ООО «ПС СТ»",
	["FirstOfd"]: "Первый ОФД",
	["Taxcom"]: "Такском",
	["PlatformaOfd"]: "Платформа ОФД",
	["OfdYa"]: "ОФД-Я",
	["OfdYandex"]: "Яндекс ОФД",
	["Garantexpress"]: "Гарант ОФД",
	["OfdAstralNalog"]: "Астрал ОФД",
	["Sbis"]: "Компания \"ТЕНЗОР\", ООО",
};

/**
 * Коды временных зон
 * @see https://developers.cloudpayments.ru/#kody-vremennyh-zon
 */
export type TimeZoneCode = "HST" | "AKST" | "PST" | "MST" | "CST" | "EST" | "AST" | "BRT" | "UTC" | "GMT" | "CET" | "EET" | "MSK" | "AZT" | "AMT" | "SAMT" | "GET" | "TJT" | "YEKT" | "ALMT" | "NOVT" | "KRAT" | "HKT" | "IRKT" | "SGT" | "ULAT" | "YAKT" | "VLAT" | "SAKT" | "ANAT";
/** Все значения TimeZoneCode. */
export const TIME_ZONE_CODE_VALUES: readonly TimeZoneCode[] = ["HST", "AKST", "PST", "MST", "CST", "EST", "AST", "BRT", "UTC", "GMT", "CET", "EET", "MSK", "AZT", "AMT", "SAMT", "GET", "TJT", "YEKT", "ALMT", "NOVT", "KRAT", "HKT", "IRKT", "SGT", "ULAT", "YAKT", "VLAT", "SAKT", "ANAT"] as const;
/** Человекочитаемые названия TimeZoneCode. */
export const timeZoneCodeLabels: Record<TimeZoneCode, string> = {
	["HST"]: "(UTC-10:00) Гавайи",
	["AKST"]: "(UTC-09:00) Аляска",
	["PST"]: "(UTC-08:00) Тихоокеанское время (США и Канада)",
	["MST"]: "(UTC-07:00) Горное время (США и Канада)",
	["CST"]: "(UTC-06:00) Центральное время (США и Канада)",
	["EST"]: "(UTC-05:00) Восточное время (США и Канада)",
	["AST"]: "(UTC-04:00) Атлантическое время (Канада)",
	["BRT"]: "(UTC-03:00) Бразилия",
	["UTC"]: "(UTC) Время в формате UTC",
	["GMT"]: "(UTC) Дублин, Лиссабон, Лондон, Эдинбург",
	["CET"]: "(UTC+01:00) Амстердам, Берлин, Берн, Вена, Рим, Стокгольм",
	["EET"]: "(UTC+02:00) Афины, Бухарест",
	["MSK"]: "(UTC+03:00) Волгоград, Москва, Санкт-Петербург (RTZ 2)",
	["AZT"]: "(UTC+04:00) Баку",
	["AMT"]: "(UTC+04:00) Ереван",
	["SAMT"]: "(UTC+04:00) Ижевск, Самара (RTZ 3)",
	["GET"]: "(UTC+04:00) Тбилиси",
	["TJT"]: "(UTC+05:00) Ашхабад, Ташкент",
	["YEKT"]: "(UTC+05:00) Екатеринбург (RTZ 4)",
	["ALMT"]: "(UTC+06:00) Астана, Алматы",
	["NOVT"]: "(UTC+06:00) Новосибирск (RTZ 5)",
	["KRAT"]: "(UTC+07:00) Красноярск (RTZ 6)",
	["HKT"]: "(UTC+08:00) Гонконг, Пекин, Урумчи, Чунцин",
	["IRKT"]: "(UTC+08:00) Иркутск (RTZ 7)",
	["SGT"]: "(UTC+08:00) Куала-Лумпур, Сингапур",
	["ULAT"]: "(UTC+08:00) Улан-Батор",
	["YAKT"]: "(UTC+09:00) Якутск (RTZ 8)",
	["VLAT"]: "(UTC+10:00) Владивосток, Магадан (RTZ 9)",
	["SAKT"]: "(UTC+11:00) Чокурдах (RTZ 10)",
	["ANAT"]: "(UTC+12:00) Анадырь, Петропавловск-Камчатский (RTZ 11)",
};

/**
 * Коды обработки ответов на check уведомление
 * @see https://developers.cloudpayments.ru/#kody-obrabotki-otvetov-na-check-uvedomlenie
 */
export type CheckResponseCode = 3001 | 3002 | 3003 | 3004 | 3005 | 3006 | 3007 | 3008;
/** Все значения CheckResponseCode. */
export const CHECK_RESPONSE_CODE_VALUES: readonly CheckResponseCode[] = [3001, 3002, 3003, 3004, 3005, 3006, 3007, 3008] as const;
/** Человекочитаемые названия CheckResponseCode. */
export const checkResponseCodeLabels: Record<CheckResponseCode, string> = {
	[3001]: "InvalidInvoiceId",
	[3002]: "InvalidAccountId",
	[3003]: "InvalidAmount",
	[3004]: "OutOfDate",
	[3005]: "FormatError",
	[3006]: "Unavailable",
	[3007]: "UnableToConnect",
	[3008]: "NotAccepted",
};
/** Полная информация по CheckResponseCode (label + метаданные). */
export const checkResponseCodeInfo: Record<CheckResponseCode, { label: string; "причина": string; }> = {
	[3001]: { label: "InvalidInvoiceId", "причина": "Обработчик уведомления вернул `{\"code\":10}`" },
	[3002]: { label: "InvalidAccountId", "причина": "Обработчик уведомления вернул `{\"code\":11}`" },
	[3003]: { label: "InvalidAmount", "причина": "Обработчик уведомления вернул `{\"code\":12}`" },
	[3004]: { label: "OutOfDate", "причина": "Обработчик уведомления вернул `{\"code\":20}`" },
	[3005]: { label: "FormatError", "причина": "Обработчик уведомления вернул код, отличный от [ожидаемого](#check)" },
	[3006]: { label: "Unavailable", "причина": "Сервис недоступен" },
	[3007]: { label: "UnableToConnect", "причина": "Обработчик не отвечает (`404`, `504`, `508` и т.д)" },
	[3008]: { label: "NotAccepted", "причина": "Обработчик уведомления вернул `{\"code\":13}`" },
};
