/**
 * AUTO-GENERATED by tools/gen.ts from specs/ir.json.
 * Do not edit directly — run `bun run gen` instead.
 */

export * from "./meta.js";
export * from "./handbooks.js";
export * from "./endpoints.js";
export * from "./webhook-payloads.js";
export * from "./shared.js";
