/**
 * AUTO-GENERATED by tools/gen.ts from specs/ir.json.
 * Do not edit directly — run `bun run gen` instead.
 */

export const CP_SDK_NAME = "@onreza/cloudpayments-sdk" as const;
export const CP_SDK_VERSION = "0.1.0" as const;

export const CP_BASE_URL = "https://api.cloudpayments.ru" as const;
export const CP_BASE_URL_EU = "https://api.cloudpayments.eu" as const;
export const CP_BASE_URL_KZ = "https://api.cp.kz" as const;
export const CP_DOCS_URL = "https://developers.cloudpayments.ru" as const;

/** Дата парсинга документации, по которой собраны эти типы. */
export const CP_SDK_DOCS_SHA256 = "8970567fa60c6de9f3a5636cc19ff6a895609ccae6bcb494fca38fc5b562ffc0" as const;
export const CP_SDK_DOCS_PARSED_AT = "2026-07-27T06:15:38.343Z" as const;
