/**
 * AUTO-GENERATED by tools/gen.ts from specs/ir.json.
 * Do not edit directly — run `bun run gen` instead.
 */

export const CP_SDK_NAME = "@onreza/cloudpayments-sdk" as const;
export const CP_SDK_VERSION = "0.1.0" as const;

export const CP_BASE_URL = "https://api.cloudpayments.ru" as const;
export const CP_BASE_URL_EU = "https://api.cloudpayments.eu" as const;
export const CP_BASE_URL_KZ = "https://api.cp.kz" as const;
export const CP_DOCS_URL = "https://developers.cloudpayments.ru" as const;

/** Дата парсинга документации, по которой собраны эти типы. */
export const CP_SDK_DOCS_SHA256 = "3cdbf7c0ccc1dfef1f5acfddfb46372bf7d2b19d28b8deb8483e6b1fd15477d4" as const;
export const CP_SDK_DOCS_PARSED_AT = "2026-05-30T06:13:34.770Z" as const;
