/**
 * AUTO-GENERATED by tools/gen.ts from specs/ir.json.
 * Do not edit directly — run `bun run gen` instead.
 */

/**
 * Вложенные объекты, которые в документации CloudPayments передаются как "Object"
 * без формального schema. Описаны вручную исходя из текста описаний и примеров.
 * Эти типы используют Request-типы из endpoints.ts — не удаляйте и не переименовывайте.
 */

/** Плательщик (Payer object в charge/auth/payout/...) */
export interface Payer {
	FirstName?: string;
	LastName?: string;
	MiddleName?: string;
	/** Дата рождения, YYYY-MM-DD. */
	Birth?: string;
	Address?: string;
	Street?: string;
	City?: string;
	Country?: string;
	/** Телефон, только цифры, формат «+71234567890». */
	Phone?: string;
	Postcode?: string;
}

/** Онлайн-чек 54-ФЗ (передаётся в cloudpayments.CustomerReceipt). */
export interface Receipt {
	Items: ReceiptItem[];
	taxationSystem?: number;
	email?: string;
	phone?: string;
	isBso?: boolean;
	AgentSign?: string | null;
	amounts?: ReceiptAmounts;
}

export interface ReceiptItem {
	label: string;
	price: number;
	quantity: number;
	amount: number;
	vat?: number | null;
	method: number;
	object: number;
	measurementUnit?: string;
	agentSign?: string | null;
}

export interface ReceiptAmounts {
	electronic: number;
	advancePayment?: number;
	credit?: number;
	provision?: number;
}

/** cloudpayments-namespace внутри JsonData — инструкции для формирования подписки/чека. */
export interface CloudPaymentsMeta {
	CustomerReceipt?: Receipt;
	recurrent?: {
		interval: "Day" | "Week" | "Month";
		period: number;
		customerReceipt?: Receipt;
		amount?: number;
		startDate?: string;
		maxPeriods?: number | null;
	};
	ShouldAuthenticate3DS?: boolean;
}
