/**
 * AUTO-GENERATED by tools/gen.ts from specs/ir.json.
 * Do not edit directly — run `bun run gen` instead.
 */

import type { NotificationType, OperationType, TransactionStatus, Currency, CultureName } from "./handbooks.js";

/**
 * Payload уведомления Check.
 * Выполняется после того, как держатель заполнил платежную форму и нажал кнопку «Оплатить».
 * @see https://developers.cloudpayments.ru/#check
 */
export interface CheckNotificationPayload {
	/** Номер транзакции в системе */
	TransactionId: number;
	/** Сумма оплаты из параметров платежа */
	Amount: number;
	/** Валюта: RUB/USD/EUR/GBP из параметров платежа (см. [справочник](#spisok-valyut)) */
	Currency: Currency;
	/** Сумма списания */
	PaymentAmount: string;
	/** Валюта списания */
	PaymentCurrency: Currency;
	/** Дата/время создания платежа во временной зоне UTC */
	DateTime: string;
	/** Уникальный идентификатор карты в системе CloudPayments */
	CardId?: string;
	/** Первые 6 цифр номера карты */
	CardFirstSix: string;
	/** Последние 4 цифры номера карты */
	CardLastFour: string;
	/** Платежная система карты: Visa, Mastercard, Maestro или "МИР" */
	CardType: string;
	/** Срок действия карты в формате MM/YY */
	CardExpDate: string;
	/** Признак тестового режима */
	TestMode: 0 | 1;
	/** Статус платежа в случае успешного завершения: Completed — для [одностадийных платежей](#shemy-provedeniya-platezha), Authorized — для [двухстадийных](#shemy-provedeniya-platezha) */
	Status: TransactionStatus;
	/** Тип операции: Payment/Refund/CardPayout (см. [справочник](#tipy-operatsiy)) */
	OperationType: OperationType;
	/** Номер заказа из параметров платежа */
	InvoiceId?: string;
	/** Идентификатор пользователя из параметров платежа */
	AccountId?: string;
	/** Идентификатор подписки (для рекуррентных платежей) */
	SubscriptionId?: string;
	/** Токен получателя платежа */
	TokenRecipient?: string;
	/** Имя держателя карты */
	Name?: string;
	/** E-mail адрес плательщика */
	Email?: string;
	/** IP-адрес плательщика */
	IpAddress?: string;
	/** Двухбуквенный код страны нахождения плательщика по [ISO3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) */
	IpCountry?: string;
	/** Город нахождения плательщика */
	IpCity?: string;
	/** Регион нахождения плательщика */
	IpRegion?: string;
	/** Округ нахождения плательщика */
	IpDistrict?: string;
	/** Широта нахождения плательщика */
	IpLatitude?: string;
	/** Долгота нахождения плательщика */
	IpLongitude?: string;
	/** Название банка-эмитента карты */
	Issuer?: string;
	/** Двухбуквенный код страны эмитента карты по [ISO3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) */
	IssuerBankCountry?: string;
	/** Назначение оплаты из параметров платежа */
	Description?: string;
	/** Тип карточного продукта */
	CardProduct?: string;
	/** Метод оплаты (например, T-Pay) */
	PaymentMethod?: string;
	/** Произвольный набор параметров, переданных в транзакцию */
	Data?: Record<string, unknown>;
}

/**
 * Payload уведомления Pay.
 * Выполняется после того, как оплата была успешно проведена и получена авторизация эмитента.
 * @see https://developers.cloudpayments.ru/#pay
 */
export interface PayNotificationPayload {
	/** Номер транзакции в системе */
	TransactionId: number;
	/** Сумма оплаты из параметров платежа */
	Amount: number;
	/** Валюта: RUB/USD/EUR/GBP из параметров платежа (см. [справочник](#spisok-valyut)) */
	Currency: Currency;
	/** Сумма списания */
	PaymentAmount: string;
	/** Валюта списания */
	PaymentCurrency: Currency;
	/** Дата/время создания платежа во временной зоне UTC */
	DateTime: string;
	/** Уникальный идентификатор карты в системе CloudPayments */
	CardId?: string;
	/** Первые 6 цифр номера карты */
	CardFirstSix: string;
	/** Последние 4 цифры номера карты */
	CardLastFour: string;
	/** Платежная система карты: Visa, Mastercard, Maestro или "МИР" */
	CardType: string;
	/** Срок действия карты в формате MM/YY */
	CardExpDate: string;
	/** Признак тестового режима */
	TestMode: 0 | 1;
	/** Статус платежа после авторизации: `Completed` — для одностадийных платежей, `Authorized` — для двухстадийных */
	Status: TransactionStatus;
	/** Тип операции: Payment/CardPayout (см. [справочник](#tipy-operatsiy)) */
	OperationType: OperationType;
	/** Идентификатор банка-эквайера */
	GatewayName: string;
	/** Номер заказа из параметров платежа */
	InvoiceId?: string;
	/** Идентификатор пользователя из параметров платежа */
	AccountId?: string;
	/** Идентификатор подписки (для рекуррентных платежей) */
	SubscriptionId?: string;
	/** Имя держателя карты */
	Name?: string;
	/** E-mail адрес плательщика */
	Email?: string;
	/** IP-адрес плательщика */
	IpAddress?: string;
	/** Двухбуквенный код страны нахождения плательщика по [ISO3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) */
	IpCountry?: string;
	/** Город нахождения плательщика */
	IpCity?: string;
	/** Регион нахождения плательщика */
	IpRegion?: string;
	/** Округ нахождения плательщика */
	IpDistrict?: string;
	/** Широта нахождения плательщика */
	IpLatitude?: string;
	/** Долгота нахождения плательщика */
	IpLongitude?: string;
	/** Название банка-эмитента карты */
	Issuer?: string;
	/** Двухбуквенный код страны эмитента карты по [ISO3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) */
	IssuerBankCountry?: string;
	/** Назначение оплаты из параметров платежа */
	Description?: string;
	/** Код авторизации */
	AuthCode?: string;
	/** Произвольный набор параметров, переданных в транзакцию */
	Data?: Record<string, unknown>;
	/** Токен карты для повторных платежей без ввода реквизитов */
	Token?: string;
	/** Значение общей комиссии */
	TotalFee?: number;
	/** Тип карточного продукта */
	CardProduct?: string;
	/** Метод оплаты (например, T-Pay) */
	PaymentMethod?: string;
	/** Номер первой неуспешной транзакции */
	FallBackScenarioDeclinedTransactionId?: number;
	/** Уникальный номер банковской транзакции, который назначается обслуживающим банком */
	Rrn?: string;
	/** Кастомные поля, которые передает мерчант в запросе оплаты */
	CustomFields?: unknown[];
}

/**
 * Payload уведомления Fail.
 * Выполняется в случае, если оплата была отклонена, и используется для анализа количества и причин отказов.
 * @see https://developers.cloudpayments.ru/#fail
 */
export interface FailNotificationPayload {
	/** Номер транзакции в системе */
	TransactionId: number;
	/** Сумма оплаты из параметров платежа */
	Amount: number;
	/** Валюта: RUB/USD/EUR/GBP из параметров платежа (см. [справочник](#spisok-valyut)) */
	Currency: Currency;
	/** Сумма списания */
	PaymentAmount: string;
	/** Валюта списания */
	PaymentCurrency: Currency;
	/** Дата/время создания платежа во временной зоне UTC */
	DateTime: string;
	/** Уникальный идентификатор карты в системе CloudPayments */
	CardId?: string;
	/** Первые 6 цифр номера карты */
	CardFirstSix: string;
	/** Последние 4 цифры номера карты */
	CardLastFour: string;
	/** Платежная система карты: Visa, Mastercard, Maestro или "МИР" */
	CardType: string;
	/** Срок действия карты в формате MM/YY */
	CardExpDate: string;
	/** Признак тестового режима */
	TestMode: 0 | 1;
	/** Причина отказа */
	Reason: string;
	/** Код ошибки (см. [справочник](#kody-oshibok)) */
	ReasonCode: number;
	/** Тип операции: Payment/Refund/CardPayout (см. [справочник](#tipy-operatsiy)) */
	OperationType: OperationType;
	/** Номер заказа из параметров платежа */
	InvoiceId?: string;
	/** Идентификатор пользователя из параметров платежа */
	AccountId?: string;
	/** Идентификатор подписки (для рекуррентных платежей) */
	SubscriptionId?: string;
	/** Имя держателя карты */
	Name?: string;
	/** E-mail адрес плательщика */
	Email?: string;
	/** IP-адрес плательщика */
	IpAddress?: string;
	/** Двухбуквенный код страны нахождения плательщика по [ISO3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) */
	IpCountry?: string;
	/** Город нахождения плательщика */
	IpCity?: string;
	/** Регион нахождения плательщика */
	IpRegion?: string;
	/** Округ нахождения плательщика */
	IpDistrict?: string;
	/** Широта нахождения плательщика */
	IpLatitude?: string;
	/** Долгота нахождения плательщика */
	IpLongitude?: string;
	/** Название банка-эмитента карты */
	Issuer?: string;
	/** Двухбуквенный код страны эмитента карты по [ISO3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) */
	IssuerBankCountry?: string;
	/** Назначение оплаты из параметров платежа */
	Description?: string;
	/** Произвольный набор параметров, переданных в транзакцию */
	Data?: Record<string, unknown>;
	/** Токен карты для повторных платежей без ввода реквизитов */
	Token?: string;
	/** Метод оплаты (например, T-Pay) */
	PaymentMethod?: string;
	/** Номер первой неуспешной транзакции */
	FallBackScenarioDeclinedTransactionId?: number;
	/** Уникальный номер банковской транзакции, который назначается обслуживающим банком */
	Rrn?: string;
	/** Кастомные поля, которые передает мерчант в запросе оплаты */
	CustomFields?: unknown[];
}

/**
 * Payload уведомления Confirm.
 * Выполняется после подтверждения платежа, проведенного по [двухстадийной](#shemy-provedeniya-platezha) схеме.
 * @see https://developers.cloudpayments.ru/#confirm
 */
export interface ConfirmNotificationPayload {
	/** Номер транзакции в системе */
	TransactionId: number;
	/** Сумма оплаты из параметров платежа */
	Amount: number;
	/** Валюта: RUB/USD/EUR/GBP из параметров платежа (см. [справочник](#spisok-valyut)) */
	Currency: Currency;
	/** Сумма списания */
	PaymentAmount: string;
	/** Валюта списания */
	PaymentCurrency: Currency;
	/** Дата/время создания платежа во временной зоне UTC */
	DateTime: string;
	/** Первые 6 цифр номера карты */
	CardFirstSix: string;
	/** Последние 4 цифры номера карты */
	CardLastFour: string;
	/** Платежная система карты: Visa, Mastercard, Maestro или "МИР" */
	CardType: string;
	/** Срок действия карты в формате MM/YY */
	CardExpDate: string;
	/** Признак тестового режима */
	TestMode: 0 | 1;
	/** Статус платежа после авторизации: Completed */
	Status: TransactionStatus;
	/** Номер заказа из параметров платежа */
	InvoiceId?: string;
	/** Идентификатор пользователя из параметров платежа */
	AccountId?: string;
	/** Идентификатор подписки (для рекуррентных платежей) */
	SubscriptionId?: string;
	/** Имя держателя карты */
	Name?: string;
	/** E-mail адрес плательщика */
	Email?: string;
	/** IP-адрес плательщика */
	IpAddress?: string;
	/** Двухбуквенный код страны нахождения плательщика по [ISO3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) */
	IpCountry?: string;
	/** Город нахождения плательщика */
	IpCity?: string;
	/** Регион нахождения плательщика */
	IpRegion?: string;
	/** Округ нахождения плательщика */
	IpDistrict?: string;
	/** Широта нахождения плательщика */
	IpLatitude?: string;
	/** Долгота нахождения плательщика */
	IpLongitude?: string;
	/** Название банка-эмитента карты */
	Issuer?: string;
	/** Двухбуквенный код страны эмитента карты по [ISO3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) */
	IssuerBankCountry?: string;
	/** Назначение оплаты из параметров платежа */
	Description?: string;
	/** Код авторизации */
	AuthCode?: string;
	/** Произвольный набор параметров, переданных в транзакцию */
	Data?: Record<string, unknown>;
	/** Токен карты для повторных платежей без ввода реквизитов */
	Token?: string;
	/** Метод оплаты (например, T-Pay) */
	PaymentMethod?: string;
	/** Уникальный номер банковской транзакции, который назначается обслуживающим банком */
	Rrn?: string;
}

/**
 * Payload уведомления Refund.
 * Выполняется в случае, если платеж был возвращен (полностью или частично) по вашей инициативе через [API](#vozvrat-deneg) или личный кабинет.
 * @see https://developers.cloudpayments.ru/#refund
 */
export interface RefundNotificationPayload {
	/** Номер транзакции возврата в системе */
	TransactionId: number;
	/** Номер оригинальной транзакции оплаты в системе */
	PaymentTransactionId: number;
	/** Сумма возврата в валюте платежа */
	Amount: number;
	/** Дата/время возврата по временной зоне UTC */
	DateTime: string;
	/** Тип операции: Refund/CardPayout (см. [справочник](#tipy-operatsiy)) */
	OperationType: OperationType;
	/** Номер заказа оригинальной операции */
	InvoiceId?: string;
	/** Идентификатор пользователя оригинальной операции */
	AccountId?: string;
	/** E-mail адрес плательщика */
	Email?: string;
	/** Произвольный набор параметров, переданных в транзакцию */
	Data?: Record<string, unknown>;
	/** Уникальный номер банковской транзакции, который назначается обслуживающим банком */
	Rrn?: string;
	/** Кастомные поля, которые передает мерчант в запросе оплаты */
	CustomFields?: unknown[];
}

/**
 * Payload уведомления Recurrent.
 * Выполняется в случае, если статус подписки на рекуррентный платеж был изменен.
 * @see https://developers.cloudpayments.ru/#recurrent
 */
export interface RecurrentNotificationPayload {
	/** Идентификатор подписки */
	Id: string;
	/** Идентификатор пользователя */
	AccountId: string;
	/** Назначение платежа в свободной форме */
	Description: string;
	/** E-mail плательщика */
	Email: string;
	/** Сумма платежа */
	Amount: number;
	/** Валюта: RUB/USD/EUR/GBP из параметров платежа (см. [справочник](#spisok-valyut)) */
	Currency: Currency;
	/** Если значение `true` — платеж будет выполнен по [двухстадийной схеме](#shemy-provedeniya-platezha) */
	RequireConfirmation: boolean;
	/** Дата и время первого платежа по плану во временной зоне UTC */
	StartDate: string;
	/** Интервал. Возможные значения: Week, Month */
	Interval: string;
	/** Период. В комбинации с интервалом 1 Month значит раз в месяц, а 2 Week — раз в две недели */
	Period: number;
	/** [Статусы подписок](#statusy-podpisok-rekurrent) */
	Status: TransactionStatus;
	/** Количество успешных платежей */
	SuccessfulTransactionsNumber: number;
	/** Количество неуспешных платежей (обнуляется после каждого успешного) */
	FailedTransactionsNumber: number;
	/** Максимальное количество платежей в подписке */
	MaxPeriods?: number;
	/** Дата и время последнего успешного платежа во временной зоне UTC */
	LastTransactionDate?: string;
	/** Дата и время следующего платежа во временной зоне UTC */
	NextTransactionDate?: string;
}

/**
 * Payload уведомления Cancel.
 * Выполняется в случае, если платеж был отменен по вашей инициативе через [API](#api) или личный кабинет.
 * @see https://developers.cloudpayments.ru/#cancel
 */
export interface CancelNotificationPayload {
	/** Номер отмененной транзакции в системе */
	TransactionId: number;
	/** Сумма отмененной транзакции в валюте платежа */
	Amount: number;
	/** Дата/время отмены по временной зоне UTC */
	DateTime: string;
	/** Номер заказа отмененной операции */
	InvoiceId?: string;
	/** Идентификатор пользователя отмененной операции */
	AccountId?: string;
	/** E-mail адрес плательщика */
	Email?: string;
	/** Произвольный набор параметров, переданных в транзакцию */
	Data?: Record<string, unknown>;
	/** Уникальный номер банковской транзакции, который назначается обслуживающим банком */
	Rrn?: string;
}

/** Discriminated union всех входящих payload-ов по заголовку X-Content-HMAC. */
export type AnyWebhookPayload = CheckNotificationPayload | PayNotificationPayload | FailNotificationPayload | ConfirmNotificationPayload | RefundNotificationPayload | RecurrentNotificationPayload | CancelNotificationPayload;
