/**
 * AUTO-GENERATED by tools/gen.ts from specs/ir.json.
 * Do not edit directly — run `bun run gen` instead.
 */

import type { OperationType, TransactionStatus, SubscriptionStatus, Currency, CultureName } from "./handbooks.js";

import type { KktReceipt, KktReceiptType } from "../models.js";

/** Runtime coercion schema для form-urlencoded webhook payload-ов. */
export const WEBHOOK_FIELD_SCHEMAS = {
	AccountId: { kind: "string", optional: false },
	Amount: { kind: "number", optional: false },
	AuthCode: { kind: "string", optional: true },
	CalculationPlace: { kind: "string", optional: true },
	CardExpDate: { kind: "string", optional: false },
	CardFirstSix: { kind: "string", optional: false },
	CardId: { kind: "string", optional: true },
	CardLastFour: { kind: "string", optional: false },
	CardProduct: { kind: "string", optional: true },
	CardType: { kind: "string", optional: false },
	CashierName: { kind: "string", optional: true },
	Currency: { kind: "string", optional: false },
	CustomFields: { kind: "json-array", optional: true },
	Data: { kind: "json-object", optional: true },
	DateTime: { kind: "string", optional: false },
	Description: { kind: "string", optional: false },
	DeviceNumber: { kind: "string", optional: false },
	DocumentNumber: { kind: "number", optional: false },
	Email: { kind: "string", optional: false },
	FailedTransactionsNumber: { kind: "number", optional: false },
	FallBackScenarioDeclinedTransactionId: { kind: "number", optional: true },
	FiscalNumber: { kind: "string", optional: false },
	FiscalSign: { kind: "string", optional: false },
	GatewayName: { kind: "string", optional: false },
	Id: { kind: "string", optional: false },
	Inn: { kind: "string", optional: false },
	Interval: { kind: "string", optional: false },
	InvoiceId: { kind: "string", optional: true },
	IpAddress: { kind: "string", optional: true },
	IpCity: { kind: "string", optional: true },
	IpCountry: { kind: "string", optional: true },
	IpDistrict: { kind: "string", optional: true },
	IpLatitude: { kind: "string", optional: true },
	IpLongitude: { kind: "string", optional: true },
	IpRegion: { kind: "string", optional: true },
	Issuer: { kind: "string", optional: true },
	IssuerBankCountry: { kind: "string", optional: true },
	LastTransactionDate: { kind: "string", optional: true },
	MaxPeriods: { kind: "number", optional: true },
	Name: { kind: "string", optional: true },
	NextTransactionDate: { kind: "string", optional: true },
	Number: { kind: "number", optional: false },
	Ofd: { kind: "string", optional: false },
	OperationType: { kind: "string", optional: false },
	PaymentAmount: { kind: "string", optional: false },
	PaymentCurrency: { kind: "string", optional: false },
	PaymentMethod: { kind: "string", optional: true },
	PaymentTransactionId: { kind: "number", optional: false },
	Period: { kind: "number", optional: false },
	ProcessorAndPartnerFee: { kind: "number", optional: true },
	ProviderMessage: { kind: "string", optional: true },
	QrCodeUrl: { kind: "string", optional: false },
	Reason: { kind: "string", optional: false },
	ReasonCode: { kind: "number", optional: false },
	Receipt: { kind: "json-object", optional: false },
	RegNumber: { kind: "string", optional: false },
	RequireConfirmation: { kind: "boolean", optional: false },
	RetryAfter: { kind: "string", optional: true },
	Rrn: { kind: "string", optional: true },
	SessionNumber: { kind: "number", optional: false },
	SettlePlace: { kind: "string", optional: true },
	StartDate: { kind: "string", optional: false },
	Status: { kind: "string", optional: false },
	SubscriptionId: { kind: "string", optional: true },
	SuccessfulTransactionsNumber: { kind: "number", optional: false },
	TestMode: { kind: "bit", optional: false },
	Token: { kind: "string", optional: true },
	TokenRecipient: { kind: "string", optional: true },
	TotalFee: { kind: "number", optional: true },
	TransactionId: { kind: "number", optional: false },
	Type: { kind: "string", optional: false },
	Url: { kind: "string", optional: false },
	VatAboveTotalFee: { kind: "number", optional: true },
	VatWithinProcessorFee: { kind: "number", optional: true },
} as const;

/** Runtime coercion schemas для конкретных типов webhook payload-ов. */
export const WEBHOOK_FIELD_SCHEMAS_BY_TYPE = {
	Check: {
		AccountId: { kind: "string", optional: true },
		Amount: { kind: "number", optional: false },
		CardExpDate: { kind: "string", optional: false },
		CardFirstSix: { kind: "string", optional: false },
		CardId: { kind: "string", optional: true },
		CardLastFour: { kind: "string", optional: false },
		CardProduct: { kind: "string", optional: true },
		CardType: { kind: "string", optional: false },
		Currency: { kind: "string", optional: false },
		Data: { kind: "json-object", optional: true },
		DateTime: { kind: "string", optional: false },
		Description: { kind: "string", optional: true },
		Email: { kind: "string", optional: true },
		InvoiceId: { kind: "string", optional: true },
		IpAddress: { kind: "string", optional: true },
		IpCity: { kind: "string", optional: true },
		IpCountry: { kind: "string", optional: true },
		IpDistrict: { kind: "string", optional: true },
		IpLatitude: { kind: "string", optional: true },
		IpLongitude: { kind: "string", optional: true },
		IpRegion: { kind: "string", optional: true },
		Issuer: { kind: "string", optional: true },
		IssuerBankCountry: { kind: "string", optional: true },
		Name: { kind: "string", optional: true },
		OperationType: { kind: "string", optional: false },
		PaymentAmount: { kind: "string", optional: false },
		PaymentCurrency: { kind: "string", optional: false },
		PaymentMethod: { kind: "string", optional: true },
		Status: { kind: "string", optional: false },
		SubscriptionId: { kind: "string", optional: true },
		TestMode: { kind: "bit", optional: false },
		TokenRecipient: { kind: "string", optional: true },
		TransactionId: { kind: "number", optional: false },
	},
	Pay: {
		AccountId: { kind: "string", optional: true },
		Amount: { kind: "number", optional: false },
		AuthCode: { kind: "string", optional: true },
		CardExpDate: { kind: "string", optional: false },
		CardFirstSix: { kind: "string", optional: false },
		CardId: { kind: "string", optional: true },
		CardLastFour: { kind: "string", optional: false },
		CardProduct: { kind: "string", optional: true },
		CardType: { kind: "string", optional: false },
		Currency: { kind: "string", optional: false },
		CustomFields: { kind: "json-array", optional: true },
		Data: { kind: "json-object", optional: true },
		DateTime: { kind: "string", optional: false },
		Description: { kind: "string", optional: true },
		Email: { kind: "string", optional: true },
		FallBackScenarioDeclinedTransactionId: { kind: "number", optional: true },
		GatewayName: { kind: "string", optional: false },
		InvoiceId: { kind: "string", optional: true },
		IpAddress: { kind: "string", optional: true },
		IpCity: { kind: "string", optional: true },
		IpCountry: { kind: "string", optional: true },
		IpDistrict: { kind: "string", optional: true },
		IpLatitude: { kind: "string", optional: true },
		IpLongitude: { kind: "string", optional: true },
		IpRegion: { kind: "string", optional: true },
		Issuer: { kind: "string", optional: true },
		IssuerBankCountry: { kind: "string", optional: true },
		Name: { kind: "string", optional: true },
		OperationType: { kind: "string", optional: false },
		PaymentAmount: { kind: "string", optional: false },
		PaymentCurrency: { kind: "string", optional: false },
		PaymentMethod: { kind: "string", optional: true },
		ProcessorAndPartnerFee: { kind: "number", optional: true },
		Rrn: { kind: "string", optional: true },
		Status: { kind: "string", optional: false },
		SubscriptionId: { kind: "string", optional: true },
		TestMode: { kind: "bit", optional: false },
		Token: { kind: "string", optional: true },
		TotalFee: { kind: "number", optional: true },
		TransactionId: { kind: "number", optional: false },
		VatAboveTotalFee: { kind: "number", optional: true },
		VatWithinProcessorFee: { kind: "number", optional: true },
	},
	Fail: {
		AccountId: { kind: "string", optional: true },
		Amount: { kind: "number", optional: false },
		CardExpDate: { kind: "string", optional: false },
		CardFirstSix: { kind: "string", optional: false },
		CardId: { kind: "string", optional: true },
		CardLastFour: { kind: "string", optional: false },
		CardType: { kind: "string", optional: false },
		Currency: { kind: "string", optional: false },
		CustomFields: { kind: "json-array", optional: true },
		Data: { kind: "json-object", optional: true },
		DateTime: { kind: "string", optional: false },
		Description: { kind: "string", optional: true },
		Email: { kind: "string", optional: true },
		FallBackScenarioDeclinedTransactionId: { kind: "number", optional: true },
		InvoiceId: { kind: "string", optional: true },
		IpAddress: { kind: "string", optional: true },
		IpCity: { kind: "string", optional: true },
		IpCountry: { kind: "string", optional: true },
		IpDistrict: { kind: "string", optional: true },
		IpLatitude: { kind: "string", optional: true },
		IpLongitude: { kind: "string", optional: true },
		IpRegion: { kind: "string", optional: true },
		Issuer: { kind: "string", optional: true },
		IssuerBankCountry: { kind: "string", optional: true },
		Name: { kind: "string", optional: true },
		OperationType: { kind: "string", optional: false },
		PaymentAmount: { kind: "string", optional: false },
		PaymentCurrency: { kind: "string", optional: false },
		PaymentMethod: { kind: "string", optional: true },
		ProviderMessage: { kind: "string", optional: true },
		Reason: { kind: "string", optional: false },
		ReasonCode: { kind: "number", optional: false },
		RetryAfter: { kind: "string", optional: true },
		Rrn: { kind: "string", optional: true },
		SubscriptionId: { kind: "string", optional: true },
		TestMode: { kind: "bit", optional: false },
		Token: { kind: "string", optional: true },
		TransactionId: { kind: "number", optional: false },
	},
	Confirm: {
		AccountId: { kind: "string", optional: true },
		Amount: { kind: "number", optional: false },
		AuthCode: { kind: "string", optional: true },
		CardExpDate: { kind: "string", optional: false },
		CardFirstSix: { kind: "string", optional: false },
		CardLastFour: { kind: "string", optional: false },
		CardType: { kind: "string", optional: false },
		Currency: { kind: "string", optional: false },
		Data: { kind: "json-object", optional: true },
		DateTime: { kind: "string", optional: false },
		Description: { kind: "string", optional: true },
		Email: { kind: "string", optional: true },
		InvoiceId: { kind: "string", optional: true },
		IpAddress: { kind: "string", optional: true },
		IpCity: { kind: "string", optional: true },
		IpCountry: { kind: "string", optional: true },
		IpDistrict: { kind: "string", optional: true },
		IpLatitude: { kind: "string", optional: true },
		IpLongitude: { kind: "string", optional: true },
		IpRegion: { kind: "string", optional: true },
		Issuer: { kind: "string", optional: true },
		IssuerBankCountry: { kind: "string", optional: true },
		Name: { kind: "string", optional: true },
		PaymentAmount: { kind: "string", optional: false },
		PaymentCurrency: { kind: "string", optional: false },
		PaymentMethod: { kind: "string", optional: true },
		Rrn: { kind: "string", optional: true },
		Status: { kind: "string", optional: false },
		SubscriptionId: { kind: "string", optional: true },
		TestMode: { kind: "bit", optional: false },
		Token: { kind: "string", optional: true },
		TransactionId: { kind: "number", optional: false },
	},
	Refund: {
		AccountId: { kind: "string", optional: true },
		Amount: { kind: "number", optional: false },
		CustomFields: { kind: "json-array", optional: true },
		Data: { kind: "json-object", optional: true },
		DateTime: { kind: "string", optional: false },
		Email: { kind: "string", optional: true },
		InvoiceId: { kind: "string", optional: true },
		OperationType: { kind: "string", optional: false },
		PaymentTransactionId: { kind: "number", optional: false },
		Rrn: { kind: "string", optional: true },
		TransactionId: { kind: "number", optional: false },
	},
	Recurrent: {
		AccountId: { kind: "string", optional: false },
		Amount: { kind: "number", optional: false },
		Currency: { kind: "string", optional: false },
		Description: { kind: "string", optional: false },
		Email: { kind: "string", optional: false },
		FailedTransactionsNumber: { kind: "number", optional: false },
		Id: { kind: "string", optional: false },
		Interval: { kind: "string", optional: false },
		LastTransactionDate: { kind: "string", optional: true },
		MaxPeriods: { kind: "number", optional: true },
		NextTransactionDate: { kind: "string", optional: true },
		Period: { kind: "number", optional: false },
		RequireConfirmation: { kind: "boolean", optional: false },
		StartDate: { kind: "string", optional: false },
		Status: { kind: "string", optional: false },
		SuccessfulTransactionsNumber: { kind: "number", optional: false },
	},
	Cancel: {
		AccountId: { kind: "string", optional: true },
		Amount: { kind: "number", optional: false },
		Data: { kind: "json-object", optional: true },
		DateTime: { kind: "string", optional: false },
		Email: { kind: "string", optional: true },
		InvoiceId: { kind: "string", optional: true },
		Rrn: { kind: "string", optional: true },
		TransactionId: { kind: "number", optional: false },
	},
	Receipt: {
		AccountId: { kind: "string", optional: true },
		Amount: { kind: "number", optional: false },
		CalculationPlace: { kind: "string", optional: true },
		CashierName: { kind: "string", optional: true },
		DateTime: { kind: "string", optional: false },
		DeviceNumber: { kind: "string", optional: false },
		DocumentNumber: { kind: "number", optional: false },
		FiscalNumber: { kind: "string", optional: false },
		FiscalSign: { kind: "string", optional: false },
		Id: { kind: "string", optional: false },
		Inn: { kind: "string", optional: false },
		InvoiceId: { kind: "string", optional: true },
		Number: { kind: "number", optional: false },
		Ofd: { kind: "string", optional: false },
		QrCodeUrl: { kind: "string", optional: false },
		Receipt: { kind: "json-object", optional: false },
		RegNumber: { kind: "string", optional: false },
		SessionNumber: { kind: "number", optional: false },
		SettlePlace: { kind: "string", optional: true },
		TransactionId: { kind: "number", optional: true },
		Type: { kind: "string", optional: false },
		Url: { kind: "string", optional: false },
	},
} as const;

/**
 * Payload уведомления Check.
 * Выполняется после того, как держатель заполнил платежную форму и нажал кнопку «Оплатить».
 * @see https://developers.cloudpayments.ru/#check
 */
export interface CheckNotificationPayload {
	/** Номер транзакции в системе */
	TransactionId: number;
	/** Сумма оплаты из параметров платежа */
	Amount: number;
	/** Валюта: RUB/USD/EUR/GBP из параметров платежа (см. [справочник](#spisok-valyut)) */
	Currency: Currency;
	/** Сумма списания */
	PaymentAmount: string;
	/** Валюта списания */
	PaymentCurrency: Currency;
	/** Дата/время создания платежа во временной зоне UTC */
	DateTime: string;
	/** Уникальный идентификатор карты в системе CloudPayments */
	CardId?: string;
	/** Первые 6 цифр номера карты */
	CardFirstSix: string;
	/** Последние 4 цифры номера карты */
	CardLastFour: string;
	/** Платежная система карты: Visa, Mastercard, Maestro или "МИР" */
	CardType: string;
	/** Срок действия карты в формате MM/YY */
	CardExpDate: string;
	/** Признак тестового режима */
	TestMode: 0 | 1;
	/** Статус платежа в случае успешного завершения: Completed — для [одностадийных платежей](#shemy-provedeniya-platezha), Authorized — для [двухстадийных](#shemy-provedeniya-platezha) */
	Status: TransactionStatus;
	/** Тип операции: Payment/Refund/CardPayout (см. [справочник](#tipy-operatsiy)) */
	OperationType: OperationType;
	/** Номер заказа из параметров платежа */
	InvoiceId?: string;
	/** Идентификатор пользователя из параметров платежа */
	AccountId?: string;
	/** Идентификатор подписки (для рекуррентных платежей) */
	SubscriptionId?: string;
	/** Токен получателя платежа */
	TokenRecipient?: string;
	/** Имя держателя карты */
	Name?: string;
	/** E-mail адрес плательщика */
	Email?: string;
	/** IP-адрес плательщика */
	IpAddress?: string;
	/** Двухбуквенный код страны нахождения плательщика по [ISO3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) */
	IpCountry?: string;
	/** Город нахождения плательщика */
	IpCity?: string;
	/** Регион нахождения плательщика */
	IpRegion?: string;
	/** Округ нахождения плательщика */
	IpDistrict?: string;
	/** Широта нахождения плательщика */
	IpLatitude?: string;
	/** Долгота нахождения плательщика */
	IpLongitude?: string;
	/** Название банка-эмитента карты */
	Issuer?: string;
	/** Двухбуквенный код страны эмитента карты по [ISO3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) */
	IssuerBankCountry?: string;
	/** Назначение оплаты из параметров платежа */
	Description?: string;
	/** Тип карточного продукта */
	CardProduct?: string;
	/** Метод оплаты (например, T-Pay) */
	PaymentMethod?: string;
	/** Произвольный набор параметров, переданных в транзакцию */
	Data?: Record<string, unknown>;
}

/**
 * Payload уведомления Pay.
 * Выполняется после того, как оплата была успешно проведена и получена авторизация эмитента.
 * @see https://developers.cloudpayments.ru/#pay
 */
export interface PayNotificationPayload {
	/** Номер транзакции в системе */
	TransactionId: number;
	/** Сумма оплаты из параметров платежа */
	Amount: number;
	/** Валюта: RUB/USD/EUR/GBP из параметров платежа (см. [справочник](#spisok-valyut)) */
	Currency: Currency;
	/** Сумма списания */
	PaymentAmount: string;
	/** Валюта списания */
	PaymentCurrency: Currency;
	/** Дата/время создания платежа во временной зоне UTC */
	DateTime: string;
	/** Уникальный идентификатор карты в системе CloudPayments */
	CardId?: string;
	/** Первые 6 цифр номера карты */
	CardFirstSix: string;
	/** Последние 4 цифры номера карты */
	CardLastFour: string;
	/** Платежная система карты: Visa, Mastercard, Maestro или "МИР" */
	CardType: string;
	/** Срок действия карты в формате MM/YY */
	CardExpDate: string;
	/** Признак тестового режима */
	TestMode: 0 | 1;
	/** Статус платежа после авторизации: `Completed` — для одностадийных платежей, `Authorized` — для двухстадийных */
	Status: TransactionStatus;
	/** Тип операции: Payment/CardPayout (см. [справочник](#tipy-operatsiy)) */
	OperationType: OperationType;
	/** Идентификатор банка-эквайера */
	GatewayName: string;
	/** Номер заказа из параметров платежа */
	InvoiceId?: string;
	/** Идентификатор пользователя из параметров платежа */
	AccountId?: string;
	/** Идентификатор подписки (для рекуррентных платежей) */
	SubscriptionId?: string;
	/** Имя держателя карты */
	Name?: string;
	/** E-mail адрес плательщика */
	Email?: string;
	/** IP-адрес плательщика */
	IpAddress?: string;
	/** Двухбуквенный код страны нахождения плательщика по [ISO3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) */
	IpCountry?: string;
	/** Город нахождения плательщика */
	IpCity?: string;
	/** Регион нахождения плательщика */
	IpRegion?: string;
	/** Округ нахождения плательщика */
	IpDistrict?: string;
	/** Широта нахождения плательщика */
	IpLatitude?: string;
	/** Долгота нахождения плательщика */
	IpLongitude?: string;
	/** Название банка-эмитента карты */
	Issuer?: string;
	/** Двухбуквенный код страны эмитента карты по [ISO3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) */
	IssuerBankCountry?: string;
	/** Назначение оплаты из параметров платежа */
	Description?: string;
	/** Код авторизации */
	AuthCode?: string;
	/** Произвольный набор параметров, переданных в транзакцию */
	Data?: Record<string, unknown>;
	/** Токен карты для повторных платежей без ввода реквизитов */
	Token?: string;
	/** Значение общей комиссии */
	TotalFee?: number;
	/** Тип карточного продукта */
	CardProduct?: string;
	/** Метод оплаты (например, T-Pay) */
	PaymentMethod?: string;
	/** Номер первой неуспешной транзакции */
	FallBackScenarioDeclinedTransactionId?: number;
	/** Уникальный номер банковской транзакции, который назначается обслуживающим банком */
	Rrn?: string;
	/** Кастомные поля, которые передает мерчант в запросе оплаты */
	CustomFields?: unknown[];
	/** Расчетная сумма по НДС, начисленного на комиссию Системы. Параметр передается с 29.04.2026 */
	VatAboveTotalFee?: number;
	/** Сумма вознаграждения Агента ТСП. Значение заполняется для СБП платежей. Параметр передается с 29.04.2026 */
	ProcessorAndPartnerFee?: number;
	/** Расчетная сумма НДС с вознаграждения платёжного агента. Значение заполняется для СБП платежей. Параметр передается с 29.04.2026 */
	VatWithinProcessorFee?: number;
}

/**
 * Payload уведомления Fail.
 * Выполняется в случае, если оплата была отклонена, и используется для анализа количества и причин отказов.
 * @see https://developers.cloudpayments.ru/#fail
 */
export interface FailNotificationPayload {
	/** Номер транзакции в системе */
	TransactionId: number;
	/** Сумма оплаты из параметров платежа */
	Amount: number;
	/** Валюта: RUB/USD/EUR/GBP из параметров платежа (см. [справочник](#spisok-valyut)) */
	Currency: Currency;
	/** Сумма списания */
	PaymentAmount: string;
	/** Валюта списания */
	PaymentCurrency: Currency;
	/** Дата/время создания платежа во временной зоне UTC */
	DateTime: string;
	/** Уникальный идентификатор карты в системе CloudPayments */
	CardId?: string;
	/** Первые 6 цифр номера карты */
	CardFirstSix: string;
	/** Последние 4 цифры номера карты */
	CardLastFour: string;
	/** Платежная система карты: Visa, Mastercard, Maestro или "МИР" */
	CardType: string;
	/** Срок действия карты в формате MM/YY */
	CardExpDate: string;
	/** Признак тестового режима */
	TestMode: 0 | 1;
	/** Причина отказа */
	Reason: string;
	/** Код ошибки (см. [справочник](#kody-oshibok)) */
	ReasonCode: number;
	/** Тип операции: Payment/Refund/CardPayout (см. [справочник](#tipy-operatsiy)) */
	OperationType: OperationType;
	/** Номер заказа из параметров платежа */
	InvoiceId?: string;
	/** Идентификатор пользователя из параметров платежа */
	AccountId?: string;
	/** Идентификатор подписки (для рекуррентных платежей) */
	SubscriptionId?: string;
	/** Имя держателя карты */
	Name?: string;
	/** E-mail адрес плательщика */
	Email?: string;
	/** IP-адрес плательщика */
	IpAddress?: string;
	/** Двухбуквенный код страны нахождения плательщика по [ISO3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) */
	IpCountry?: string;
	/** Город нахождения плательщика */
	IpCity?: string;
	/** Регион нахождения плательщика */
	IpRegion?: string;
	/** Округ нахождения плательщика */
	IpDistrict?: string;
	/** Широта нахождения плательщика */
	IpLatitude?: string;
	/** Долгота нахождения плательщика */
	IpLongitude?: string;
	/** Название банка-эмитента карты */
	Issuer?: string;
	/** Двухбуквенный код страны эмитента карты по [ISO3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) */
	IssuerBankCountry?: string;
	/** Назначение оплаты из параметров платежа */
	Description?: string;
	/** Произвольный набор параметров, переданных в транзакцию */
	Data?: Record<string, unknown>;
	/** Токен карты для повторных платежей без ввода реквизитов */
	Token?: string;
	/** Метод оплаты (например, T-Pay) */
	PaymentMethod?: string;
	/** Номер первой неуспешной транзакции */
	FallBackScenarioDeclinedTransactionId?: number;
	/** Уникальный номер банковской транзакции, который назначается обслуживающим банком */
	Rrn?: string;
	/** Кастомные поля, которые передает мерчант в запросе оплаты */
	CustomFields?: unknown[];
	/** Дата и время, когда можно повторить попытку списания. Параметр передаётся с 27.05.2026 */
	RetryAfter?: string;
	/** Детали ошибки, возникшей при попытке списания. Параметр передаётся с 27.05.2026 */
	ProviderMessage?: string;
}

/**
 * Payload уведомления Confirm.
 * Выполняется после подтверждения платежа, проведенного по [двухстадийной](#shemy-provedeniya-platezha) схеме.
 * @see https://developers.cloudpayments.ru/#confirm
 */
export interface ConfirmNotificationPayload {
	/** Номер транзакции в системе */
	TransactionId: number;
	/** Сумма оплаты из параметров платежа */
	Amount: number;
	/** Валюта: RUB/USD/EUR/GBP из параметров платежа (см. [справочник](#spisok-valyut)) */
	Currency: Currency;
	/** Сумма списания */
	PaymentAmount: string;
	/** Валюта списания */
	PaymentCurrency: Currency;
	/** Дата/время создания платежа во временной зоне UTC */
	DateTime: string;
	/** Первые 6 цифр номера карты */
	CardFirstSix: string;
	/** Последние 4 цифры номера карты */
	CardLastFour: string;
	/** Платежная система карты: Visa, Mastercard, Maestro или "МИР" */
	CardType: string;
	/** Срок действия карты в формате MM/YY */
	CardExpDate: string;
	/** Признак тестового режима */
	TestMode: 0 | 1;
	/** Статус платежа после авторизации: Completed */
	Status: TransactionStatus;
	/** Номер заказа из параметров платежа */
	InvoiceId?: string;
	/** Идентификатор пользователя из параметров платежа */
	AccountId?: string;
	/** Идентификатор подписки (для рекуррентных платежей) */
	SubscriptionId?: string;
	/** Имя держателя карты */
	Name?: string;
	/** E-mail адрес плательщика */
	Email?: string;
	/** IP-адрес плательщика */
	IpAddress?: string;
	/** Двухбуквенный код страны нахождения плательщика по [ISO3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) */
	IpCountry?: string;
	/** Город нахождения плательщика */
	IpCity?: string;
	/** Регион нахождения плательщика */
	IpRegion?: string;
	/** Округ нахождения плательщика */
	IpDistrict?: string;
	/** Широта нахождения плательщика */
	IpLatitude?: string;
	/** Долгота нахождения плательщика */
	IpLongitude?: string;
	/** Название банка-эмитента карты */
	Issuer?: string;
	/** Двухбуквенный код страны эмитента карты по [ISO3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) */
	IssuerBankCountry?: string;
	/** Назначение оплаты из параметров платежа */
	Description?: string;
	/** Код авторизации */
	AuthCode?: string;
	/** Произвольный набор параметров, переданных в транзакцию */
	Data?: Record<string, unknown>;
	/** Токен карты для повторных платежей без ввода реквизитов */
	Token?: string;
	/** Метод оплаты (например, T-Pay) */
	PaymentMethod?: string;
	/** Уникальный номер банковской транзакции, который назначается обслуживающим банком */
	Rrn?: string;
}

/**
 * Payload уведомления Refund.
 * Выполняется в случае, если платеж был возвращен (полностью или частично) по вашей инициативе через [API](#vozvrat-deneg) или личный кабинет.
 * @see https://developers.cloudpayments.ru/#refund
 */
export interface RefundNotificationPayload {
	/** Номер транзакции возврата в системе */
	TransactionId: number;
	/** Номер оригинальной транзакции оплаты в системе */
	PaymentTransactionId: number;
	/** Сумма возврата в валюте платежа */
	Amount: number;
	/** Дата/время возврата по временной зоне UTC */
	DateTime: string;
	/** Тип операции: Refund/CardPayout (см. [справочник](#tipy-operatsiy)) */
	OperationType: OperationType;
	/** Номер заказа оригинальной операции */
	InvoiceId?: string;
	/** Идентификатор пользователя оригинальной операции */
	AccountId?: string;
	/** E-mail адрес плательщика */
	Email?: string;
	/** Произвольный набор параметров, переданных в транзакцию */
	Data?: Record<string, unknown>;
	/** Уникальный номер банковской транзакции, который назначается обслуживающим банком */
	Rrn?: string;
	/** Кастомные поля, которые передает мерчант в запросе оплаты */
	CustomFields?: unknown[];
}

/**
 * Payload уведомления Recurrent.
 * Выполняется в случае, если статус подписки на рекуррентный платеж был изменен.
 * @see https://developers.cloudpayments.ru/#recurrent
 */
export interface RecurrentNotificationPayload {
	/** Идентификатор подписки */
	Id: string;
	/** Идентификатор пользователя */
	AccountId: string;
	/** Назначение платежа в свободной форме */
	Description: string;
	/** E-mail плательщика */
	Email: string;
	/** Сумма платежа */
	Amount: number;
	/** Валюта: RUB/USD/EUR/GBP из параметров платежа (см. [справочник](#spisok-valyut)) */
	Currency: Currency;
	/** Если значение `true` — платеж будет выполнен по [двухстадийной схеме](#shemy-provedeniya-platezha) */
	RequireConfirmation: boolean;
	/** Дата и время первого платежа по плану во временной зоне UTC */
	StartDate: string;
	/** Интервал. Возможные значения: Week, Month */
	Interval: string;
	/** Период. В комбинации с интервалом 1 Month значит раз в месяц, а 2 Week — раз в две недели */
	Period: number;
	/** [Статусы подписок](#statusy-podpisok-rekurrent) */
	Status: SubscriptionStatus;
	/** Количество успешных платежей */
	SuccessfulTransactionsNumber: number;
	/** Количество неуспешных платежей (обнуляется после каждого успешного) */
	FailedTransactionsNumber: number;
	/** Максимальное количество платежей в подписке */
	MaxPeriods?: number;
	/** Дата и время последнего успешного платежа во временной зоне UTC */
	LastTransactionDate?: string;
	/** Дата и время следующего платежа во временной зоне UTC */
	NextTransactionDate?: string;
}

/**
 * Payload уведомления Cancel.
 * Выполняется в случае, если платеж был отменен по вашей инициативе через [API](#api) или личный кабинет.
 * @see https://developers.cloudpayments.ru/#cancel
 */
export interface CancelNotificationPayload {
	/** Номер отмененной транзакции в системе */
	TransactionId: number;
	/** Сумма отмененной транзакции в валюте платежа */
	Amount: number;
	/** Дата/время отмены по временной зоне UTC */
	DateTime: string;
	/** Номер заказа отмененной операции */
	InvoiceId?: string;
	/** Идентификатор пользователя отмененной операции */
	AccountId?: string;
	/** E-mail адрес плательщика */
	Email?: string;
	/** Произвольный набор параметров, переданных в транзакцию */
	Data?: Record<string, unknown>;
	/** Уникальный номер банковской транзакции, который назначается обслуживающим банком */
	Rrn?: string;
}

/**
 * Payload уведомления Receipt.
 * Выполняется после выдачи кассового чека.
 * @see https://developers.cloudkassir.ru/#receipt
 */
export interface ReceiptNotificationPayload {
	/** Уникальный идентификатор чека */
	Id: string;
	/** Номер чека */
	DocumentNumber: number;
	/** Номер смены */
	SessionNumber: number;
	/** Номер чека в смене */
	Number: number;
	/** Фискальный признак документа */
	FiscalSign: string;
	/** Заводской номер ККТ */
	DeviceNumber: string;
	/** Регистрационный номер ККТ */
	RegNumber: string;
	/** Номер фискального накопителя */
	FiscalNumber: string;
	/** ИНН */
	Inn: string;
	/** Признак расчета, см. [справочник](#type) */
	Type: KktReceiptType;
	/** Наименование оператора фискальных данных */
	Ofd: string;
	/** URL адрес с копией чека */
	Url: string;
	/** URL адрес с QR кодом для проверки чека в ФНС */
	QrCodeUrl: string;
	/** Идентификатор транзакции */
	TransactionId?: number;
	/** Сумма чека */
	Amount: number;
	/** Дата/время выдачи чека во временной зоне UTC */
	DateTime: string;
	/** Номер заказа */
	InvoiceId?: string;
	/** Идентификатор пользователя */
	AccountId?: string;
	/** Состав чека */
	Receipt: KktReceipt;
	/** Место осуществления расчетов */
	CalculationPlace?: string;
	/** Имя кассира */
	CashierName?: string;
	/** место нахождения (установки) ккм */
	SettlePlace?: string;
}

/** Union всех входящих webhook payload-ов. Тип определяется endpoint-ом. */
export type AnyWebhookPayload = CheckNotificationPayload | PayNotificationPayload | FailNotificationPayload | ConfirmNotificationPayload | RefundNotificationPayload | RecurrentNotificationPayload | CancelNotificationPayload | ReceiptNotificationPayload;
