#!/usr/bin/env bun
/**
 * Генерирует src/_generated/ из specs/ir.json:
 *   - meta.ts          — package metadata, BASE_URL и docs sha256
 *   - handbooks.ts     — типы + мап-объекты для справочников (статусы, коды ошибок, валюты, …)
 *   - endpoints.ts     — Request-типы и URL-константы для всех API-методов
 *   - webhook-payloads.ts — payload-типы для входящих уведомлений
 *   - index.ts         — re-export всего
 */
import { existsSync } from "node:fs";
import { mkdir, rm, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { DOCS_SOURCES, type DocsSourceName } from "./docs-sources.js";
import type { Group, IR, Param, Table } from "./parse.js";

const OUT_DIR = resolve(import.meta.dir, "..", "src", "_generated");

const HEADER = `/**
 * AUTO-GENERATED by tools/gen.ts from specs/ir.json.
 * Do not edit directly — run \`bun run gen\` instead.
 */
`;

/* ──────────────────────────── Config ──────────────────────────── */

type HandbookAs = "stringUnion" | "numberUnion" | "stringEnum" | "numberEnum";

interface HandbookSpec {
	anchor: string;
	name: string;
	valueCol: string;
	labelCol: string;
	as: HandbookAs;
}

const HANDBOOKS: HandbookSpec[] = [
	{
		anchor: "statusy-operatsiy",
		name: "TransactionStatus",
		valueCol: "Статус",
		labelCol: "Описание",
		as: "stringUnion",
	},
	{
		anchor: "statusy-podpisok-rekurrent",
		name: "SubscriptionStatus",
		valueCol: "Статус",
		labelCol: "Описание",
		as: "stringUnion",
	},
	{
		anchor: "spisok-valyut",
		name: "Currency",
		valueCol: "Код",
		labelCol: "Название",
		as: "stringUnion",
	},
	{
		anchor: "cultures",
		name: "CultureName",
		valueCol: "Код",
		labelCol: "Язык",
		as: "stringUnion",
	},
	{
		anchor: "tipy-uvedomleniy",
		name: "NotificationType",
		valueCol: "Код",
		labelCol: "Название",
		as: "stringUnion",
	},
	{
		anchor: "tipy-operatsiy",
		name: "OperationType",
		valueCol: "Код",
		labelCol: "Название",
		as: "stringUnion",
	},
	{
		anchor: "kody-oshibok",
		name: "ReasonCode",
		valueCol: "Код",
		labelCol: "Название",
		as: "numberUnion",
	},
	{
		anchor: "operatory-fiskalnyh-dannyh",
		name: "FiscalDataOperator",
		valueCol: "Код",
		labelCol: "Название оператора",
		as: "stringUnion",
	},
	{
		anchor: "kody-vremennyh-zon",
		name: "TimeZoneCode",
		valueCol: "Код",
		labelCol: "Название",
		as: "stringUnion",
	},
	{
		anchor: "kody-obrabotki-otvetov-na-check-uvedomlenie",
		name: "CheckResponseCode",
		valueCol: "Код",
		labelCol: "Название",
		as: "numberUnion",
	},
];

interface EndpointAlias {
	source?: DocsSourceName;
	sectionAnchor?: string;
	anchor: string;
	module:
		| "payments"
		| "subscriptions"
		| "orders"
		| "settings"
		| "escrow"
		| "tPay"
		| "sbp"
		| "sberPay"
		| "kkt";
	methodName: string;
	/** URL находится в дочернем блоке endpoint-группы. */
	urlAnchor?: string;
	/** Параметры находятся в другом блоке той же секции. */
	requestGroupAnchor?: string;
	requestAnchor?: string;
	/** Документация содержит только JSON-пример запроса, без таблицы параметров. */
	paramsOverride?: Param[];
	/** Если у endpoint-а несколько URL, создаём несколько методов, выбирая URL по label-подстроке. */
	splitByUrlLabel?: Array<{ match: string; methodName: string }>;
	/** По-умолчанию берём url[0]. Этот индекс используется если splitByUrlLabel не задан и нужен не первый URL. */
	urlIndex?: number;
}

const ENDPOINT_ALIASES: EndpointAlias[] = [
	// /Escrow/GetEscrowInfo
	{
		sectionAnchor: "bezopasnaya-sdelka",
		anchor: "metod-dlya-polucheniya-informatsii-po-bs-dlya-oboih-tipov-sdelki-n-1-i-1-n",
		module: "escrow",
		methodName: "getInfo",
		paramsOverride: [
			{
				name: "EscrowAccumulationIds",
				type: "Array string",
				required: true,
				description: "Идентификаторы безопасных сделок",
			},
		],
	},

	// /test
	{ anchor: "testovyy-metod", module: "payments", methodName: "test" },

	// /payments/cards/{charge|auth}
	{
		anchor: "oplata-po-kriptogramme",
		module: "payments",
		methodName: "chargeCryptogram",
		splitByUrlLabel: [
			{ match: "одностадийн", methodName: "chargeCryptogram" },
			{ match: "двухстадийн", methodName: "authCryptogram" },
		],
	},
	// /payments/cards/post3ds
	{ anchor: "primer-formy", module: "payments", methodName: "post3ds" },

	// /payments/tokens/{charge|auth}
	{
		anchor: "oplata-po-tokenu-rekarring",
		module: "payments",
		methodName: "chargeToken",
		splitByUrlLabel: [
			{ match: "одностадийн", methodName: "chargeToken" },
			{ match: "двухстадийн", methodName: "authToken" },
		],
	},

	// /payments/confirm, /void, /refund
	{ anchor: "podtverzhdenie-oplaty", module: "payments", methodName: "confirm" },
	{ anchor: "otmena-oplaty", module: "payments", methodName: "void" },
	{ anchor: "vozvrat-deneg", module: "payments", methodName: "refund" },

	// /payments/cards/topup, /payments/tokens/topup, /payments/qr/sbp/topup
	{ anchor: "vyplata-po-kriptogramme", module: "payments", methodName: "payoutCryptogram" },
	{ anchor: "vyplata-po-tokenu", module: "payments", methodName: "payoutToken" },
	{ anchor: "vyplata-po-sbp", module: "payments", methodName: "payoutSbp" },

	// /payments/get, /payments/list, /payments/list/v2, /payments/claims
	{ anchor: "prosmotr-tranzaktsii", module: "payments", methodName: "get" },
	{
		anchor: "proverka-statusa-platezha",
		module: "payments",
		methodName: "findLegacy",
		splitByUrlLabel: [
			{ match: "старого", methodName: "findLegacy" },
			{ match: "нового", methodName: "find" },
		],
	},
	{ anchor: "vygruzka-spiska-tranzaktsiy", module: "payments", methodName: "listByDay" },
	{
		anchor: "vygruzka-spiska-tranzaktsiy-za-proizvolnyy-period",
		module: "payments",
		methodName: "listByPeriod",
	},
	{
		anchor: "vygruzka-spiska-pretenziy-za-proizvolnyy-period",
		module: "payments",
		methodName: "listClaimsByPeriod",
	},
	{ anchor: "vygruzka-tokenov", module: "payments", methodName: "listTokens" },

	// /subscriptions/*
	{
		anchor: "sozdanie-podpiski-na-rekurrentnye-platezhi",
		module: "subscriptions",
		methodName: "create",
	},
	{ anchor: "zapros-informatsii-o-podpiske", module: "subscriptions", methodName: "get" },
	{ anchor: "poisk-podpisok", module: "subscriptions", methodName: "findByAccount" },
	{
		anchor: "izmenenie-podpiski-na-rekurrentnye-platezhi",
		module: "subscriptions",
		methodName: "update",
	},
	{
		anchor: "otmena-podpiski-na-rekurrentnye-platezhi",
		module: "subscriptions",
		methodName: "cancel",
	},

	// /orders/*
	{ anchor: "sozdanie-scheta-dlya-otpravki-po-pochte", module: "orders", methodName: "create" },
	{ anchor: "otmena-sozdannogo-scheta", module: "orders", methodName: "cancel" },

	// /site/notifications/*
	{ anchor: "prosmotr-nastroek-uvedomleniy", module: "settings", methodName: "getNotification" },
	{
		anchor: "izmenenie-nastroek-uvedomleniy",
		module: "settings",
		methodName: "updateNotification",
	},

	// Альтернативные способы оплаты
	{
		sectionAnchor: "t-pay",
		anchor: "poluchenie-ssylki-dlya-oplaty",
		urlAnchor: "adres-metoda",
		requestAnchor: "parametry-zaprosa",
		module: "tPay",
		methodName: "createLink",
	},
	{
		sectionAnchor: "t-pay",
		anchor: "poluchenie-qr-koda-dlya-oplaty",
		urlAnchor: "opisanie-2",
		requestGroupAnchor: "poluchenie-ssylki-dlya-oplaty",
		requestAnchor: "parametry-zaprosa",
		module: "tPay",
		methodName: "createQrImage",
	},
	{
		sectionAnchor: "sbp",
		anchor: "sbp-poluchenie-ssylki-dlya-oplaty",
		urlAnchor: "adres-metoda",
		requestAnchor: "sbp-parametry-zaprosa",
		module: "sbp",
		methodName: "createLink",
	},
	{
		sectionAnchor: "sbp",
		anchor: "sbp-poluchenie-qr-koda-dlya-oplaty",
		urlAnchor: "adres-metoda-2",
		requestGroupAnchor: "sbp-poluchenie-ssylki-dlya-oplaty",
		requestAnchor: "sbp-parametry-zaprosa",
		module: "sbp",
		methodName: "createQrImage",
	},
	{
		sectionAnchor: "sbp",
		anchor: "spisok-uchastnikov-sbp",
		urlAnchor: "adres-metoda-3",
		requestAnchor: "parametry-zaprosa-2",
		module: "sbp",
		methodName: "listBanks",
	},
	{
		sectionAnchor: "sberpay",
		anchor: "sberpay-poluchenie-ssylki-dlya-oplaty",
		urlAnchor: "adres-metoda",
		requestAnchor: "sberpay-parametry-zaprosa",
		module: "sberPay",
		methodName: "createLink",
	},
	{
		sectionAnchor: "sberpay",
		anchor: "sberpay-poluchenie-qr-koda-dlya-oplaty",
		urlAnchor: "adres-metoda-2",
		requestGroupAnchor: "sberpay-poluchenie-ssylki-dlya-oplaty",
		requestAnchor: "sberpay-parametry-zaprosa",
		module: "sberPay",
		methodName: "createQrImage",
	},

	// CloudKassir /kkt/*
	{ source: "cloudkassir", anchor: "fiskalizatsiya-kassy", module: "kkt", methodName: "fiscalize" },
	{
		source: "cloudkassir",
		anchor: "formirovanie-kassovogo-cheka",
		module: "kkt",
		methodName: "submitReceipt",
	},
	{
		source: "cloudkassir",
		anchor: "zapros-statusa-cheka",
		module: "kkt",
		methodName: "getReceiptStatus",
	},
	{
		source: "cloudkassir",
		anchor: "poluchenie-dannyh-cheka",
		module: "kkt",
		methodName: "getReceipt",
	},
	{
		source: "cloudkassir",
		anchor: "proverka-koda-markirovki",
		module: "kkt",
		methodName: "validateMarkCode",
	},
	{
		source: "cloudkassir",
		anchor: "massovaya-proverka-kodov-markirovki",
		module: "kkt",
		methodName: "validateMarkCodes",
	},
	{
		source: "cloudkassir",
		anchor: "formirovanie-cheka-korrektsii",
		module: "kkt",
		methodName: "submitCorrectionReceipt",
	},
	{
		source: "cloudkassir",
		anchor: "zapros-statusa-cheka-korrektsii",
		module: "kkt",
		methodName: "getCorrectionReceiptStatus",
	},
	{
		source: "cloudkassir",
		anchor: "poluchenie-dannyh-cheka-korrektsii",
		module: "kkt",
		methodName: "getCorrectionReceipt",
		paramsOverride: [
			{ name: "Id", type: "Строка", required: true, description: "Идентификатор чека" },
		],
	},
	{
		source: "cloudkassir",
		anchor: "izmenenie-sostoyaniya-kassy",
		module: "kkt",
		methodName: "updateCashRegisterState",
	},
	{
		source: "cloudkassir",
		anchor: "poluchenie-dannyh-kassy",
		module: "kkt",
		methodName: "getCashRegisterState",
	},
	{
		source: "cloudkassir",
		anchor: "preduprezhdeniya-po-kassam",
		module: "kkt",
		methodName: "listCashRegisterWarnings",
	},
];

/** anchor из раздела уведомлений → идентификатор payload-типа */
const WEBHOOK_PAYLOADS = [
	{ source: "cloudpayments", anchor: "check", type: "Check", name: "CheckNotificationPayload" },
	{ source: "cloudpayments", anchor: "pay", type: "Pay", name: "PayNotificationPayload" },
	{ source: "cloudpayments", anchor: "fail", type: "Fail", name: "FailNotificationPayload" },
	{
		source: "cloudpayments",
		anchor: "confirm",
		type: "Confirm",
		name: "ConfirmNotificationPayload",
	},
	{ source: "cloudpayments", anchor: "refund", type: "Refund", name: "RefundNotificationPayload" },
	{
		source: "cloudpayments",
		anchor: "recurrent",
		type: "Recurrent",
		name: "RecurrentNotificationPayload",
	},
	{ source: "cloudpayments", anchor: "cancel", type: "Cancel", name: "CancelNotificationPayload" },
	{ source: "cloudkassir", anchor: "receipt", type: "Receipt", name: "ReceiptNotificationPayload" },
] as const;

const BASE_URL_PROD = "https://api.cloudpayments.ru";
/** Sandbox-режим у CP — не отдельный домен, а тестовые Public ID/Secret, см. #testirovanie. */
const BASE_URL_EU = "https://api.cloudpayments.eu";
const BASE_URL_KZ = "https://api.cp.kz";
const DOCS_URL = "https://developers.cloudpayments.ru";
const KKT_DOCS_URL = "https://developers.cloudkassir.ru";

/* ──────────────────────── Helpers: IR lookup ──────────────────────── */

type IRBySource = Record<DocsSourceName, IR>;

async function loadIRs(): Promise<IRBySource> {
	const entries = await Promise.all(
		Object.values(DOCS_SOURCES).map(async (source) => {
			const raw = await Bun.file(source.irPath).text();
			return [source.name, JSON.parse(raw) as IR] as const;
		}),
	);
	return Object.fromEntries(entries) as IRBySource;
}

function findGroupDeep(ir: IR, anchor: string, sectionAnchor?: string): Group | null {
	for (const s of ir.sections) {
		if (sectionAnchor && s.anchor !== sectionAnchor) continue;
		for (const g of s.groups) {
			if (g.anchor === anchor) return g;
			for (const sg of g.subgroups) if (sg.anchor === anchor) return sg;
		}
	}
	return null;
}

/* ──────────────────────── Helpers: type mapping ──────────────────────── */

function tsTypeFor(param: Param): string {
	const t = param.type.trim().toLowerCase();
	if (!t) return "unknown";
	// date-format strings — "yyyy-MM-dd", "yyyy-MM-dd HH:mm:ss", ISO-шаблоны etc. → string
	if (/^y{2,4}[-./]/.test(t) || /datetime/.test(t) || /^date\b/.test(t)) return "string";
	if (/^string/.test(t) || /^guid\b/.test(t) || /^url\b/.test(t) || /^строк/u.test(t))
		return "string";
	if (/^(long|int|integer|decimal|float|double|number)/.test(t) || /^(число|целое число)/u.test(t))
		return "number";
	if (/^bit\b/.test(t)) return "0 | 1";
	if (/^(bool|boolean)/.test(t) || /^булев/u.test(t)) return "boolean";
	if (/^(array|list).*string/.test(t) || /^массив строк/u.test(t)) return "string[]";
	if (/^json/.test(t)) return inferObjectType(param);
	if (/^object/.test(t)) return inferObjectType(param);
	if (/^(array|list)/.test(t) || /^массив/u.test(t)) return "unknown[]";
	return "unknown";
}

function inferObjectType(param: Param): string {
	const name = param.name.toLowerCase();
	if (name === "payer") return "Payer";
	if (name === "receiver") return "Payer";
	if (name === "receipt") return "KktReceipt";
	if (name === "customerreceipt") return "KktReceipt";
	if (name === "correctionreceiptdata") return "KktCorrectionReceiptData";
	return "Record<string, unknown>";
}

function escapeJsDoc(text: string): string {
	return text.replace(/\*\//g, "*\\/");
}

/** Готовит JSDoc-комментарий: первая строка short-description, далее блоки если нужны. */
function jsDoc(lines: string[], indent = ""): string {
	const trimmed = lines.map((l) => l.trim()).filter(Boolean);
	if (trimmed.length === 0) return "";
	if (trimmed.length === 1) return `${indent}/** ${escapeJsDoc(trimmed[0] as string)} */\n`;
	const body = trimmed
		.flatMap((l) => l.split("\n"))
		.map((l) => `${indent} * ${escapeJsDoc(l)}`)
		.join("\n");
	return `${indent}/**\n${body}\n${indent} */\n`;
}

/** Безопасное имя поля — если содержит тире или начинается с цифры, квотим. */
function fieldName(name: string): string {
	if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) return name;
	return JSON.stringify(name);
}

/* ──────────────────────── meta.ts ──────────────────────── */

function writeMeta(irs: IRBySource): string {
	return `${HEADER}
import packageMetadata from "../../package.json" with { type: "json" };

export const CP_SDK_NAME = packageMetadata.name;
export const CP_SDK_VERSION = packageMetadata.version;

export const CP_BASE_URL = ${JSON.stringify(BASE_URL_PROD)} as const;
export const CP_BASE_URL_EU = ${JSON.stringify(BASE_URL_EU)} as const;
export const CP_BASE_URL_KZ = ${JSON.stringify(BASE_URL_KZ)} as const;
export const CP_DOCS_URL = ${JSON.stringify(DOCS_URL)} as const;
export const CLOUDKASSIR_DOCS_URL = ${JSON.stringify(KKT_DOCS_URL)} as const;

export const CP_SDK_DOCS_SHA256 = ${JSON.stringify(irs.cloudpayments.source.htmlSha256)} as const;
export const CLOUDKASSIR_SDK_DOCS_SHA256 = ${JSON.stringify(irs.cloudkassir.source.htmlSha256)} as const;
`;
}

/* ──────────────────────── handbooks.ts ──────────────────────── */

function writeHandbooks(ir: IR): string {
	const parts: string[] = [HEADER];
	for (const spec of HANDBOOKS) {
		const group = findGroupDeep(ir, spec.anchor);
		if (!group) {
			throw new Error(`Handbook not found in IR: ${spec.anchor}`);
		}
		const table = group.tables[0];
		if (!table) {
			throw new Error(`Handbook has no tables in IR: ${spec.anchor}`);
		}
		parts.push(renderHandbook(spec, table, group.title));
	}
	return parts.join("\n");
}

function renderHandbook(spec: HandbookSpec, table: Table, sectionTitle: string): string {
	const allRows = table.rows
		.map((row) => ({
			value: (row[spec.valueCol] ?? "").trim(),
			label: (row[spec.labelCol] ?? "").trim(),
			extra: Object.fromEntries(
				table.headers
					.filter((h) => h !== spec.valueCol && h !== spec.labelCol)
					.map((h) => [h, (row[h] ?? "").trim()]),
			) as Record<string, string>,
		}))
		.filter((r) => r.value !== "");
	// Дедупликация по value: например, один TZ-код CET у разных стран.
	const seen = new Set<string>();
	const rows: typeof allRows = [];
	for (const r of allRows) {
		if (seen.has(r.value)) continue;
		seen.add(r.value);
		rows.push(r);
	}

	const isNumeric = spec.as === "numberUnion" || spec.as === "numberEnum";
	const quote = (v: string): string => (isNumeric ? v : JSON.stringify(v));
	const values = rows.map((r) => quote(r.value)).join(" | ");
	const typeDecl = values.length > 0 ? values : "never";

	const jsdoc = jsDoc([sectionTitle, `@see ${DOCS_URL}/#${spec.anchor}`]);

	const out: string[] = [];
	out.push(jsdoc);
	out.push(`export type ${spec.name} = ${typeDecl};\n`);

	// Array литерал всех значений
	const arrayName = `${pascalToScreamingSnake(spec.name)}_VALUES`;
	out.push(jsDoc([`Все значения ${spec.name}.`]));
	out.push(
		`export const ${arrayName}: readonly ${spec.name}[] = [${rows
			.map((r) => quote(r.value))
			.join(", ")}] as const;\n`,
	);

	// Map: value → label
	const labelsMap = `${toCamelLower(spec.name)}Labels`;
	const labelEntries = rows
		.map((r) => `\t[${quote(r.value)}]: ${JSON.stringify(r.label)},`)
		.join("\n");
	out.push(jsDoc([`Человекочитаемые названия ${spec.name}.`]));
	out.push(`export const ${labelsMap}: Record<${spec.name}, string> = {\n${labelEntries}\n};\n`);

	// Дополнительные поля (если есть другие колонки помимо value/label)
	if (rows[0] && Object.keys(rows[0].extra).length > 0) {
		const extraMap = `${toCamelLower(spec.name)}Info`;
		const extraKeys = Object.keys(rows[0].extra);
		const infoType = `{ label: string; ${extraKeys.map((k) => `${fieldName(toCamelLower(k))}: string;`).join(" ")} }`;
		const entries = rows
			.map((r) => {
				const extras = Object.entries(r.extra)
					.map(([k, v]) => `${fieldName(toCamelLower(k))}: ${JSON.stringify(v)}`)
					.join(", ");
				return `\t[${quote(r.value)}]: { label: ${JSON.stringify(r.label)}, ${extras} },`;
			})
			.join("\n");
		out.push(jsDoc([`Полная информация по ${spec.name} (label + метаданные).`]));
		out.push(`export const ${extraMap}: Record<${spec.name}, ${infoType}> = {\n${entries}\n};\n`);
	}
	return out.join("");
}

function toCamelLower(pascal: string): string {
	return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

function pascalToScreamingSnake(pascal: string): string {
	return pascal.replace(/([a-z])([A-Z])/g, "$1_$2").toUpperCase();
}

/* ──────────────────────── endpoints.ts ──────────────────────── */

interface ResolvedEndpoint {
	alias: EndpointAlias;
	group: Group;
	params: Param[];
	docsUrl: string;
	urls: { url: string; label: string; methodName: string }[];
}

function resolveEndpoints(irs: IRBySource): ResolvedEndpoint[] {
	const out: ResolvedEndpoint[] = [];
	for (const alias of ENDPOINT_ALIASES) {
		const sourceName = alias.source ?? "cloudpayments";
		const ir = irs[sourceName];
		const group = findGroupDeep(ir, alias.anchor, alias.sectionAnchor);
		if (!group) {
			throw new Error(`Endpoint alias not found in ${sourceName} IR: ${alias.anchor}`);
		}
		const urlGroup = alias.urlAnchor
			? group.subgroups.find((candidate) => candidate.anchor === alias.urlAnchor)
			: group;
		if (!urlGroup) {
			throw new Error(`Endpoint URL block not found for ${alias.anchor}: ${alias.urlAnchor}`);
		}
		const requestParent = alias.requestGroupAnchor
			? findGroupDeep(ir, alias.requestGroupAnchor, alias.sectionAnchor)
			: group;
		if (!requestParent) {
			throw new Error(`Endpoint request group not found for ${alias.anchor}`);
		}
		const requestGroup = alias.requestAnchor
			? requestParent.subgroups.find((candidate) => candidate.anchor === alias.requestAnchor)
			: requestParent;
		if (!requestGroup) {
			throw new Error(
				`Endpoint request block not found for ${alias.anchor}: ${alias.requestAnchor}`,
			);
		}
		const params = alias.paramsOverride ?? requestGroup.params;
		if (urlGroup.urls.length === 0) {
			throw new Error(`Endpoint ${alias.anchor} has no URLs`);
		}
		const docsUrl = sourceName === "cloudkassir" ? KKT_DOCS_URL : DOCS_URL;

		if (alias.splitByUrlLabel) {
			const resolved: ResolvedEndpoint["urls"] = [];
			for (const split of alias.splitByUrlLabel) {
				const u = urlGroup.urls.find((x) =>
					x.label.toLowerCase().includes(split.match.toLowerCase()),
				);
				if (!u) {
					throw new Error(`Endpoint URL split not matched for ${alias.anchor}: ${split.match}`);
				}
				resolved.push({ url: u.url, label: u.label, methodName: split.methodName });
			}
			out.push({ alias, group, params, docsUrl, urls: resolved });
		} else {
			const idx = alias.urlIndex ?? 0;
			const u = urlGroup.urls[idx];
			if (!u) throw new Error(`Endpoint URL index ${idx} not found for ${alias.anchor}`);
			out.push({
				alias,
				group,
				params,
				docsUrl,
				urls: [{ url: u.url, label: u.label, methodName: alias.methodName }],
			});
		}
	}
	assertEndpointCoverage(irs, out);
	return out;
}

function assertEndpointCoverage(irs: IRBySource, endpoints: ResolvedEndpoint[]): void {
	const covered = new Set(
		endpoints.flatMap((endpoint) => endpoint.urls.map((url) => endpointPath(url.url))),
	);
	const missing: string[] = [];
	for (const [sourceName, ir] of Object.entries(irs) as Array<[DocsSourceName, IR]>) {
		for (const section of ir.sections) {
			for (const group of section.groups) {
				for (const candidate of [group, ...group.subgroups]) {
					for (const url of candidate.urls) {
						if (new URL(url.url).hostname !== "api.cloudpayments.ru") continue;
						if (!covered.has(endpointPath(url.url))) {
							missing.push(`${sourceName}:${section.anchor}:${candidate.anchor} -> ${url.url}`);
						}
					}
				}
			}
		}
	}
	if (missing.length > 0) {
		throw new Error(`Official API endpoints are not exposed by the SDK:\n${missing.join("\n")}`);
	}
}

function writeEndpoints(irs: IRBySource): string {
	const endpoints = resolveEndpoints(irs);
	const parts: string[] = [HEADER];
	parts.push(`import type { Currency, CultureName, FiscalDataOperator } from "./handbooks.js";`);
	parts.push(
		`import type { Payer, CloudPaymentsJsonData, KktCorrectionReceiptData, KktReceipt, KktReceiptType, KktTaxationSystem } from "../models.js";\n`,
	);

	for (const ep of endpoints) {
		parts.push(renderEndpointBlock(ep));
	}

	parts.push(renderEndpointRegistry(endpoints));
	return parts.join("\n");
}

function renderEndpointBlock(ep: ResolvedEndpoint): string {
	const out: string[] = [];
	for (const url of ep.urls) {
		const prefix = pascal(ep.alias.module);
		const typeName = `${prefix}${pascal(url.methodName)}Request`;
		const urlConst = `${pascalToScreamingSnake(ep.alias.module)}_${pascalToScreamingSnake(url.methodName)}_URL`;
		out.push(renderRequestType(typeName, ep));
		out.push(`export const ${urlConst} = ${JSON.stringify(endpointPath(url.url))} as const;\n`);
	}
	return out.join("\n");
}

function endpointPath(rawUrl: string): string {
	const url = new URL(rawUrl);
	return `${decodeURI(url.pathname)}${url.search}`;
}

function renderRequestType(typeName: string, endpoint: ResolvedEndpoint): string {
	const { group, params } = endpoint;
	const out: string[] = [];
	out.push(
		jsDoc([
			group.title,
			group.description.split("\n")[0] ?? "",
			`@see ${endpoint.docsUrl}/#${group.anchor}`,
		]),
	);
	if (params.length === 0) {
		out.push(`export type ${typeName} = Record<string, never>;\n`);
		return out.join("");
	}
	out.push(`export interface ${typeName} {\n`);
	for (const p of params) {
		const parentName = p.name.split(".", 1)[0];
		if (parentName !== p.name && params.some((candidate) => candidate.name === parentName))
			continue;
		const tsType = tsTypeForNamed(p, endpoint.alias);
		const optionalFlag = p.required ? "" : "?";
		const desc = cleanDescription(p.description);
		if (desc) out.push(`\t/** ${escapeJsDoc(desc)} */\n`);
		out.push(`\t${fieldName(p.name)}${optionalFlag}: ${tsType};\n`);
	}
	out.push("}\n");
	return out.join("");
}

function tsTypeForNamed(param: Param, alias?: EndpointAlias): string {
	const name = param.name.toLowerCase();
	// Spec-осведомлённые сужения типов
	if (name === "currency") return "Currency";
	if (name === "culturename" || name === "culture") return "CultureName";
	if (name === "customerreceipt") return "KktReceipt";
	if (name === "correctionreceiptdata") return "KktCorrectionReceiptData";
	if (name === "jsondata" && /^json/i.test(param.type.trim())) return "CloudPaymentsJsonData";
	if (alias?.module === "payments" && alias.methodName === "payoutSbp" && name === "receiver") {
		return "Payer & { Phone: string }";
	}
	if (alias?.module === "kkt" && name === "type") return "KktReceiptType";
	if (alias?.module === "kkt" && name === "taxationsystem") return "KktTaxationSystem[]";
	if (alias?.module === "kkt" && name === "ofd") return "FiscalDataOperator";
	if (alias?.module === "tPay" && name === "scheme") return "0 | 1";
	if (alias?.module === "sbp" && name === "scheme") return '"charge"';
	if (alias?.module === "sberPay" && name === "scheme") return '"charge" | "auth"';
	if (["tPay", "sbp", "sberPay"].includes(alias?.module ?? "") && name === "device") {
		return '"MobileApp" | "DesktopWeb" | "Mobile"';
	}
	if (name === "ttlminutes") return "number | null";
	return tsTypeFor(param);
}

function cleanDescription(desc: string): string {
	return desc.replace(/\s+/g, " ").trim();
}

function pascal(camel: string): string {
	return camel.charAt(0).toUpperCase() + camel.slice(1);
}

function renderEndpointRegistry(endpoints: ResolvedEndpoint[]): string {
	const byModule = new Map<string, Array<{ methodName: string; url: string }>>();
	for (const ep of endpoints) {
		for (const u of ep.urls) {
			const list = byModule.get(ep.alias.module) ?? [];
			list.push({ methodName: u.methodName, url: u.url });
			byModule.set(ep.alias.module, list);
		}
	}

	const out: string[] = [];
	out.push(jsDoc(["Реестр всех API-эндпоинтов, сгенерирован из IR."]));
	out.push("export const ENDPOINTS = {\n");
	for (const [module, methods] of byModule) {
		out.push(`\t${module}: {\n`);
		for (const m of methods) {
			out.push(
				`\t\t${m.methodName}: { url: ${JSON.stringify(endpointPath(m.url))}, method: "POST" as const },\n`,
			);
		}
		out.push("\t},\n");
	}
	out.push("} as const;\n");
	return out.join("");
}

/* ──────────────────────── webhook-payloads.ts ──────────────────────── */

function writeWebhookPayloads(irs: IRBySource): string {
	const parts: string[] = [HEADER];
	parts.push(
		`import type { OperationType, TransactionStatus, SubscriptionStatus, Currency, CultureName } from "./handbooks.js";\n`,
	);
	parts.push(`import type { KktReceipt, KktReceiptType } from "../models.js";\n`);
	parts.push(renderWebhookFieldSchemas(irs));

	for (const spec of WEBHOOK_PAYLOADS) {
		const g = findGroupDeep(irs[spec.source], spec.anchor);
		if (!g) {
			throw new Error(`Webhook payload not found in ${spec.source} IR: ${spec.anchor}`);
		}
		const docsUrl = spec.source === "cloudkassir" ? KKT_DOCS_URL : DOCS_URL;
		parts.push(renderWebhookPayload(spec.name, spec.type, g, docsUrl));
	}

	parts.push(renderWebhookUnion());
	return parts.join("\n");
}

type WebhookFieldKind = "string" | "number" | "bit" | "boolean" | "json-object" | "json-array";

interface WebhookFieldSchema {
	kind: WebhookFieldKind;
	optional: boolean;
}

function renderWebhookFieldSchemas(irs: IRBySource): string {
	const fields = new Map<string, WebhookFieldSchema>();
	const byType: string[] = [];
	for (const spec of WEBHOOK_PAYLOADS) {
		const group = findGroupDeep(irs[spec.source], spec.anchor);
		if (!group) continue;
		const ownFields = new Map<string, WebhookFieldSchema>();
		for (const param of group.params) {
			const kind = webhookFieldKind(tsTypeForWebhook(param, spec.type));
			const optional = !param.required;
			ownFields.set(param.name, { kind, optional });
			const existing = fields.get(param.name);
			if (existing && existing.kind !== kind) {
				throw new Error(
					`Webhook field ${param.name} has conflicting runtime kinds: ${existing.kind} and ${kind}`,
				);
			}
			if (existing) existing.optional &&= optional;
			else fields.set(param.name, { kind, optional });
		}
		byType.push(`\t${spec.type}: ${renderWebhookSchemaObject(ownFields, "\t")},`);
	}

	return `${jsDoc(["Runtime coercion schema для form-urlencoded webhook payload-ов."])}export const WEBHOOK_FIELD_SCHEMAS = ${renderWebhookSchemaObject(fields)} as const;\n\n${jsDoc(["Runtime coercion schemas для конкретных типов webhook payload-ов."])}export const WEBHOOK_FIELD_SCHEMAS_BY_TYPE = {\n${byType.join("\n")}\n} as const;\n`;
}

function renderWebhookSchemaObject(fields: Map<string, WebhookFieldSchema>, indent = ""): string {
	const entries = [...fields]
		.sort(([left], [right]) => left.localeCompare(right))
		.map(
			([name, field]) =>
				`${indent}\t${fieldName(name)}: { kind: ${JSON.stringify(field.kind)}, optional: ${field.optional} },`,
		)
		.join("\n");
	return `{\n${entries}\n${indent}}`;
}

function webhookFieldKind(tsType: string): WebhookFieldKind {
	if (tsType === "number") return "number";
	if (tsType === "0 | 1") return "bit";
	if (tsType === "boolean") return "boolean";
	if (tsType === "Record<string, unknown>" || tsType === "KktReceipt") return "json-object";
	if (tsType === "unknown[]") return "json-array";
	return "string";
}

function renderWebhookPayload(
	typeName: string,
	notificationType: string,
	group: Group,
	docsUrl: string,
): string {
	const out: string[] = [];
	out.push(
		jsDoc([
			`Payload уведомления ${notificationType}.`,
			group.description.split("\n")[0] ?? "",
			`@see ${docsUrl}/#${group.anchor}`,
		]),
	);
	out.push(`export interface ${typeName} {\n`);
	for (const p of group.params) {
		const tsType = tsTypeForWebhook(p, notificationType);
		const optionalFlag = p.required ? "" : "?";
		const desc = cleanDescription(p.description);
		if (desc) out.push(`\t/** ${escapeJsDoc(desc)} */\n`);
		out.push(`\t${fieldName(p.name)}${optionalFlag}: ${tsType};\n`);
	}
	out.push("}\n");
	return out.join("");
}

function tsTypeForWebhook(param: Param, notificationType: string): string {
	const name = param.name.toLowerCase();
	// CloudKassir labels these identifiers as integers, but they can contain
	// leading zeroes and must survive form parsing byte-for-byte.
	if (notificationType === "Receipt" && (name === "devicenumber" || name === "inn")) {
		return "string";
	}
	if (name === "currency" || name === "paymentcurrency") return "Currency";
	if (name === "culturename") return "CultureName";
	if (name === "status" && notificationType === "Recurrent") return "SubscriptionStatus";
	if (name === "status") return "TransactionStatus";
	if (name === "operationtype") return "OperationType";
	if (notificationType === "Receipt" && name === "type") return "KktReceiptType";
	if (notificationType === "Receipt" && name === "receipt") return "KktReceipt";
	return tsTypeFor(param);
}

function renderWebhookUnion(): string {
	const out: string[] = [];
	out.push(jsDoc(["Union всех входящих webhook payload-ов. Тип определяется endpoint-ом."]));
	const members = WEBHOOK_PAYLOADS.map((w) => w.name).join(" | ");
	out.push(`export type AnyWebhookPayload = ${members};\n`);
	return out.join("");
}

/* ──────────────────────── index.ts ──────────────────────── */

function writeIndex(): string {
	return `${HEADER}
export * from "./meta.js";
export * from "./handbooks.js";
export * from "./endpoints.js";
export * from "./webhook-payloads.js";
`;
}

/* ──────────────────────── Entry ──────────────────────── */

async function main() {
	for (const source of Object.values(DOCS_SOURCES)) {
		if (!existsSync(source.irPath)) {
			console.error(
				`✗ ${source.irPath} not found. Run \`bun run docs:parse ${source.name}\` first.`,
			);
			process.exit(1);
		}
	}
	const irs = await loadIRs();

	const files: Array<[string, string]> = [
		["meta.ts", writeMeta(irs)],
		["handbooks.ts", writeHandbooks(irs.cloudpayments)],
		["endpoints.ts", writeEndpoints(irs)],
		["webhook-payloads.ts", writeWebhookPayloads(irs)],
		["index.ts", writeIndex()],
	];

	await rm(OUT_DIR, { recursive: true, force: true });
	await mkdir(OUT_DIR, { recursive: true });
	for (const [name, content] of files) {
		const out = resolve(OUT_DIR, name);
		await writeFile(out, content);
		console.log(`✓ Wrote src/_generated/${name} (${content.length} bytes)`);
	}
}

await main();
