#!/usr/bin/env bun
/**
 * Генерирует src/_generated/ из specs/ir.json:
 *   - meta.ts          — BASE_URL, SDK_API_DATE и пр.
 *   - handbooks.ts     — типы + мап-объекты для справочников (статусы, коды ошибок, валюты, …)
 *   - endpoints.ts     — Request-типы и URL-константы для всех API-методов
 *   - webhook-payloads.ts — payload-типы для входящих уведомлений
 *   - index.ts         — re-export всего
 */
import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import type { Group, IR, Param, Table } from "./parse.ts";

const IR_PATH = resolve(import.meta.dir, "..", "specs", "ir.json");
const OUT_DIR = resolve(import.meta.dir, "..", "src", "_generated");

const HEADER = `/**
 * AUTO-GENERATED by tools/gen.ts from specs/ir.json.
 * Do not edit directly — run \`bun run gen\` instead.
 */
`;

/* ──────────────────────────── Config ──────────────────────────── */

type HandbookAs = "stringUnion" | "numberUnion" | "stringEnum" | "numberEnum";

interface HandbookSpec {
	anchor: string;
	name: string;
	valueCol: string;
	labelCol: string;
	as: HandbookAs;
}

const HANDBOOKS: HandbookSpec[] = [
	{
		anchor: "statusy-operatsiy",
		name: "TransactionStatus",
		valueCol: "Статус",
		labelCol: "Описание",
		as: "stringUnion",
	},
	{
		anchor: "statusy-podpisok-rekurrent",
		name: "SubscriptionStatus",
		valueCol: "Статус",
		labelCol: "Описание",
		as: "stringUnion",
	},
	{
		anchor: "spisok-valyut",
		name: "Currency",
		valueCol: "Код",
		labelCol: "Название",
		as: "stringUnion",
	},
	{
		anchor: "cultures",
		name: "CultureName",
		valueCol: "Код",
		labelCol: "Язык",
		as: "stringUnion",
	},
	{
		anchor: "tipy-uvedomleniy",
		name: "NotificationType",
		valueCol: "Код",
		labelCol: "Название",
		as: "stringUnion",
	},
	{
		anchor: "tipy-operatsiy",
		name: "OperationType",
		valueCol: "Код",
		labelCol: "Название",
		as: "stringUnion",
	},
	{
		anchor: "kody-oshibok",
		name: "ReasonCode",
		valueCol: "Код",
		labelCol: "Название",
		as: "numberUnion",
	},
	{
		anchor: "operatory-fiskalnyh-dannyh",
		name: "FiscalDataOperator",
		valueCol: "Код",
		labelCol: "Название оператора",
		as: "stringUnion",
	},
	{
		anchor: "kody-vremennyh-zon",
		name: "TimeZoneCode",
		valueCol: "Код",
		labelCol: "Название",
		as: "stringUnion",
	},
	{
		anchor: "kody-obrabotki-otvetov-na-check-uvedomlenie",
		name: "CheckResponseCode",
		valueCol: "Код",
		labelCol: "Название",
		as: "numberUnion",
	},
];

interface EndpointAlias {
	anchor: string;
	module: "payments" | "subscriptions" | "orders" | "settings";
	methodName: string;
	/** Если у endpoint-а несколько URL, создаём несколько методов, выбирая URL по label-подстроке. */
	splitByUrlLabel?: Array<{ match: string; methodName: string }>;
	/** По-умолчанию берём url[0]. Этот индекс используется если splitByUrlLabel не задан и нужен не первый URL. */
	urlIndex?: number;
}

const ENDPOINT_ALIASES: EndpointAlias[] = [
	// /test
	{ anchor: "testovyy-metod", module: "payments", methodName: "test" },

	// /payments/cards/{charge|auth}
	{
		anchor: "oplata-po-kriptogramme",
		module: "payments",
		methodName: "chargeCryptogram",
		splitByUrlLabel: [
			{ match: "одностадийн", methodName: "chargeCryptogram" },
			{ match: "двухстадийн", methodName: "authCryptogram" },
		],
	},
	// /payments/cards/post3ds
	{ anchor: "primer-formy", module: "payments", methodName: "post3ds" },

	// /payments/tokens/{charge|auth}
	{
		anchor: "oplata-po-tokenu-rekarring",
		module: "payments",
		methodName: "chargeToken",
		splitByUrlLabel: [
			{ match: "одностадийн", methodName: "chargeToken" },
			{ match: "двухстадийн", methodName: "authToken" },
		],
	},

	// /payments/confirm, /void, /refund
	{ anchor: "podtverzhdenie-oplaty", module: "payments", methodName: "confirm" },
	{ anchor: "otmena-oplaty", module: "payments", methodName: "void" },
	{ anchor: "vozvrat-deneg", module: "payments", methodName: "refund" },

	// /payments/cards/topup, /payments/tokens/topup, /payments/qr/sbp/topup
	{ anchor: "vyplata-po-kriptogramme", module: "payments", methodName: "payoutCryptogram" },
	{ anchor: "vyplata-po-tokenu", module: "payments", methodName: "payoutToken" },
	{ anchor: "vyplata-po-sbp", module: "payments", methodName: "payoutSbp" },

	// /payments/get, /payments/list, /payments/list/v2, /payments/claims
	{ anchor: "prosmotr-tranzaktsii", module: "payments", methodName: "get" },
	{ anchor: "vygruzka-spiska-tranzaktsiy", module: "payments", methodName: "listByDay" },
	{
		anchor: "vygruzka-spiska-tranzaktsiy-za-proizvolnyy-period",
		module: "payments",
		methodName: "listByPeriod",
	},
	{
		anchor: "vygruzka-spiska-pretenziy-za-proizvolnyy-period",
		module: "payments",
		methodName: "listClaimsByPeriod",
	},
	{ anchor: "vygruzka-tokenov", module: "payments", methodName: "listTokens" },

	// /subscriptions/*
	{
		anchor: "sozdanie-podpiski-na-rekurrentnye-platezhi",
		module: "subscriptions",
		methodName: "create",
	},
	{ anchor: "zapros-informatsii-o-podpiske", module: "subscriptions", methodName: "get" },
	{ anchor: "poisk-podpisok", module: "subscriptions", methodName: "findByAccount" },
	{
		anchor: "izmenenie-podpiski-na-rekurrentnye-platezhi",
		module: "subscriptions",
		methodName: "update",
	},
	{
		anchor: "otmena-podpiski-na-rekurrentnye-platezhi",
		module: "subscriptions",
		methodName: "cancel",
	},

	// /orders/*
	{ anchor: "sozdanie-scheta-dlya-otpravki-po-pochte", module: "orders", methodName: "create" },
	{ anchor: "otmena-sozdannogo-scheta", module: "orders", methodName: "cancel" },

	// /site/notifications/*
	{ anchor: "prosmotr-nastroek-uvedomleniy", module: "settings", methodName: "getNotification" },
	{
		anchor: "izmenenie-nastroek-uvedomleniy",
		module: "settings",
		methodName: "updateNotification",
	},
];

/** anchor из #uvedomleniya раздела → идентификатор payload-типа */
const WEBHOOK_PAYLOADS = [
	{ anchor: "check", type: "Check", name: "CheckNotificationPayload" },
	{ anchor: "pay", type: "Pay", name: "PayNotificationPayload" },
	{ anchor: "fail", type: "Fail", name: "FailNotificationPayload" },
	{ anchor: "confirm", type: "Confirm", name: "ConfirmNotificationPayload" },
	{ anchor: "refund", type: "Refund", name: "RefundNotificationPayload" },
	{ anchor: "recurrent", type: "Recurrent", name: "RecurrentNotificationPayload" },
	{ anchor: "cancel", type: "Cancel", name: "CancelNotificationPayload" },
] as const;

const BASE_URL_PROD = "https://api.cloudpayments.ru";
/** Sandbox-режим у CP — не отдельный домен, а тестовые Public ID/Secret, см. #testirovanie. */
const BASE_URL_EU = "https://api.cloudpayments.eu";
const BASE_URL_KZ = "https://api.cp.kz";
const DOCS_URL = "https://developers.cloudpayments.ru";

/* ──────────────────────── Helpers: IR lookup ──────────────────────── */

async function loadIR(): Promise<IR> {
	const raw = await Bun.file(IR_PATH).text();
	return JSON.parse(raw) as IR;
}

function findGroupDeep(ir: IR, anchor: string): Group | null {
	for (const s of ir.sections) {
		for (const g of s.groups) {
			if (g.anchor === anchor) return g;
			for (const sg of g.subgroups) if (sg.anchor === anchor) return sg;
		}
	}
	return null;
}

/* ──────────────────────── Helpers: type mapping ──────────────────────── */

function tsTypeFor(param: Param): string {
	const t = param.type.trim().toLowerCase();
	if (!t) return "unknown";
	// date-format strings — "yyyy-MM-dd", "yyyy-MM-dd HH:mm:ss", ISO-шаблоны etc. → string
	if (/^y{2,4}[-./]/.test(t) || /datetime/.test(t) || /^date\b/.test(t)) return "string";
	if (/^string/.test(t) || /^guid\b/.test(t) || /^url\b/.test(t)) return "string";
	if (/^(long|int|integer|decimal|float|double|number)/.test(t)) return "number";
	if (/^bit\b/.test(t)) return "0 | 1";
	if (/^(bool|boolean)/.test(t)) return "boolean";
	if (/^json/.test(t)) return "Record<string, unknown>";
	if (/^object/.test(t)) return inferObjectType(param);
	if (/^(array|list)/.test(t)) return "unknown[]";
	return "unknown";
}

function inferObjectType(param: Param): string {
	const name = param.name.toLowerCase();
	if (name === "payer") return "Payer";
	if (name === "receipt" || name === "inn") return "Receipt";
	if (name === "cloudpayments") return "CloudPaymentsMeta";
	return "Record<string, unknown>";
}

function escapeJsDoc(text: string): string {
	return text.replace(/\*\//g, "*\\/");
}

/** Готовит JSDoc-комментарий: первая строка short-description, далее блоки если нужны. */
function jsDoc(lines: string[], indent = ""): string {
	const trimmed = lines.map((l) => l.trim()).filter(Boolean);
	if (trimmed.length === 0) return "";
	if (trimmed.length === 1) return `${indent}/** ${escapeJsDoc(trimmed[0] as string)} */\n`;
	const body = trimmed
		.flatMap((l) => l.split("\n"))
		.map((l) => `${indent} * ${escapeJsDoc(l)}`)
		.join("\n");
	return `${indent}/**\n${body}\n${indent} */\n`;
}

/** Безопасное имя поля — если содержит тире или начинается с цифры, квотим. */
function fieldName(name: string): string {
	if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) return name;
	return JSON.stringify(name);
}

/* ──────────────────────── meta.ts ──────────────────────── */

async function writeMeta(ir: IR): Promise<string> {
	const pkg = (await Bun.file(resolve(import.meta.dir, "..", "package.json")).json()) as {
		name: string;
		version: string;
	};
	return `${HEADER}
export const CP_SDK_NAME = ${JSON.stringify(pkg.name)} as const;
export const CP_SDK_VERSION = ${JSON.stringify(pkg.version)} as const;

export const CP_BASE_URL = ${JSON.stringify(BASE_URL_PROD)} as const;
export const CP_BASE_URL_EU = ${JSON.stringify(BASE_URL_EU)} as const;
export const CP_BASE_URL_KZ = ${JSON.stringify(BASE_URL_KZ)} as const;
export const CP_DOCS_URL = ${JSON.stringify(DOCS_URL)} as const;

/** Дата парсинга документации, по которой собраны эти типы. */
export const CP_SDK_DOCS_SHA256 = ${JSON.stringify(ir.source.htmlSha256)} as const;
export const CP_SDK_DOCS_PARSED_AT = ${JSON.stringify(ir.source.parsedAt)} as const;
`;
}

/* ──────────────────────── handbooks.ts ──────────────────────── */

function writeHandbooks(ir: IR): string {
	const parts: string[] = [HEADER];
	for (const spec of HANDBOOKS) {
		const group = findGroupDeep(ir, spec.anchor);
		if (!group) {
			console.warn(`! handbook not found: ${spec.anchor}`);
			continue;
		}
		const table = group.tables[0];
		if (!table) {
			console.warn(`! handbook ${spec.anchor} has no tables`);
			continue;
		}
		parts.push(renderHandbook(spec, table, group.title));
	}
	return parts.join("\n");
}

function renderHandbook(spec: HandbookSpec, table: Table, sectionTitle: string): string {
	const allRows = table.rows
		.map((row) => ({
			value: (row[spec.valueCol] ?? "").trim(),
			label: (row[spec.labelCol] ?? "").trim(),
			extra: Object.fromEntries(
				table.headers
					.filter((h) => h !== spec.valueCol && h !== spec.labelCol)
					.map((h) => [h, (row[h] ?? "").trim()]),
			) as Record<string, string>,
		}))
		.filter((r) => r.value !== "");
	// Дедупликация по value: например, один TZ-код CET у разных стран.
	const seen = new Set<string>();
	const rows: typeof allRows = [];
	for (const r of allRows) {
		if (seen.has(r.value)) continue;
		seen.add(r.value);
		rows.push(r);
	}

	const isNumeric = spec.as === "numberUnion" || spec.as === "numberEnum";
	const quote = (v: string): string => (isNumeric ? v : JSON.stringify(v));
	const values = rows.map((r) => quote(r.value)).join(" | ");
	const typeDecl = values.length > 0 ? values : "never";

	const jsdoc = jsDoc([sectionTitle, `@see ${DOCS_URL}/#${spec.anchor}`]);

	const out: string[] = [];
	out.push(jsdoc);
	out.push(`export type ${spec.name} = ${typeDecl};\n`);

	// Array литерал всех значений
	const arrayName = `${pascalToScreamingSnake(spec.name)}_VALUES`;
	out.push(jsDoc([`Все значения ${spec.name}.`]));
	out.push(
		`export const ${arrayName}: readonly ${spec.name}[] = [${rows
			.map((r) => quote(r.value))
			.join(", ")}] as const;\n`,
	);

	// Map: value → label
	const labelsMap = `${toCamelLower(spec.name)}Labels`;
	const labelEntries = rows
		.map((r) => `\t[${quote(r.value)}]: ${JSON.stringify(r.label)},`)
		.join("\n");
	out.push(jsDoc([`Человекочитаемые названия ${spec.name}.`]));
	out.push(`export const ${labelsMap}: Record<${spec.name}, string> = {\n${labelEntries}\n};\n`);

	// Дополнительные поля (если есть другие колонки помимо value/label)
	if (rows[0] && Object.keys(rows[0].extra).length > 0) {
		const extraMap = `${toCamelLower(spec.name)}Info`;
		const extraKeys = Object.keys(rows[0].extra);
		const infoType = `{ label: string; ${extraKeys.map((k) => `${fieldName(toCamelLower(k))}: string;`).join(" ")} }`;
		const entries = rows
			.map((r) => {
				const extras = Object.entries(r.extra)
					.map(([k, v]) => `${fieldName(toCamelLower(k))}: ${JSON.stringify(v)}`)
					.join(", ");
				return `\t[${quote(r.value)}]: { label: ${JSON.stringify(r.label)}, ${extras} },`;
			})
			.join("\n");
		out.push(jsDoc([`Полная информация по ${spec.name} (label + метаданные).`]));
		out.push(`export const ${extraMap}: Record<${spec.name}, ${infoType}> = {\n${entries}\n};\n`);
	}
	return out.join("");
}

function toCamelLower(pascal: string): string {
	return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

function pascalToScreamingSnake(pascal: string): string {
	return pascal.replace(/([a-z])([A-Z])/g, "$1_$2").toUpperCase();
}

/* ──────────────────────── endpoints.ts ──────────────────────── */

interface ResolvedEndpoint {
	alias: EndpointAlias;
	group: Group;
	urls: { url: string; label: string; methodName: string }[];
}

function resolveEndpoints(ir: IR): ResolvedEndpoint[] {
	const out: ResolvedEndpoint[] = [];
	for (const alias of ENDPOINT_ALIASES) {
		const group = findGroupDeep(ir, alias.anchor);
		if (!group) {
			console.warn(`! endpoint alias not found in IR: ${alias.anchor}`);
			continue;
		}
		if (group.urls.length === 0) {
			console.warn(`! endpoint ${alias.anchor} has no URLs`);
			continue;
		}

		if (alias.splitByUrlLabel) {
			const resolved: ResolvedEndpoint["urls"] = [];
			for (const split of alias.splitByUrlLabel) {
				const u = group.urls.find((x) => x.label.toLowerCase().includes(split.match.toLowerCase()));
				if (!u) {
					console.warn(`! split not matched for ${alias.anchor}: ${split.match}`);
					continue;
				}
				resolved.push({ url: u.url, label: u.label, methodName: split.methodName });
			}
			out.push({ alias, group, urls: resolved });
		} else {
			const idx = alias.urlIndex ?? 0;
			const u = group.urls[idx];
			if (!u) continue;
			out.push({
				alias,
				group,
				urls: [{ url: u.url, label: u.label, methodName: alias.methodName }],
			});
		}
	}
	return out;
}

function writeEndpoints(ir: IR): string {
	const endpoints = resolveEndpoints(ir);
	const parts: string[] = [HEADER];
	parts.push(`import type { Currency, CultureName } from "./handbooks.js";`);
	parts.push(`import type { Payer, Receipt, CloudPaymentsMeta } from "./shared.js";\n`);

	for (const ep of endpoints) {
		parts.push(renderEndpointBlock(ep));
	}

	parts.push(renderEndpointRegistry(endpoints));
	return parts.join("\n");
}

function renderEndpointBlock(ep: ResolvedEndpoint): string {
	const out: string[] = [];
	for (const url of ep.urls) {
		const prefix = pascal(ep.alias.module);
		const typeName = `${prefix}${pascal(url.methodName)}Request`;
		const urlConst = `${pascalToScreamingSnake(ep.alias.module)}_${pascalToScreamingSnake(url.methodName)}_URL`;
		out.push(renderRequestType(typeName, ep.group));
		out.push(`export const ${urlConst} = ${JSON.stringify(url.url)} as const;\n`);
	}
	return out.join("\n");
}

function renderRequestType(typeName: string, group: Group): string {
	const out: string[] = [];
	out.push(
		jsDoc([
			group.title,
			group.description.split("\n")[0] ?? "",
			`@see ${DOCS_URL}/#${group.anchor}`,
		]),
	);
	if (group.params.length === 0) {
		out.push(`export type ${typeName} = Record<string, never>;\n`);
		return out.join("");
	}
	out.push(`export interface ${typeName} {\n`);
	for (const p of group.params) {
		const tsType = tsTypeForNamed(p);
		const optionalFlag = p.required ? "" : "?";
		const desc = cleanDescription(p.description);
		if (desc) out.push(`\t/** ${escapeJsDoc(desc)} */\n`);
		out.push(`\t${fieldName(p.name)}${optionalFlag}: ${tsType};\n`);
	}
	out.push("}\n");
	return out.join("");
}

function tsTypeForNamed(param: Param): string {
	const name = param.name.toLowerCase();
	// Spec-осведомлённые сужения типов
	if (name === "currency") return "Currency";
	if (name === "culturename" || name === "culture") return "CultureName";
	return tsTypeFor(param);
}

function cleanDescription(desc: string): string {
	return desc.replace(/\s+/g, " ").trim();
}

function pascal(camel: string): string {
	return camel.charAt(0).toUpperCase() + camel.slice(1);
}

function renderEndpointRegistry(endpoints: ResolvedEndpoint[]): string {
	const byModule = new Map<string, Array<{ methodName: string; url: string }>>();
	for (const ep of endpoints) {
		for (const u of ep.urls) {
			const list = byModule.get(ep.alias.module) ?? [];
			list.push({ methodName: u.methodName, url: u.url });
			byModule.set(ep.alias.module, list);
		}
	}

	const out: string[] = [];
	out.push(jsDoc(["Реестр всех API-эндпоинтов, сгенерирован из IR."]));
	out.push("export const ENDPOINTS = {\n");
	for (const [module, methods] of byModule) {
		out.push(`\t${module}: {\n`);
		for (const m of methods) {
			out.push(
				`\t\t${m.methodName}: { url: ${JSON.stringify(m.url)}, method: "POST" as const },\n`,
			);
		}
		out.push("\t},\n");
	}
	out.push("} as const;\n");
	return out.join("");
}

/* ──────────────────────── webhook-payloads.ts ──────────────────────── */

function writeWebhookPayloads(ir: IR): string {
	const parts: string[] = [HEADER];
	parts.push(
		`import type { NotificationType, OperationType, TransactionStatus, Currency, CultureName } from "./handbooks.js";\n`,
	);

	for (const spec of WEBHOOK_PAYLOADS) {
		const g = findGroupDeep(ir, spec.anchor);
		if (!g) {
			console.warn(`! webhook payload not found: ${spec.anchor}`);
			continue;
		}
		parts.push(renderWebhookPayload(spec.name, spec.type, g));
	}

	parts.push(renderWebhookUnion());
	return parts.join("\n");
}

function renderWebhookPayload(typeName: string, notificationType: string, group: Group): string {
	const out: string[] = [];
	out.push(
		jsDoc([
			`Payload уведомления ${notificationType}.`,
			group.description.split("\n")[0] ?? "",
			`@see ${DOCS_URL}/#${group.anchor}`,
		]),
	);
	out.push(`export interface ${typeName} {\n`);
	for (const p of group.params) {
		const tsType = tsTypeForWebhook(p);
		const optionalFlag = p.required ? "" : "?";
		const desc = cleanDescription(p.description);
		if (desc) out.push(`\t/** ${escapeJsDoc(desc)} */\n`);
		out.push(`\t${fieldName(p.name)}${optionalFlag}: ${tsType};\n`);
	}
	out.push("}\n");
	return out.join("");
}

function tsTypeForWebhook(param: Param): string {
	const name = param.name.toLowerCase();
	if (name === "currency" || name === "paymentcurrency") return "Currency";
	if (name === "culturename") return "CultureName";
	if (name === "status") return "TransactionStatus";
	if (name === "operationtype") return "OperationType";
	return tsTypeFor(param);
}

function renderWebhookUnion(): string {
	const out: string[] = [];
	out.push(jsDoc(["Discriminated union всех входящих payload-ов по заголовку X-Content-HMAC."]));
	const members = WEBHOOK_PAYLOADS.map((w) => w.name).join(" | ");
	out.push(`export type AnyWebhookPayload = ${members};\n`);
	return out.join("");
}

/* ──────────────────────── shared shapes — кандидаты в src/modules/ ──────────────────────── */

/** Заголовок + заглушка для общих типов, которые пишутся руками. */
function writeSharedTypesStub(): string {
	return `${HEADER}
/**
 * Вложенные объекты, которые в документации CloudPayments передаются как "Object"
 * без формального schema. Описаны вручную исходя из текста описаний и примеров.
 * Эти типы используют Request-типы из endpoints.ts — не удаляйте и не переименовывайте.
 */

/** Плательщик (Payer object в charge/auth/payout/...) */
export interface Payer {
	FirstName?: string;
	LastName?: string;
	MiddleName?: string;
	/** Дата рождения, YYYY-MM-DD. */
	Birth?: string;
	Address?: string;
	Street?: string;
	City?: string;
	Country?: string;
	/** Телефон, только цифры, формат «+71234567890». */
	Phone?: string;
	Postcode?: string;
}

/** Онлайн-чек 54-ФЗ (передаётся в cloudpayments.CustomerReceipt). */
export interface Receipt {
	Items: ReceiptItem[];
	taxationSystem?: number;
	email?: string;
	phone?: string;
	isBso?: boolean;
	AgentSign?: string | null;
	amounts?: ReceiptAmounts;
}

export interface ReceiptItem {
	label: string;
	price: number;
	quantity: number;
	amount: number;
	vat?: number | null;
	method: number;
	object: number;
	measurementUnit?: string;
	agentSign?: string | null;
}

export interface ReceiptAmounts {
	electronic: number;
	advancePayment?: number;
	credit?: number;
	provision?: number;
}

/** cloudpayments-namespace внутри JsonData — инструкции для формирования подписки/чека. */
export interface CloudPaymentsMeta {
	CustomerReceipt?: Receipt;
	recurrent?: {
		interval: "Day" | "Week" | "Month";
		period: number;
		customerReceipt?: Receipt;
		amount?: number;
		startDate?: string;
		maxPeriods?: number | null;
	};
	ShouldAuthenticate3DS?: boolean;
}
`;
}

/* ──────────────────────── index.ts ──────────────────────── */

function writeIndex(): string {
	return `${HEADER}
export * from "./meta.js";
export * from "./handbooks.js";
export * from "./endpoints.js";
export * from "./webhook-payloads.js";
export * from "./shared.js";
`;
}

/* ──────────────────────── Entry ──────────────────────── */

async function main() {
	if (!existsSync(IR_PATH)) {
		console.error("✗ specs/ir.json not found. Run `bun run docs:parse` first.");
		process.exit(1);
	}
	const ir = await loadIR();

	await mkdir(OUT_DIR, { recursive: true });

	const files: Array<[string, string]> = [
		["meta.ts", await writeMeta(ir)],
		["handbooks.ts", writeHandbooks(ir)],
		["endpoints.ts", writeEndpoints(ir)],
		["webhook-payloads.ts", writeWebhookPayloads(ir)],
		["shared.ts", writeSharedTypesStub()],
		["index.ts", writeIndex()],
	];

	for (const [name, content] of files) {
		const out = resolve(OUT_DIR, name);
		await writeFile(out, content);
		console.log(`✓ Wrote src/_generated/${name} (${content.length} bytes)`);
	}
}

await main();
